LArCV: larcv::Voxel3DMeta Class Reference
larcv::Voxel3DMeta Class Reference
Meta data for defining voxels (ID, size, position) and voxelized volume (coordinate, size)
#include <Voxel3DMeta.h>
Public Member Functions
Voxel3DMeta ()
Default ctor.
~Voxel3DMeta ()
Default dtor.
void update (size_t xnum, size_t ynum, size_t znum)
Update voxel count.
void set (double xmin, double ymin, double zmin, double xmax, double ymax, double zmax, size_t xnum, size_t ynum, size_t znum, DistanceUnit_t unit=kUnitCM)
Define dimensions.
void clear ()
Clear method.
bool operator== (const Voxel3DMeta &rhs) const
Uniry == operator.
bool operator!= (const Voxel3DMeta &rhs) const
Uniry != operator.
bool valid () const
Checker if the meta parameters are set properly or not.
VoxelID_t size () const
Returns size.
VoxelID_t id (const Point3D &pt) const
Given a position, returns voxel ID.
VoxelID_t id (const double x, const double y, const double z) const
Given a position, returns voxel ID.
VoxelID_t shift (const VoxelID_t origin_id, const int shift_x, const int shift_y, const int shift_z) const
Given a voxel id, returns a neighbor voxel ID with (x,y,z) shift.
VoxelID_t invalid_voxel_id () const
Return value of invalid voxel ID:
Point3D position (VoxelID_t id) const
Given a valid voxel ID, returns a position array.
double pos_x (VoxelID_t id) const
Given a valid voxel ID, returns X position.
double pos_y (VoxelID_t id) const
Given a valid voxel ID, returns Y position.
double pos_z (VoxelID_t id) const
Given a valid voxel ID, returns Z position.
size_t num_voxel_x () const
Returns voxel count along x-axis.
size_t num_voxel_y () const
Returns voxel count along y-axis.
size_t num_voxel_z () const
Returns voxel count along z-axis.
double size_voxel_x () const
Returns voxel size along x-axis;.
double size_voxel_y () const
Returns voxel size along y-axis;.
double size_voxel_z () const
Returns voxel size along z-axis;.
DistanceUnit_t unit () const
Distance unit.
std::string dump () const
text dumper
bool operator== (const BBox3D &rhs) const
void update (double xmin, double ymin, double zmin, double xmax, double ymax, double zmax)
void update (const Point3D &pt1, const Point3D &pt2)
bool empty () const
const Point3D & origin () const
const Point3D & bottom_left () const
const Point3D & top_right () const
Point3D center () const
double center_x () const
double center_y () const
double center_z () const
double min_x () const
double min_y () const
double min_z () const
double max_x () const
double max_y () const
double max_z () const
double width () const
double height () const
double depth () const
double volume () const
double area (int axis) const
BBox3D overlap (const BBox3D &box) const
BBox3D inclusive (const BBox3D &box) const
Private Attributes
bool _valid
Boolean set to true only if voxel parameters are properly set.
size_t _num_element
Total number of voxel elements.
double _xlen
X voxel size in [cm].
double _ylen
Y voxel size in [cm].
double _zlen
Z voxel size in [cm].
size_t _xnum
Number of voxels along X.
size_t _ynum
Number of voxels along Y.
size_t _znum
Number of voxels along Z.
DistanceUnit_t _unit
length unit
Detailed Description
Meta data for defining voxels (ID, size, position) and voxelized volume (coordinate, size)
Definition at line 27 of file Voxel3DMeta.h.
Constructor & Destructor Documentation
larcv::Voxel3DMeta::Voxel3DMeta ()
Default ctor.
Definition at line 10 of file Voxel3DMeta.cxx.
References clear().
   { clear(); }
larcv::Voxel3DMeta::~Voxel3DMeta () inline
Default dtor.
Definition at line 32 of file Voxel3DMeta.h.
 {}
Member Function Documentation
double larcv::BBox3D::area (int axis) const inherited
Definition at line 92 of file BBox.cxx.
References larcv::BBox3D::_p1, larcv::BBox3D::_p2, larcv::Point3D::x, larcv::Point3D::y, and larcv::Point3D::z.
   {
     if(axis == 0) return (_p2.x - _p1.x) * (_p2.y - _p1.y); // xy projection
     if(axis == 1) return (_p2.x - _p1.x) * (_p2.z - _p1.z); // xz projection
     if(axis == 2) return (_p2.y - _p1.y) * (_p2.z - _p1.z); // yz projection
     throw larbys("BBox3D::area can only take axis=[0,1,2]!");
   }
const Point3D& larcv::BBox3D::bottom_left () const inline inherited
Definition at line 97 of file BBox.h.
References larcv::BBox3D::_p1.
 { return _p1; }
Point3D larcv::BBox3D::center () const inline inherited
Definition at line 99 of file BBox.h.
References larcv::BBox3D::center_x(), larcv::BBox3D::center_y(), and larcv::BBox3D::center_z().
 { return Point3D(center_x(), center_y(), center_z()); }
double larcv::BBox3D::center_x () const inline inherited
Definition at line 100 of file BBox.h.
References larcv::BBox3D::_p1, larcv::BBox3D::_p2, and larcv::Point3D::x.
Referenced by larcv::BBox3D::center().
 { return _p1.x + 0.5*(_p2.x - _p1.x); }
double larcv::BBox3D::center_y () const inline inherited
Definition at line 101 of file BBox.h.
References larcv::BBox3D::_p1, larcv::BBox3D::_p2, and larcv::Point3D::y.
Referenced by larcv::BBox3D::center().
 { return _p1.y + 0.5*(_p2.y - _p1.y); }
double larcv::BBox3D::center_z () const inline inherited
Definition at line 102 of file BBox.h.
References larcv::BBox3D::_p1, larcv::BBox3D::_p2, and larcv::Point3D::z.
Referenced by larcv::BBox3D::center().
 { return _p1.z + 0.5*(_p2.z - _p1.z); }
void larcv::Voxel3DMeta::clear ()
Clear method.
Definition at line 13 of file Voxel3DMeta.cxx.
References _unit, _valid, _xlen, _xnum, _ylen, _ynum, _zlen, _znum, larcv::BBox3D::BBox3D(), and larcv::kUnitUnknown.
Referenced by larcv::PyCluster3DMaker::initialize(), larcv::PyCluster3DMaker::process(), and Voxel3DMeta().
   {
     (BBox3D)(*this) = BBox3D();
     _valid = false;
     _xnum = _ynum = _znum = 0;
     _xlen = _ylen = _zlen = -1.;
     _unit = kUnitUnknown;
   }
double larcv::BBox3D::depth () const inline inherited
Definition at line 111 of file BBox.h.
References larcv::BBox3D::_p1, larcv::BBox3D::_p2, and larcv::Point3D::z.
 { return _p2.z - _p1.z; }
std::string larcv::Voxel3DMeta::dump () const
text dumper
Definition at line 138 of file Voxel3DMeta.cxx.
References _xnum, _ynum, _znum, larcv::BBox3D::max_x(), larcv::BBox3D::max_y(), larcv::BBox3D::max_z(), larcv::BBox3D::min_x(), larcv::BBox3D::min_y(), and larcv::BBox3D::min_z().
   {
     std::stringstream ss;
     ss << "X range: " << min_x() << " => " << max_x() << " ... " << _xnum << " bins" << std::endl
        << "Y range: " << min_y() << " => " << max_y() << " ... " << _ynum << " bins" << std::endl
        << "Z range: " << min_z() << " => " << max_z() << " ... " << _znum << " bins" << std::endl;
     return std::string(ss.str());
   }
bool larcv::BBox3D::empty () const inline inherited
Definition at line 95 of file BBox.h.
References larcv::BBox3D::_p1, and larcv::BBox3D::_p2.
Referenced by update().
 { return (_p1 == _p2); }
double larcv::BBox3D::height () const inline inherited
Definition at line 110 of file BBox.h.
References larcv::BBox3D::_p1, larcv::BBox3D::_p2, and larcv::Point3D::y.
 { return _p2.y - _p1.y; }
VoxelID_t larcv::Voxel3DMeta::id (const Point3D & pt) const inline
Given a position, returns voxel ID.
Definition at line 59 of file Voxel3DMeta.h.
References larcv::Point3D::x, larcv::Point3D::y, and larcv::Point3D::z.
Referenced by larcv::SparseTensor3D::emplace(), larcv::SparseTensor3D::meta(), and larcv::ClusterVoxel3D::meta().
     { return id(pt.x, pt.y, pt.z); }
VoxelID_t larcv::Voxel3DMeta::id (const double x, const double y, const double z) const
Given a position, returns voxel ID.
Definition at line 49 of file Voxel3DMeta.cxx.
References _valid, _xlen, _xnum, _ylen, _ynum, _zlen, _znum, larcv::kINVALID_VOXELID, larcv::BBox3D::max_x(), larcv::BBox3D::max_y(), larcv::BBox3D::max_z(), larcv::BBox3D::min_x(), larcv::BBox3D::min_y(), and larcv::BBox3D::min_z().
   {
     if(!_valid) throw larbys("Voxel3DMeta::ID cannot be called on invalid meta!");
     if(x > max_x() || x < min_x()) return kINVALID_VOXELID;
     if(y > max_y() || y < min_y()) return kINVALID_VOXELID;
     if(z > max_z() || z < min_z()) return kINVALID_VOXELID;
     VoxelID_t xindex = (x - min_x()) / _xlen;
     VoxelID_t yindex = (y - min_y()) / _ylen;
     VoxelID_t zindex = (z - min_z()) / _zlen;
     if(xindex == _xnum) xindex -= 1;
     if(yindex == _ynum) yindex -= 1;
     if(zindex == _znum) zindex -= 1;
     return (zindex * (_xnum * _ynum) + yindex * _xnum + xindex);
   }
BBox3D larcv::BBox3D::inclusive (const BBox3D & box) const inherited
Definition at line 128 of file BBox.cxx.
References larcv::BBox3D::BBox3D(), larcv::BBox3D::max_x(), larcv::BBox3D::max_y(), larcv::BBox3D::max_z(), larcv::BBox3D::min_x(), larcv::BBox3D::min_y(), and larcv::BBox3D::min_z().
   {
     double min_x = ( box.min_x() < this->min_x() ? box.min_x() : this->min_x() ); //pick smaller x min-boudn
     double max_x = ( box.max_x() > this->max_x() ? box.max_x() : this->max_x() ); //pick larger x max-bound
     double min_y = ( box.min_y() < this->min_y() ? box.min_y() : this->min_y() ); //pick smaller y min-boudn
     double max_y = ( box.max_y() > this->max_y() ? box.max_y() : this->max_y() ); //pick larger y max-bound
     double min_z = ( box.min_z() < this->min_z() ? box.min_z() : this->min_z() ); //pick smaller z min-boudn
     double max_z = ( box.max_z() > this->max_z() ? box.max_z() : this->max_z() ); //pick larger z max-bound
     return BBox3D(min_x, min_y, min_z, max_x, max_y, max_z);
   }
VoxelID_t larcv::Voxel3DMeta::invalid_voxel_id () const inline
Return value of invalid voxel ID:
Definition at line 67 of file Voxel3DMeta.h.
References larcv::kINVALID_VOXELID.
 {return kINVALID_VOXELID;}
double larcv::BBox3D::max_x () const inline inherited
Definition at line 106 of file BBox.h.
References larcv::BBox3D::_p2, and larcv::Point3D::x.
Referenced by dump(), id(), larcv::BBox3D::inclusive(), larcv::BBox3D::overlap(), and update().
 { return _p2.x; }
double larcv::BBox3D::max_y () const inline inherited
Definition at line 107 of file BBox.h.
References larcv::BBox3D::_p2, and larcv::Point3D::y.
Referenced by dump(), id(), larcv::BBox3D::inclusive(), larcv::BBox3D::overlap(), and update().
 { return _p2.y; }
double larcv::BBox3D::max_z () const inline inherited
Definition at line 108 of file BBox.h.
References larcv::BBox3D::_p2, and larcv::Point3D::z.
Referenced by dump(), id(), larcv::BBox3D::inclusive(), larcv::BBox3D::overlap(), and update().
 { return _p2.z; }
double larcv::BBox3D::min_x () const inline inherited
Definition at line 103 of file BBox.h.
References larcv::BBox3D::_p1, and larcv::Point3D::x.
Referenced by dump(), id(), larcv::BBox3D::inclusive(), larcv::BBox3D::overlap(), pos_x(), position(), and update().
 { return _p1.x; }
double larcv::BBox3D::min_y () const inline inherited
Definition at line 104 of file BBox.h.
References larcv::BBox3D::_p1, and larcv::Point3D::y.
Referenced by dump(), id(), larcv::BBox3D::inclusive(), larcv::BBox3D::overlap(), pos_y(), position(), and update().
 { return _p1.y; }
double larcv::BBox3D::min_z () const inline inherited
Definition at line 105 of file BBox.h.
References larcv::BBox3D::_p1, and larcv::Point3D::z.
Referenced by dump(), id(), larcv::BBox3D::inclusive(), larcv::BBox3D::overlap(), pos_z(), position(), and update().
 { return _p1.z; }
size_t larcv::Voxel3DMeta::num_voxel_x () const inline
Returns voxel count along x-axis.
Definition at line 77 of file Voxel3DMeta.h.
References _xnum.
 { return _xnum; }
size_t larcv::Voxel3DMeta::num_voxel_y () const inline
Returns voxel count along y-axis.
Definition at line 79 of file Voxel3DMeta.h.
References _ynum.
 { return _ynum; }
size_t larcv::Voxel3DMeta::num_voxel_z () const inline
Returns voxel count along z-axis.
Definition at line 81 of file Voxel3DMeta.h.
References _znum.
 { return _znum; }
bool larcv::Voxel3DMeta::operator!= (const Voxel3DMeta & rhs) const inline
Uniry != operator.
Definition at line 52 of file Voxel3DMeta.h.
     { return !((*this) == rhs); }
bool larcv::Voxel3DMeta::operator== (const Voxel3DMeta & rhs) const inline
Uniry == operator.
Definition at line 47 of file Voxel3DMeta.h.
References _xlen, _xnum, _ylen, _ynum, _zlen, and _znum.
     { return ((BBox3D)(rhs) == (BBox3D)(*this) &&
               _xlen == rhs._xlen && _ylen == rhs._ylen && _zlen == rhs._zlen &&
               _xnum == rhs._xnum && _ynum == rhs._ynum && _znum == rhs._znum); }
bool larcv::BBox3D::operator== (const BBox3D & rhs) const inline inherited
Definition at line 88 of file BBox.h.
References larcv::BBox3D::_p1, and larcv::BBox3D::_p2.
     { return (_p1 == rhs._p1 && _p2 == rhs._p2); }
const Point3D& larcv::BBox3D::origin () const inline inherited
Definition at line 96 of file BBox.h.
References larcv::BBox3D::_p1.
 { return _p1; }
BBox3D larcv::BBox3D::overlap (const BBox3D & box) const inherited
Definition at line 101 of file BBox.cxx.
References larcv::BBox3D::BBox3D(), larcv::BBox3D::max_x(), larcv::BBox3D::max_y(), larcv::BBox3D::max_z(), larcv::BBox3D::min_x(), larcv::BBox3D::min_y(), and larcv::BBox3D::min_z().
   {
     double minx = ( box.min_x() < this->min_x() ? this->min_x() : box.min_x()  ); //pick larger x min-bound
     double maxx = ( box.max_x() < this->max_x() ? box.max_x()  : this->max_x() ); //pick smaller x max-bound
     double miny = ( box.min_y() < this->min_y() ? this->min_y() : box.min_y()  ); //pick larger x min-bound
     double maxy = ( box.max_y() < this->max_y() ? box.max_y()  : this->max_y() ); //pick smaller x max-bound
     double minz = ( box.min_z() < this->min_z() ? this->min_z() : box.min_z()  ); //pick larger x min-bound
     double maxz = ( box.max_z() < this->max_z() ? box.max_z()  : this->max_z() ); //pick smaller x max-bound
     if(!(minx < maxx && miny < maxy && minz < maxz)) {
       std::stringstream ss;
       ss << "No overlap found ... this"
      << " X: " << this->min_x() << " => " << this->max_x()
      << " Y: " << this->min_y() << " => " << this->max_y()
      << " Z: " << this->min_z() << " => " << this->max_z()
      << " ... the other"
      << " X: " << box.min_x() << " => " << box.max_x()
      << " Y: " << box.min_y() << " => " << box.max_y()
      << " Z: " << box.min_z() << " => " << box.max_z()
      << std::endl;
       throw larbys(ss.str());
     }
     return BBox3D(minx, miny, minz, maxx, maxy, maxz);
   }
double larcv::Voxel3DMeta::pos_x (VoxelID_t id) const
Given a valid voxel ID, returns X position.
Definition at line 105 of file Voxel3DMeta.cxx.
References _num_element, _valid, _xlen, _xnum, _ynum, and larcv::BBox3D::min_x().
   {
     if(!_valid) throw larbys("Voxel3DMeta::pos_x cannot be called on invalid meta!");
     if(id >= _num_element) throw larbys("Voxel3DMeta::pos_x invalid VoxelID_t!");
     VoxelID_t zid = id / (_xnum * _ynum);
     id -= zid * (_xnum * _ynum);
     VoxelID_t yid = id / _xnum;
     VoxelID_t xid = (id - yid * _xnum);
     return min_x() + ((double)xid + 0.5) * _xlen;
   }
double larcv::Voxel3DMeta::pos_y (VoxelID_t id) const
Given a valid voxel ID, returns Y position.
Definition at line 118 of file Voxel3DMeta.cxx.
References _num_element, _valid, _xnum, _ylen, _ynum, and larcv::BBox3D::min_y().
   {
     if(!_valid) throw larbys("Voxel3DMeta::pos_y cannot be called on invalid meta!");
     if(id >= _num_element) throw larbys("Voxel3DMeta::pos_y invalid VoxelID_t!");
     VoxelID_t zid = id / (_xnum * _ynum);
     id -= zid * (_xnum * _ynum);
     VoxelID_t yid = id / _xnum;
     return min_y() + ((double)yid + 0.5) * _ylen;
   }
double larcv::Voxel3DMeta::pos_z (VoxelID_t id) const
Given a valid voxel ID, returns Z position.
Definition at line 129 of file Voxel3DMeta.cxx.
References _num_element, _valid, _xnum, _ynum, _zlen, and larcv::BBox3D::min_z().
   {
     if(!_valid) throw larbys("Voxel3DMeta::pos_z cannot be called on invalid meta!");
     if(id >= _num_element) throw larbys("Voxel3DMeta::pos_z invalid VoxelID_t!");
     VoxelID_t zid = id / (_xnum * _ynum);
     return min_z() + ((double)zid + 0.5) * _zlen;
   }
Point3D larcv::Voxel3DMeta::position (VoxelID_t id) const
Given a valid voxel ID, returns a position array.
Definition at line 90 of file Voxel3DMeta.cxx.
References _num_element, _valid, _xlen, _xnum, _ylen, _ynum, _zlen, larcv::BBox3D::min_x(), larcv::BBox3D::min_y(), and larcv::BBox3D::min_z().
   {
     if(!_valid) throw larbys("Voxel3DMeta::pos cannot be called on invalid meta!");
     if(id >= _num_element) throw larbys("Voxel3DMeta::pos invalid VoxelID_t!");
     VoxelID_t zid = id / (_xnum * _ynum);
     id -= zid * (_xnum * _ynum);
     VoxelID_t yid = id / _xnum;
     VoxelID_t xid = (id - yid * _xnum);
     return Point3D(min_x() + ((double)xid + 0.5) * _xlen,
            min_y() + ((double)yid + 0.5) * _ylen,
            min_z() + ((double)zid + 0.5) * _zlen);
   }
void larcv::Voxel3DMeta::set (double xmin, double ymin, double zmin, double xmax, double ymax, double zmax, size_t xnum, size_t ynum, size_t znum, DistanceUnit_t unit = kUnitCM) inline
Define dimensions.
Definition at line 36 of file Voxel3DMeta.h.
References _unit, unit(), update(), and larcv::BBox3D::update().
     { BBox3D::update(xmin,ymin,zmin,xmax,ymax,zmax);
       Voxel3DMeta::update(xnum,ynum,znum);
       _unit = unit;
     }
VoxelID_t larcv::Voxel3DMeta::shift (const VoxelID_t origin_id, const int shift_x, const int shift_y, const int shift_z) const
Given a voxel id, returns a neighbor voxel ID with (x,y,z) shift.
Definition at line 67 of file Voxel3DMeta.cxx.
References _xnum, _ynum, _znum, and larcv::kINVALID_VOXELID.
   {
     int id = origin_id;
     int zid = id / (_xnum * _ynum);
     id -= zid * (_xnum * _ynum);
     zid += shift_z;
     if(zid < 0 || zid >= (int)_znum) return kINVALID_VOXELID;
     int yid = id / _xnum;
     int xid = id - yid * _xnum;
     yid += shift_y;
     if(yid < 0 || yid >= (int)_ynum) return kINVALID_VOXELID;
     xid += shift_x;
     if(xid < 0 || xid >= (int)_xnum) return kINVALID_VOXELID;
     return (zid * (_xnum * _ynum) + yid * _xnum + xid);
   }
VoxelID_t larcv::Voxel3DMeta::size () const inline
Returns size.
Definition at line 57 of file Voxel3DMeta.h.
References _num_element.
Referenced by larcv::SparseTensor3D::meta(), and larcv::ClusterVoxel3D::meta().
 { return _num_element; }
double larcv::Voxel3DMeta::size_voxel_x () const inline
Returns voxel size along x-axis;.
Definition at line 83 of file Voxel3DMeta.h.
References _xlen.
 { return _xlen; }
double larcv::Voxel3DMeta::size_voxel_y () const inline
Returns voxel size along y-axis;.
Definition at line 85 of file Voxel3DMeta.h.
References _ylen.
 { return _ylen; }
double larcv::Voxel3DMeta::size_voxel_z () const inline
Returns voxel size along z-axis;.
Definition at line 87 of file Voxel3DMeta.h.
References _zlen.
 { return _zlen; }
const Point3D& larcv::BBox3D::top_right () const inline inherited
Definition at line 98 of file BBox.h.
References larcv::BBox3D::_p2.
 { return _p2; }
DistanceUnit_t larcv::Voxel3DMeta::unit () const inline
Distance unit.
Definition at line 89 of file Voxel3DMeta.h.
References _unit.
Referenced by set().
 { return _unit; }
void larcv::Voxel3DMeta::update (size_t xnum, size_t ynum, size_t znum)
Update voxel count.
Definition at line 22 of file Voxel3DMeta.cxx.
References _num_element, _valid, _xlen, _xnum, _ylen, _ynum, _zlen, _znum, larcv::BBox3D::empty(), larcv::kINVALID_SIZE, larcv::BBox3D::max_x(), larcv::BBox3D::max_y(), larcv::BBox3D::max_z(), larcv::BBox3D::min_x(), larcv::BBox3D::min_y(), and larcv::BBox3D::min_z().
Referenced by set().
{
     if(empty())
       throw larbys("Empty voxel volume definition cannot be updated with new voxel counts!");
     if(xnum == kINVALID_SIZE || xnum == 0)
       throw larbys("Voxel3DMeta::Set x voxel count not set!");
     if(ynum == kINVALID_SIZE || ynum == 0)
       throw larbys("Voxel3DMeta::Set y voxel count not set!");
     if(znum == kINVALID_SIZE || znum == 0)
       throw larbys("Voxel3DMeta::Set z voxel count not set!");
     _xlen = (max_x() - min_x()) / ((double)xnum);
     _xnum = xnum;
     _ylen = (max_y() - min_y()) / ((double)ynum);
     _ynum = ynum;
     _zlen = (max_z() - min_z()) / ((double)znum);
     _znum = znum;
     _num_element = _xnum * _ynum * _znum;
     _valid = true;
   }
void larcv::BBox3D::update (double xmin, double ymin, double zmin, double xmax, double ymax, double zmax) inherited
Definition at line 79 of file BBox.cxx.
References larcv::BBox3D::_p1, larcv::BBox3D::_p2, larcv::Point3D::x, larcv::Point3D::y, and larcv::Point3D::z.
Referenced by set(), and larcv::BBox3D::update().
   {
     if(xmin > xmax) throw larbys("xmin > xmax not allowed for BBox3D::Update!");
     if(ymin > ymax) throw larbys("ymin > ymax not allowed for BBox3D::Update!");
     if(zmin > zmax) throw larbys("zmin > zmax not allowed for BBox3D::Update!");
     _p1.x = xmin; _p1.y = ymin; _p1.z = zmin;
     _p2.x = xmax, _p2.y = ymax; _p2.z = zmax;
   }
void larcv::BBox3D::update (const Point3D & pt1, const Point3D & pt2) inherited
Definition at line 89 of file BBox.cxx.
References larcv::BBox3D::update(), larcv::Point3D::x, larcv::Point3D::y, and larcv::Point3D::z.
   { update(p1.x,p1.y,p1.z,p2.x,p2.y,p2.z); }
bool larcv::Voxel3DMeta::valid () const inline
Checker if the meta parameters are set properly or not.
Definition at line 55 of file Voxel3DMeta.h.
References _valid.
 { return _valid; }
double larcv::BBox3D::volume () const inline inherited
Definition at line 112 of file BBox.h.
References larcv::BBox3D::_p1, larcv::BBox3D::_p2, larcv::Point3D::x, larcv::Point3D::y, and larcv::Point3D::z.
 { return (_p2.x - _p1.x) * (_p2.y - _p1.y) * (_p2.z - _p1.z); }
double larcv::BBox3D::width () const inline inherited
Definition at line 109 of file BBox.h.
References larcv::BBox3D::_p1, larcv::BBox3D::_p2, and larcv::Point3D::x.
 { return _p2.x - _p1.x; }
Member Data Documentation
size_t larcv::Voxel3DMeta::_num_element private
Total number of voxel elements.
Definition at line 96 of file Voxel3DMeta.h.
Referenced by pos_x(), pos_y(), pos_z(), position(), size(), and update().
DistanceUnit_t larcv::Voxel3DMeta::_unit private
length unit
Definition at line 106 of file Voxel3DMeta.h.
Referenced by clear(), set(), and unit().
bool larcv::Voxel3DMeta::_valid private
Boolean set to true only if voxel parameters are properly set.
Definition at line 95 of file Voxel3DMeta.h.
Referenced by clear(), id(), pos_x(), pos_y(), pos_z(), position(), update(), and valid().
double larcv::Voxel3DMeta::_xlen private
X voxel size in [cm].
Definition at line 98 of file Voxel3DMeta.h.
Referenced by clear(), id(), operator==(), pos_x(), position(), size_voxel_x(), and update().
size_t larcv::Voxel3DMeta::_xnum private
Number of voxels along X.
Definition at line 102 of file Voxel3DMeta.h.
Referenced by clear(), dump(), id(), num_voxel_x(), operator==(), pos_x(), pos_y(), pos_z(), position(), shift(), and update().
double larcv::Voxel3DMeta::_ylen private
Y voxel size in [cm].
Definition at line 99 of file Voxel3DMeta.h.
Referenced by clear(), id(), operator==(), pos_y(), position(), size_voxel_y(), and update().
size_t larcv::Voxel3DMeta::_ynum private
Number of voxels along Y.
Definition at line 103 of file Voxel3DMeta.h.
Referenced by clear(), dump(), id(), num_voxel_y(), operator==(), pos_x(), pos_y(), pos_z(), position(), shift(), and update().
double larcv::Voxel3DMeta::_zlen private
Z voxel size in [cm].
Definition at line 100 of file Voxel3DMeta.h.
Referenced by clear(), id(), operator==(), pos_z(), position(), size_voxel_z(), and update().
size_t larcv::Voxel3DMeta::_znum private
Number of voxels along Z.
Definition at line 104 of file Voxel3DMeta.h.
Referenced by clear(), dump(), id(), num_voxel_z(), operator==(), shift(), and update().
The documentation for this class was generated from the following files:
Voxel3DMeta.h
Voxel3DMeta.cxx