LArCV: larcv::SparseTensor2D Class Reference
larcv::SparseTensor2D Class Reference
Container of multiple (2D-projected) voxel set array.
#include <Voxel2D.h>
Public Member Functions
SparseTensor2D ()
Default ctor.
virtual ~SparseTensor2D ()
Default dtor.
SparseTensor2D (const larcv::VoxelSet &vs)
copy ctor w/ VoxelSet
SparseTensor2D (larcv::VoxelSet &&vs, larcv::ImageMeta &&meta)
move ctor
const larcv::ImageMeta & meta () const
Access ImageMeta of specific projection.
void clear_data ()
Clear everything.
void meta (const larcv::ImageMeta &meta)
Meta setter.
InstanceID_t id () const
InstanceID_t getter.
void id (const InstanceID_t id)
InstanceID_t setter.
const std::vector< larcv::Voxel > & as_vector () const
Access as a raw vector.
const Voxel & find (VoxelID_t id) const
Returns a const reference to a voxel with specified id. if not present, invalid voxel is returned.
float sum () const
Sum of contained voxel values.
float mean () const
Mean of contained voxel values.
void add (const Voxel &vox)
Add a new voxel. If another voxel instance w/ same VoxelID exists, value is added.
void insert (const Voxel &vox)
Set a voxel. If another voxel instance w/ same VoxelID exists, value is set.
void emplace (Voxel &&vox, const bool add)
Emplace a new voxel. Same logic as VoxelSet::add but consumes removable reference.
void emplace (VoxelID_t id, float value, const bool add)
Emplace a new voxel from id & value.
VoxelSet & operator+= (float value)
VoxelSet & operator-= (float value)
VoxelSet & operator*= (float factor)
VoxelSet & operator/= (float factor)
Private Attributes
larcv::ImageMeta _meta
Detailed Description
Container of multiple (2D-projected) voxel set array.
Definition at line 25 of file Voxel2D.h.
Constructor & Destructor Documentation
larcv::SparseTensor2D::SparseTensor2D () inline
Default ctor.
Definition at line 28 of file Voxel2D.h.
 {}
virtual larcv::SparseTensor2D::~SparseTensor2D () inline virtual
Default dtor.
Definition at line 30 of file Voxel2D.h.
 {}
larcv::SparseTensor2D::SparseTensor2D (const larcv::VoxelSet & vs) inline
copy ctor w/ VoxelSet
Definition at line 32 of file Voxel2D.h.
       : VoxelSet(vs)
     {}
larcv::SparseTensor2D::SparseTensor2D (larcv::VoxelSet && vs, larcv::ImageMeta && meta)
move ctor
Definition at line 8 of file Voxel2D.cxx.
References meta().
         : VoxelSet(vs)
     { this->meta(meta); }
Member Function Documentation
void larcv::VoxelSet::add (const Voxel & vox) inherited
Add a new voxel. If another voxel instance w/ same VoxelID exists, value is added.
Definition at line 12 of file Voxel.cxx.
References larcv::VoxelSet::emplace().
Referenced by larcv::as_sparse_tensor2d(), and larcv::as_sparse_tensor3d().
   {
     Voxel copy(vox);
     emplace(std::move(copy),true);
   }
const std::vector<larcv::Voxel>& larcv::VoxelSet::as_vector () const inline inherited
Access as a raw vector.
Definition at line 106 of file Voxel.h.
References larcv::VoxelSet::_voxel_v.
Referenced by larcv::as_image2d(), meta(), and larcv::SparseTensor3D::meta().
 { return _voxel_v; }
void larcv::SparseTensor2D::clear_data () inline virtual
Clear everything.
Reimplemented from larcv::VoxelSet.
Definition at line 48 of file Voxel2D.h.
References _meta, and larcv::VoxelSet::clear_data().
 { VoxelSet::clear_data(); _meta = ImageMeta(); }
void larcv::VoxelSet::emplace (Voxel && vox, const bool add) inherited
Emplace a new voxel. Same logic as VoxelSet::add but consumes removable reference.
Definition at line 41 of file Voxel.cxx.
References larcv::VoxelSet::_voxel_v.
Referenced by larcv::VoxelSet::add(), larcv::as_tensor3d(), larcv::SparseTensor3D::emplace(), larcv::VoxelSet::emplace(), and larcv::VoxelSet::insert().
   {
     // In case it's empty or greater than the last one
     if (_voxel_v.empty() || _voxel_v.back() < vox) {
       _voxel_v.emplace_back(std::move(vox));
       return;
     }
     // In case it's smaller than the first one
     if (_voxel_v.front() > vox) {
       _voxel_v.emplace_back(std::move(vox));
       for (size_t idx = 0; (idx + 1) < _voxel_v.size(); ++idx) {
         auto& element1 = _voxel_v[ _voxel_v.size() - (idx + 1) ];
         auto& element2 = _voxel_v[ _voxel_v.size() - (idx + 2) ];
         std::swap( element1, element2 );
       }
       return;
     }
     // Else do log(N) search
     auto iter = std::lower_bound(_voxel_v.begin(), _voxel_v.end(), vox);
     // Cannot be the end
     if ( iter == _voxel_v.end() ) {
       std::cerr << "VoxelSet sorting logic error!" << std::endl;
       throw std::exception();
     }
     // If found, merge
     if ( vox.id() == (*iter).id() ) {
       if(add) (*iter) += vox.value();
       else (*iter).set(vox.id(),vox.value());
       return;
     }
     // Else insert @ appropriate place
     else {
       size_t target_ctr = _voxel_v.size() - (iter - _voxel_v.begin());
       _voxel_v.emplace_back(std::move(vox));
       for (size_t idx = 0; idx < target_ctr; ++idx) {
         auto& element1 = _voxel_v[ _voxel_v.size() - (idx + 1) ];
         auto& element2 = _voxel_v[ _voxel_v.size() - (idx + 2) ];
         std::swap( element1, element2 );
       }
     }
     return;
   }
void larcv::VoxelSet::emplace (VoxelID_t id, float value, const bool add) inline inherited
Emplace a new voxel from id & value.
Definition at line 126 of file Voxel.h.
References larcv::VoxelSet::emplace().
     { emplace(Voxel(id,value),add); }
const Voxel & larcv::VoxelSet::find (VoxelID_t id) const inherited
Returns a const reference to a voxel with specified id. if not present, invalid voxel is returned.
Definition at line 24 of file Voxel.cxx.
References larcv::VoxelSet::_voxel_v, larcv::VoxelSet::id(), and larcv::kINVALID_VOXEL().
   {
     if(_voxel_v.empty() ||
        id < _voxel_v.front().id() ||
        id > _voxel_v.back().id())
       return kINVALID_VOXEL;
     Voxel vox(id,0.);
     // Else do log(N) search
     auto iter = std::lower_bound(_voxel_v.begin(), _voxel_v.end(), vox);
     if( (*iter).id() == id ) return (*iter);
     else {
       //std::cout << "Returning invalid voxel since lower_bound had an id " << (*iter).id() << std::endl;
       return kINVALID_VOXEL;
     }
   }
InstanceID_t larcv::VoxelSet::id () const inline inherited
InstanceID_t getter.
Definition at line 104 of file Voxel.h.
References larcv::VoxelSet::_id.
Referenced by larcv::VoxelSet::find(), and larcv::VoxelSetArray::insert().
 { return _id; }
void larcv::VoxelSet::id (const InstanceID_t id) inline inherited
InstanceID_t setter.
Definition at line 129 of file Voxel.h.
References larcv::VoxelSet::_id, and larcv::VoxelSet::id().
Referenced by larcv::VoxelSet::id().
 { _id = id; }
void larcv::VoxelSet::insert (const Voxel & vox) inherited
Set a voxel. If another voxel instance w/ same VoxelID exists, value is set.
Definition at line 18 of file Voxel.cxx.
References larcv::VoxelSet::emplace().
   {
     Voxel copy(vox);
     emplace(std::move(copy),false);
   }
float larcv::VoxelSet::mean () const inline inherited
Mean of contained voxel values.
Definition at line 112 of file Voxel.h.
References larcv::VoxelSet::_voxel_v, and larcv::VoxelSet::sum().
 { return (_voxel_v.empty() ? 0. : sum() / (float)(_voxel_v.size())); }
const larcv::ImageMeta& larcv::SparseTensor2D::meta () const inline
Access ImageMeta of specific projection.
Definition at line 42 of file Voxel2D.h.
References _meta.
Referenced by meta(), larcv::EventSparseTensor2D::set(), and SparseTensor2D().
 { return _meta; }
void larcv::SparseTensor2D::meta (const larcv::ImageMeta & meta)
Meta setter.
Definition at line 12 of file Voxel2D.cxx.
References _meta, larcv::VoxelSet::as_vector(), meta(), and larcv::ImageMeta::size().
     {
         auto const max_id = meta.size();
         for (auto const& vox : this->as_vector()) {
             if (vox.id() < max_id) continue;
             std::cerr << "VoxelSet contains ID " << vox.id()
                       << " which cannot exists in ImageMeta with size " << max_id
                       << std::endl;
             throw std::exception();
         }
         _meta = meta;
     }
VoxelSet& larcv::VoxelSet::operator*= (float factor) inline inherited
Definition at line 138 of file Voxel.h.
References larcv::VoxelSet::_voxel_v.
     { for(auto& vox : _voxel_v) vox *= factor; return (*this); }
VoxelSet& larcv::VoxelSet::operator+= (float value) inline inherited
Definition at line 134 of file Voxel.h.
References larcv::VoxelSet::_voxel_v.
     { for(auto& vox : _voxel_v) vox += value; return (*this); }
VoxelSet& larcv::VoxelSet::operator-= (float value) inline inherited
Definition at line 136 of file Voxel.h.
References larcv::VoxelSet::_voxel_v.
     { for(auto& vox : _voxel_v) vox -= value; return (*this); }
VoxelSet& larcv::VoxelSet::operator/= (float factor) inline inherited
Definition at line 140 of file Voxel.h.
References larcv::VoxelSet::_voxel_v.
     { for(auto& vox : _voxel_v) vox /= factor; return (*this); }
float larcv::VoxelSet::sum () const inline inherited
Sum of contained voxel values.
Definition at line 110 of file Voxel.h.
References larcv::VoxelSet::_voxel_v.
Referenced by larcv::VoxelSet::mean().
 { float res=0.; for(auto const& vox : _voxel_v) res+=vox.value(); return res;}
Member Data Documentation
larcv::ImageMeta larcv::SparseTensor2D::_meta private
Definition at line 53 of file Voxel2D.h.
Referenced by clear_data(), and meta().
The documentation for this class was generated from the following files:
Voxel2D.h
Voxel2D.cxx