LArCV: larcv::PyImageStitcher Class Reference
larcv::PyImageStitcher Class Reference
#include <PyImageStitcher.h>
Public Member Functions
PyImageStitcher (const std::string name="PyImageStitcher")
Default constructor.
~PyImageStitcher ()
Default destructor.
void configure (const PSet &)
Called first with the argument passing the configuration parameters.
void initialize ()
Called after configure, this is where you should initialize variables to be stored in an output analysis file.
bool process (IOManager &mgr)
Called per-event, this is where you should implement your per-event action/analysis.
void finalize ()
Called after event loop is over. This is where you can store your histograms etc. to an output analysis file.
void append_ndarray (PyObject *img, size_t ch)
void append_ndarray_meta (PyObject *img, const ImageMeta &meta, size_t ch)
void set_id (size_t run, size_t subrun, size_t event)
void set_producer_name (std::string name)
const std::string & producer_name () const
bool has_ana_file () const
Returns true/false if there is an analysis ROOT file to store the output objects.
TFile & ana_file ()
Returns analysis ROOT file if exits (else throws an exception)
virtual bool is (const std::string question) const
Only for experts: allows a loose grouping for a set of ProcessBase inherit classes via true/false return to a "question".
bool event_creator () const
Only for experts: larcv::ProcessDriver to see if this module can create a new event or not.
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
std::vector< std::vector
< larcv::Image2D > > _image_vv
std::string _producer_name
size_t _run
size_t _subrun
size_t _event
Detailed Description
Definition at line 28 of file PyImageStitcher.h.
Constructor & Destructor Documentation
larcv::PyImageStitcher::PyImageStitcher (const std::string name = "PyImageStitcher")
Default constructor.
Definition at line 11 of file PyImageStitcher.cxx.
     : ProcessBase(name)
   {}
larcv::PyImageStitcher::~PyImageStitcher () inline
Default destructor.
Definition at line 36 of file PyImageStitcher.h.
 {}
Member Function Documentation
TFile& larcv::ProcessBase::ana_file () inline inherited
Returns analysis ROOT file if exits (else throws an exception)
Definition at line 61 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
void larcv::PyImageStitcher::append_ndarray (PyObject * img, size_t ch)
Definition at line 24 of file PyImageStitcher.cxx.
References _image_vv, larcv::as_image2d(), and LARCV_INFO.
   {
     LARCV_INFO() << "Appending an image (ch =" << _image_vv.size() << ")" << std::endl;
     if(_image_vv.size() <= ch) _image_vv.resize(ch+1);
     _image_vv[ch].emplace_back(std::move(as_image2d(img)));
   }
void larcv::PyImageStitcher::append_ndarray_meta (PyObject * img, const ImageMeta & meta, size_t ch)
Definition at line 31 of file PyImageStitcher.cxx.
References _image_vv, larcv::as_image2d_meta(), and LARCV_INFO.
   {
     LARCV_INFO() << "Appending an image (ch =" << ch << ")" << std::endl;
     if(_image_vv.size() <= ch) _image_vv.resize(ch+1);
     _image_vv[ch].emplace_back(std::move(as_image2d_meta(img,meta)));
   }
void larcv::PyImageStitcher::configure (const PSet &) virtual
Called first with the argument passing the configuration parameters.
Implements larcv::ProcessBase.
Definition at line 15 of file PyImageStitcher.cxx.
References _producer_name, and larcv::PSet::get().
   { _producer_name = cfg.get<std::string>("ImageProducer"); }
bool larcv::ProcessBase::event_creator () const inline inherited
Only for experts: larcv::ProcessDriver to see if this module can create a new event or not.
Definition at line 70 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
     { return _event_creator; }
void larcv::PyImageStitcher::finalize () virtual
Called after event loop is over. This is where you can store your histograms etc. to an output analysis file.
Implements larcv::ProcessBase.
Definition at line 89 of file PyImageStitcher.cxx.
   {}
bool larcv::ProcessBase::has_ana_file () const inline inherited
Returns true/false if there is an analysis ROOT file to store the output objects.
Definition at line 58 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
     { return _fout != nullptr; }
void larcv::PyImageStitcher::initialize () virtual
Called after configure, this is where you should initialize variables to be stored in an output analysis file.
Implements larcv::ProcessBase.
Definition at line 18 of file PyImageStitcher.cxx.
References _event, _image_vv, _run, _subrun, and larcv::kINVALID_SIZE.
   {
     _run = _subrun = _event = kINVALID_SIZE;
     _image_vv.clear();
   }
bool larcv::ProcessBase::is (const std::string question) const virtual inherited
Only for experts: allows a loose grouping for a set of ProcessBase inherit classes via true/false return to a "question".
Definition at line 17 of file ProcessBase.cxx.
   { return !(question.empty()); }
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::ProcessDriver::configure(), and larcv::larcv_base::name().
     { return *_logger; }
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::ProcessFactory::add_factory(), larcv::ProcessDriver::configure(), larcv::ProcessFactory::create(), larcv::ProcessDriver::finalize(), larcv::IOManager::initialize(), larcv::IOManager::IOManager(), larcv::IOManager::set_out_file(), and set_producer_name().
     { return logger().name(); }
bool larcv::PyImageStitcher::process (IOManager & mgr) virtual
Called per-event, this is where you should implement your per-event action/analysis.
Implements larcv::ProcessBase.
Definition at line 38 of file PyImageStitcher.cxx.
References _event, _image_vv, _producer_name, _run, _subrun, larcv::IOManager::event_id(), larcv::IOManager::get_data(), larcv::ImageMeta::inclusive(), larcv::kINVALID_SIZE, larcv::Image2D::kOverWrite, LARCV_CRITICAL, LARCV_WARNING, larcv::Image2D::overlay(), larcv::Image2D::paint(), and larcv::IOManager::set_id().
   {
     auto image_v = (EventImage2D*)(mgr.get_data("image2d",_producer_name));
     if(!image_v) {
       LARCV_CRITICAL() << "Could not create Image2D with name " << _producer_name << std::endl;
       throw larbys();
     }
     if(image_v->image2d_array().size()) {
       LARCV_CRITICAL() << "Image2D by " << _producer_name << " is not empty!" << std::endl;
       throw larbys();
     }
     auto const& id = mgr.event_id();
     if(id.run() != kINVALID_SIZE || id.subrun() != kINVALID_SIZE || id.event() != kINVALID_SIZE) {
       if(id.run()    != _run    ) LARCV_WARNING() << "Overwriting run    number: " << id.run()    << " => " << _run    << std::endl;
       if(id.subrun() != _subrun ) LARCV_WARNING() << "Overwriting subrun number: " << id.subrun() << " => " << _subrun << std::endl;
       if(id.event()  != _event  ) LARCV_WARNING() << "Overwriting event  number: " << id.event()  << " => " << _event  << std::endl;
     }
     mgr.set_id(_run,_subrun,_event);
     _run = _subrun = _event = kINVALID_SIZE;
     std::vector<larcv::Image2D> out_img_v;
     for(size_t ch=0; ch<_image_vv.size(); ++ch) {
       if(_image_vv[ch].empty()) {
     out_img_v.push_back(Image2D());
     continue;
       }
       ImageMeta meta_combined = _image_vv[ch].front().meta();
       for(auto const& img : _image_vv[ch])
     meta_combined = meta_combined.inclusive(img.meta());
       Image2D out_img(meta_combined);
       out_img.paint(0.);
       for(auto const& img : _image_vv[ch])
     out_img.overlay(img,Image2D::kOverWrite);
       out_img_v.emplace_back(std::move(out_img));
     }
     image_v->emplace(std::move(out_img_v));
     _image_vv.clear();
     return true;
   }
const std::string& larcv::PyImageStitcher::producer_name () const inline
Definition at line 56 of file PyImageStitcher.h.
References _producer_name.
 { return _producer_name; }
void larcv::PyImageStitcher::set_id (size_t run, size_t subrun, size_t event) inline
Definition at line 50 of file PyImageStitcher.h.
References _event, _run, and _subrun.
     { _run = run; _subrun = subrun; _event = event; }
void larcv::PyImageStitcher::set_producer_name (std::string name) inline
Definition at line 53 of file PyImageStitcher.h.
References _producer_name, and larcv::larcv_base::name().
     { _producer_name = name; }
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::ProcessDriver::configure(), and larcv::IOManager::configure().
     { _logger->set(level); }
Member Data Documentation
size_t larcv::PyImageStitcher::_event private
Definition at line 64 of file PyImageStitcher.h.
Referenced by initialize(), process(), and set_id().
std::vector< std::vector<larcv::Image2D> > larcv::PyImageStitcher::_image_vv private
Definition at line 60 of file PyImageStitcher.h.
Referenced by append_ndarray(), append_ndarray_meta(), initialize(), and process().
std::string larcv::PyImageStitcher::_producer_name private
Definition at line 62 of file PyImageStitcher.h.
Referenced by configure(), process(), producer_name(), and set_producer_name().
size_t larcv::PyImageStitcher::_run private
Definition at line 64 of file PyImageStitcher.h.
Referenced by initialize(), process(), and set_id().
size_t larcv::PyImageStitcher::_subrun private
Definition at line 64 of file PyImageStitcher.h.
Referenced by initialize(), process(), and set_id().
The documentation for this class was generated from the following files:
PyImageStitcher.h
PyImageStitcher.cxx