LArCV: larcv::ProcessFactory Class Reference
larcv::ProcessFactory Class Reference
Factory class for instantiating process instance This factory class can instantiate a specified process instance w/ provided instance name.
#include <ProcessFactory.h>
Public Member Functions
ProcessFactory ()
Default ctor, shouldn't be used.
~ProcessFactory ()
Default dtor.
void add_factory (const std::string name, larcv::ProcessFactoryBase *factory)
Factory registration method (should be called by global factory instance in algorithm header)
ProcessBase * create (const std::string name, const std::string instance_name)
Factory creation method (should be called by clients, possibly you!)
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Static Public Member Functions
static ProcessFactory & get ()
Static sharable instance getter.
Private Attributes
std::map< std::string,
larcv::ProcessFactoryBase * > _factory_map
Static factory container.
Static Private Attributes
static ProcessFactory * _me = nullptr
Static self.
Detailed Description
Factory class for instantiating process instance This factory class can instantiate a specified process instance w/ provided instance name.
The actual factory core (to which each algorithm must register creation factory instance) is
a static std::map. Use static method to get a static instance (larcv::ProcessFactory::get)
to access a factory.
Definition at line 48 of file ProcessFactory.h.
Constructor & Destructor Documentation
larcv::ProcessFactory::ProcessFactory () inline
Default ctor, shouldn't be used.
Definition at line 52 of file ProcessFactory.h.
Referenced by get().
                      : larcv_base("ProcessFactory")
     {}
larcv::ProcessFactory::~ProcessFactory () inline
Default dtor.
Definition at line 55 of file ProcessFactory.h.
References _factory_map.
 {_factory_map.clear();}
Member Function Documentation
void larcv::ProcessFactory::add_factory (const std::string name, larcv::ProcessFactoryBase * factory) inline
Factory registration method (should be called by global factory instance in algorithm header)
Definition at line 65 of file ProcessFactory.h.
References _factory_map, and larcv::larcv_base::name().
Referenced by larcv::PyCluster3DMakerProcessFactory::PyCluster3DMakerProcessFactory(), larcv::PyImageMakerProcessFactory::PyImageMakerProcessFactory(), larcv::PyImageStitcherProcessFactory::PyImageStitcherProcessFactory(), and larcv::PyTensor3DMakerProcessFactory::PyTensor3DMakerProcessFactory().
     { _factory_map[name] = factory; }
ProcessBase* larcv::ProcessFactory::create (const std::string name, const std::string instance_name) inline
Factory creation method (should be called by clients, possibly you!)
Definition at line 68 of file ProcessFactory.h.
References _factory_map, LARCV_ERROR, and larcv::larcv_base::name().
Referenced by larcv::ProcessDriver::configure().
{
       auto iter = _factory_map.find(name);
       if(iter == _factory_map.end() || !((*iter).second)) {
     LARCV_ERROR() << "Found no registered class " << name << std::endl;
     return nullptr;
       }
       auto ptr = (*iter).second->create(instance_name);
       ptr->_typename = name;
       return ptr;
     }
static ProcessFactory& larcv::ProcessFactory::get () inline static
Static sharable instance getter.
Definition at line 57 of file ProcessFactory.h.
References __procfactory_mtx, _me, and ProcessFactory().
Referenced by larcv::ProcessDriver::configure(), larcv::PyCluster3DMakerProcessFactory::PyCluster3DMakerProcessFactory(), larcv::PyImageMakerProcessFactory::PyImageMakerProcessFactory(), larcv::PyImageStitcherProcessFactory::PyImageStitcherProcessFactory(), and larcv::PyTensor3DMakerProcessFactory::PyTensor3DMakerProcessFactory().
     {
       __procfactory_mtx.lock();
       if(!_me) _me = new ProcessFactory;
       __procfactory_mtx.unlock();
       return *_me;
     }
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::ProcessDriver::configure(), and larcv::larcv_base::name().
     { return *_logger; }
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by add_factory(), larcv::ProcessDriver::configure(), create(), larcv::ProcessDriver::finalize(), larcv::IOManager::initialize(), larcv::IOManager::IOManager(), larcv::IOManager::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::ProcessDriver::configure(), and larcv::IOManager::configure().
     { _logger->set(level); }
Member Data Documentation
std::map<std::string,larcv::ProcessFactoryBase*> larcv::ProcessFactory::_factory_map private
Static factory container.
Definition at line 81 of file ProcessFactory.h.
Referenced by add_factory(), create(), and ~ProcessFactory().
larcv::ProcessFactory * larcv::ProcessFactory::_me = nullptr static private
Static self.
Definition at line 83 of file ProcessFactory.h.
Referenced by get().
The documentation for this class was generated from the following files:
ProcessFactory.h
ProcessFactory.cxx