LArCV: larcv::VoxelSet Class Reference
larcv::VoxelSet Class Reference
Container of multiple voxels consisting of ordered sparse vector and meta data.
#include <Voxel.h>
Public Member Functions
VoxelSet ()
Default ctor.
virtual ~VoxelSet ()
Default dtor.
InstanceID_t id () const
InstanceID_t getter.
const std::vector< larcv::Voxel > & as_vector () const
Access as a raw vector.
const Voxel & find (VoxelID_t id) const
Returns a const reference to a voxel with specified id. if not present, invalid voxel is returned.
float sum () const
Sum of contained voxel values.
float mean () const
Mean of contained voxel values.
virtual void clear_data ()
Clear everything.
void add (const Voxel &vox)
Add a new voxel. If another voxel instance w/ same VoxelID exists, value is added.
void insert (const Voxel &vox)
Set a voxel. If another voxel instance w/ same VoxelID exists, value is set.
void emplace (Voxel &&vox, const bool add)
Emplace a new voxel. Same logic as VoxelSet::add but consumes removable reference.
void emplace (VoxelID_t id, float value, const bool add)
Emplace a new voxel from id & value.
void id (const InstanceID_t id)
InstanceID_t setter.
VoxelSet & operator+= (float value)
VoxelSet & operator-= (float value)
VoxelSet & operator*= (float factor)
VoxelSet & operator/= (float factor)
Private Attributes
InstanceID_t _id
Instance ID.
std::vector< larcv::Voxel > _voxel_v
Ordered sparse vector of voxels.
Detailed Description
Container of multiple voxels consisting of ordered sparse vector and meta data.
Definition at line 93 of file Voxel.h.
Constructor & Destructor Documentation
larcv::VoxelSet::VoxelSet () inline
Default ctor.
Definition at line 96 of file Voxel.h.
 {}
virtual larcv::VoxelSet::~VoxelSet () inline virtual
Default dtor.
Definition at line 98 of file Voxel.h.
 {}
Member Function Documentation
void larcv::VoxelSet::add (const Voxel & vox)
Add a new voxel. If another voxel instance w/ same VoxelID exists, value is added.
Definition at line 12 of file Voxel.cxx.
References emplace().
Referenced by larcv::as_sparse_tensor2d(), and larcv::as_sparse_tensor3d().
   {
     Voxel copy(vox);
     emplace(std::move(copy),true);
   }
const std::vector<larcv::Voxel>& larcv::VoxelSet::as_vector () const inline
Access as a raw vector.
Definition at line 106 of file Voxel.h.
References _voxel_v.
Referenced by larcv::as_image2d(), larcv::SparseTensor2D::meta(), and larcv::SparseTensor3D::meta().
 { return _voxel_v; }
virtual void larcv::VoxelSet::clear_data () inline virtual
Clear everything.
Reimplemented in larcv::SparseTensor3D, and larcv::SparseTensor2D.
Definition at line 118 of file Voxel.h.
References _voxel_v.
Referenced by larcv::SparseTensor2D::clear_data(), larcv::SparseTensor3D::clear_data(), larcv::PyTensor3DMaker::initialize(), and larcv::PyTensor3DMaker::process().
 { _voxel_v.clear(); }
void larcv::VoxelSet::emplace (Voxel && vox, const bool add)
Emplace a new voxel. Same logic as VoxelSet::add but consumes removable reference.
Definition at line 41 of file Voxel.cxx.
References _voxel_v.
Referenced by add(), larcv::as_tensor3d(), larcv::SparseTensor3D::emplace(), emplace(), and insert().
   {
     // In case it's empty or greater than the last one
     if (_voxel_v.empty() || _voxel_v.back() < vox) {
       _voxel_v.emplace_back(std::move(vox));
       return;
     }
     // In case it's smaller than the first one
     if (_voxel_v.front() > vox) {
       _voxel_v.emplace_back(std::move(vox));
       for (size_t idx = 0; (idx + 1) < _voxel_v.size(); ++idx) {
         auto& element1 = _voxel_v[ _voxel_v.size() - (idx + 1) ];
         auto& element2 = _voxel_v[ _voxel_v.size() - (idx + 2) ];
         std::swap( element1, element2 );
       }
       return;
     }
     // Else do log(N) search
     auto iter = std::lower_bound(_voxel_v.begin(), _voxel_v.end(), vox);
     // Cannot be the end
     if ( iter == _voxel_v.end() ) {
       std::cerr << "VoxelSet sorting logic error!" << std::endl;
       throw std::exception();
     }
     // If found, merge
     if ( vox.id() == (*iter).id() ) {
       if(add) (*iter) += vox.value();
       else (*iter).set(vox.id(),vox.value());
       return;
     }
     // Else insert @ appropriate place
     else {
       size_t target_ctr = _voxel_v.size() - (iter - _voxel_v.begin());
       _voxel_v.emplace_back(std::move(vox));
       for (size_t idx = 0; idx < target_ctr; ++idx) {
         auto& element1 = _voxel_v[ _voxel_v.size() - (idx + 1) ];
         auto& element2 = _voxel_v[ _voxel_v.size() - (idx + 2) ];
         std::swap( element1, element2 );
       }
     }
     return;
   }
void larcv::VoxelSet::emplace (VoxelID_t id, float value, const bool add) inline
Emplace a new voxel from id & value.
Definition at line 126 of file Voxel.h.
References emplace().
     { emplace(Voxel(id,value),add); }
const Voxel & larcv::VoxelSet::find (VoxelID_t id) const
Returns a const reference to a voxel with specified id. if not present, invalid voxel is returned.
Definition at line 24 of file Voxel.cxx.
References _voxel_v, id(), and larcv::kINVALID_VOXEL().
   {
     if(_voxel_v.empty() ||
        id < _voxel_v.front().id() ||
        id > _voxel_v.back().id())
       return kINVALID_VOXEL;
     Voxel vox(id,0.);
     // Else do log(N) search
     auto iter = std::lower_bound(_voxel_v.begin(), _voxel_v.end(), vox);
     if( (*iter).id() == id ) return (*iter);
     else {
       //std::cout << "Returning invalid voxel since lower_bound had an id " << (*iter).id() << std::endl;
       return kINVALID_VOXEL;
     }
   }
InstanceID_t larcv::VoxelSet::id () const inline
InstanceID_t getter.
Definition at line 104 of file Voxel.h.
References _id.
Referenced by find(), and larcv::VoxelSetArray::insert().
 { return _id; }
void larcv::VoxelSet::id (const InstanceID_t id) inline
InstanceID_t setter.
Definition at line 129 of file Voxel.h.
References _id, and id().
Referenced by id().
 { _id = id; }
void larcv::VoxelSet::insert (const Voxel & vox)
Set a voxel. If another voxel instance w/ same VoxelID exists, value is set.
Definition at line 18 of file Voxel.cxx.
References emplace().
   {
     Voxel copy(vox);
     emplace(std::move(copy),false);
   }
float larcv::VoxelSet::mean () const inline
Mean of contained voxel values.
Definition at line 112 of file Voxel.h.
References _voxel_v, and sum().
 { return (_voxel_v.empty() ? 0. : sum() / (float)(_voxel_v.size())); }
VoxelSet& larcv::VoxelSet::operator*= (float factor) inline
Definition at line 138 of file Voxel.h.
References _voxel_v.
     { for(auto& vox : _voxel_v) vox *= factor; return (*this); }
VoxelSet& larcv::VoxelSet::operator+= (float value) inline
Definition at line 134 of file Voxel.h.
References _voxel_v.
     { for(auto& vox : _voxel_v) vox += value; return (*this); }
VoxelSet& larcv::VoxelSet::operator-= (float value) inline
Definition at line 136 of file Voxel.h.
References _voxel_v.
     { for(auto& vox : _voxel_v) vox -= value; return (*this); }
VoxelSet& larcv::VoxelSet::operator/= (float factor) inline
Definition at line 140 of file Voxel.h.
References _voxel_v.
     { for(auto& vox : _voxel_v) vox /= factor; return (*this); }
float larcv::VoxelSet::sum () const inline
Sum of contained voxel values.
Definition at line 110 of file Voxel.h.
References _voxel_v.
Referenced by mean().
 { float res=0.; for(auto const& vox : _voxel_v) res+=vox.value(); return res;}
Member Data Documentation
InstanceID_t larcv::VoxelSet::_id private
Instance ID.
Definition at line 145 of file Voxel.h.
Referenced by id().
std::vector<larcv::Voxel> larcv::VoxelSet::_voxel_v private
Ordered sparse vector of voxels.
Definition at line 147 of file Voxel.h.
Referenced by as_vector(), clear_data(), emplace(), find(), mean(), operator*=(), operator+=(), operator-=(), operator/=(), and sum().
The documentation for this class was generated from the following files:
Voxel.h
Voxel.cxx