LArCV: larcv::EventClusterVoxel3D Class Reference
larcv::EventClusterVoxel3D Class Reference
Event-wise class to store a collection of VoxelSet (cluster) collection.
#include <EventVoxel3D.h>
Public Member Functions
EventClusterVoxel3D ()
Default constructor.
virtual ~EventClusterVoxel3D ()
Default destructor.
void clear ()
EventBase::clear() override.
const std::string & producer () const
Producer name getter.
size_t run () const
Run number getter.
size_t subrun () const
SubRun number getter.
size_t event () const
Event number getter.
bool valid () const
Make sure run/subrun/event ID is set.
bool operator== (const EventBase &rhs) const
Comparison opearator for run/subrun/event id.
bool operator!= (const EventBase &rhs) const
Comparison opearator for run/subrun/event id.
bool operator< (const EventBase &rhs) const
Comparison opearator for run/subrun/event id (for sorted container like std::set and/or std::map)
std::string event_key () const
Formatted string key getter (a string key consists of 0-padded run, subrun, and event id)
void set_id (const size_t run, const size_t subrun, const size_t event)
Setting the id.
const larcv::Voxel3DMeta & meta () const
Access Voxel3DMeta of specific projection.
void meta (const larcv::Voxel3DMeta &meta)
Meta setter.
void clear_data ()
Clear everything.
void set (VoxelSetArray &&vsa, Voxel3DMeta &meta)
set VoxelSetArray
void emplace (VoxelSetArray &&vsa, Voxel3DMeta &meta)
emplace VoxelSetArray
void emplace (std::vector< larcv::VoxelSet > &&voxel_vv)
Move an arrray of VoxelSet. Each element's InstanceID_t gets updated.
void emplace (larcv::VoxelSet &&voxel_v)
Move a VoxelSet into a collection. The InstanceID_t is respected.
size_t size () const
Get # of VoxelSet.
const larcv::VoxelSet & voxel_set (InstanceID_t id) const
Access specific VoxelSet.
const std::vector
< larcv::VoxelSet > & as_vector () const
Access all VoxelSet as a vector.
void resize (const size_t num)
Resize voxel array.
larcv::VoxelSet & writeable_voxel_set (const InstanceID_t id)
Access non-const reference of a specific VoxelSet.
void insert (const std::vector< larcv::VoxelSet > &voxel_vv)
Set an array of VoxelSet. Each element's InstanceID_t gets updated.
void insert (const larcv::VoxelSet &voxel_v)
Set a VoxelSet into a collection. The InstanceID_t is respected.
void move (larcv::VoxelSetArray &&orig)
Mover.
Detailed Description
Event-wise class to store a collection of VoxelSet (cluster) collection.
A concrete factory class for larcv::EventClusterVoxel3D.
Definition at line 27 of file EventVoxel3D.h.
Constructor & Destructor Documentation
larcv::EventClusterVoxel3D::EventClusterVoxel3D () inline
Default constructor.
Definition at line 33 of file EventVoxel3D.h.
 {}
virtual larcv::EventClusterVoxel3D::~EventClusterVoxel3D () inline virtual
Default destructor.
Definition at line 36 of file EventVoxel3D.h.
 {}
Member Function Documentation
const std::vector<larcv::VoxelSet>& larcv::VoxelSetArray::as_vector () const inline inherited
Access all VoxelSet as a vector.
Definition at line 169 of file Voxel.h.
References larcv::VoxelSetArray::_voxel_vv.
Referenced by larcv::as_image2d(), larcv::as_sparse_tensor2d(), larcv::as_sparse_tensor3d(), larcv::ClusterPixel2D::meta(), and larcv::ClusterVoxel3D::meta().
     { return _voxel_vv; }
void larcv::EventClusterVoxel3D::clear () inline virtual
EventBase::clear() override.
Reimplemented from larcv::EventBase.
Definition at line 39 of file EventVoxel3D.h.
References larcv::EventBase::clear(), and larcv::ClusterVoxel3D::clear_data().
 {EventBase::clear(); ClusterVoxel3D::clear_data();}
void larcv::ClusterVoxel3D::clear_data () inline inherited
Clear everything.
Definition at line 83 of file Voxel3D.h.
References larcv::ClusterVoxel3D::_meta, and larcv::VoxelSetArray::clear_data().
Referenced by clear().
 { VoxelSetArray::clear_data(); _meta = Voxel3DMeta(); }
void larcv::ClusterVoxel3D::emplace (VoxelSetArray && vsa, Voxel3DMeta & meta) inline inherited
emplace VoxelSetArray
Definition at line 88 of file Voxel3D.h.
References larcv::ClusterVoxel3D::meta().
Referenced by larcv::PyCluster3DMaker::process().
     { *((VoxelSetArray*)this) = vsa; this->meta(meta); }
void larcv::VoxelSetArray::emplace (std::vector< larcv::VoxelSet > && voxel_vv) inherited
Move an arrray of VoxelSet. Each element's InstanceID_t gets updated.
Definition at line 100 of file Voxel.cxx.
References larcv::VoxelSetArray::_voxel_vv.
Referenced by larcv::PyCluster3DMaker::append_ndarray().
   {
     _voxel_vv = std::move(voxel_vv);
     for(size_t id=0; id<_voxel_vv.size(); ++id)
       _voxel_vv[id].id(id);
   }
void larcv::VoxelSetArray::emplace (larcv::VoxelSet && voxel_v) inherited
Move a VoxelSet into a collection. The InstanceID_t is respected.
Definition at line 114 of file Voxel.cxx.
References larcv::VoxelSetArray::_voxel_vv.
   {
     if(voxel_v.id() >= _voxel_vv.size()) {
       size_t orig_size = _voxel_vv.size();
       _voxel_vv.resize(voxel_v.id()+1);
       for(size_t id=orig_size; id<_voxel_vv.size(); ++id)
         _voxel_vv[id].id(id);
     }
     _voxel_vv[voxel_v.id()] = std::move(voxel_v);
   }
size_t larcv::EventBase::event () const inline inherited
Event number getter.
Definition at line 56 of file EventBase.h.
References larcv::EventBase::_event.
Referenced by larcv::IOManager::clear_entry(), larcv::IOManager::get_data(), larcv::EventBase::operator<(), larcv::EventBase::operator==(), larcv::IOManager::register_producer(), larcv::EventBase::set_id(), and larcv::IOManager::set_id().
 { return _event;  }
std::string larcv::EventBase::event_key () const inherited
Formatted string key getter (a string key consists of 0-padded run, subrun, and event id)
Definition at line 13 of file EventBase.cxx.
References larcv::EventBase::_event, larcv::EventBase::_run, and larcv::EventBase::_subrun.
Referenced by larcv::IOManager::set_id().
   {
     std::stringstream ss;
     ss << std::setw( 7 ) << std::setfill( '0' ) << _run << "_"
        << std::setw( 5 ) << std::setfill( '0' ) << _subrun << "_"
        << std::setw( 6 ) << std::setfill( '0' ) << _event;
     return ss.str();
   }
void larcv::VoxelSetArray::insert (const std::vector< larcv::VoxelSet > & voxel_vv) inline inherited
Set an array of VoxelSet. Each element's InstanceID_t gets updated.
Definition at line 107 of file Voxel.cxx.
References larcv::VoxelSetArray::_voxel_vv.
   {
     _voxel_vv = voxel_vv;
     for(size_t id=0; id<_voxel_vv.size(); ++id)
       _voxel_vv[id].id(id);
   }
void larcv::VoxelSetArray::insert (const larcv::VoxelSet & voxel_v) inherited
Set a VoxelSet into a collection. The InstanceID_t is respected.
Definition at line 125 of file Voxel.cxx.
References larcv::VoxelSetArray::_voxel_vv, and larcv::VoxelSet::id().
   {
     if(voxel_v.id() >= _voxel_vv.size()) {
       size_t orig_size = _voxel_vv.size();
       _voxel_vv.resize(voxel_v.id()+1);
       for(size_t id=orig_size; id<_voxel_vv.size(); ++id)
         _voxel_vv[id].id(id);
     }
     _voxel_vv[voxel_v.id()] = voxel_v;
   }
const larcv::Voxel3DMeta& larcv::ClusterVoxel3D::meta () const inline inherited
Access Voxel3DMeta of specific projection.
Definition at line 77 of file Voxel3D.h.
References larcv::ClusterVoxel3D::_meta.
Referenced by larcv::as_sparse_tensor3d(), larcv::ClusterVoxel3D::emplace(), larcv::ClusterVoxel3D::meta(), and larcv::ClusterVoxel3D::set().
 { return _meta; }
void larcv::ClusterVoxel3D::meta (const larcv::Voxel3DMeta & meta) inherited
Meta setter.
Definition at line 31 of file Voxel3D.cxx.
References larcv::ClusterVoxel3D::_meta, larcv::VoxelSetArray::as_vector(), larcv::Voxel3DMeta::id(), larcv::ClusterVoxel3D::meta(), and larcv::Voxel3DMeta::size().
     {
         for (auto const& vs : this->as_vector()) {
             for (auto const& vox : vs.as_vector()) {
                 if (vox.id() < meta.size()) continue;
                 std::cerr << "VoxelSet contains ID " << vox.id()
                           << " which cannot exists in Voxel3DMeta with size " << meta.size()
                           << std::endl;
                 throw std::exception();
             }
         }
         _meta = meta;
     }
void larcv::VoxelSetArray::move (larcv::VoxelSetArray && orig) inline inherited
Mover.
Definition at line 191 of file Voxel.h.
References larcv::VoxelSetArray::_voxel_vv.
     { _voxel_vv = std::move(orig._voxel_vv); }
bool larcv::EventBase::operator!= (const EventBase & rhs) const inline inherited
Comparison opearator for run/subrun/event id.
Definition at line 64 of file EventBase.h.
     { return !((*this) == rhs); }
bool larcv::EventBase::operator< (const EventBase & rhs) const inline inherited
Comparison opearator for run/subrun/event id (for sorted container like std::set and/or std::map)
Definition at line 67 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, larcv::EventBase::event(), larcv::EventBase::run(), and larcv::EventBase::subrun().
     {
       if(_run < rhs.run()) return true;
       if(_run > rhs.run()) return false;
       if(_subrun < rhs.subrun()) return true;
       if(_subrun > rhs.subrun()) return false;
       if(_event < rhs.event()) return true;
       if(_event > rhs.event()) return false;
       return false;
     }
bool larcv::EventBase::operator== (const EventBase & rhs) const inline inherited
Comparison opearator for run/subrun/event id.
Definition at line 61 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, larcv::EventBase::event(), larcv::EventBase::run(), and larcv::EventBase::subrun().
     { return (_run == rhs.run() && _subrun == rhs.subrun() && _event == rhs.event()); }
const std::string& larcv::EventBase::producer () const inline inherited
Producer name getter.
Definition at line 50 of file EventBase.h.
References larcv::EventBase::_producer.
 { return _producer; }
void larcv::VoxelSetArray::resize (const size_t num) inline inherited
Resize voxel array.
Definition at line 178 of file Voxel.h.
References larcv::VoxelSetArray::_voxel_vv.
     { _voxel_vv.resize(num); for(size_t i=0; i<num; ++i) _voxel_vv[i].id(i); }
size_t larcv::EventBase::run () const inline inherited
Run number getter.
Definition at line 52 of file EventBase.h.
References larcv::EventBase::_run.
Referenced by larcv::IOManager::clear_entry(), larcv::IOManager::get_data(), larcv::EventBase::operator<(), larcv::EventBase::operator==(), larcv::IOManager::register_producer(), larcv::EventBase::set_id(), and larcv::IOManager::set_id().
 { return _run;    }
void larcv::ClusterVoxel3D::set (VoxelSetArray && vsa, Voxel3DMeta & meta) inline inherited
set VoxelSetArray
Definition at line 85 of file Voxel3D.h.
References larcv::ClusterVoxel3D::meta().
     { *((VoxelSetArray*)this) = std::move(vsa); this->meta(meta); }
void larcv::EventBase::set_id (const size_t run, const size_t subrun, const size_t event) inline inherited
Setting the id.
Definition at line 82 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, larcv::EventBase::event(), larcv::EventBase::run(), and larcv::EventBase::subrun().
Referenced by larcv::IOManager::get_data().
     { _run = run; _subrun = subrun; _event = event; }
size_t larcv::VoxelSetArray::size () const inline inherited
Get # of VoxelSet.
Definition at line 165 of file Voxel.h.
References larcv::VoxelSetArray::_voxel_vv.
Referenced by larcv::PyCluster3DMaker::append_ndarray().
 { return _voxel_vv.size(); }
size_t larcv::EventBase::subrun () const inline inherited
SubRun number getter.
Definition at line 54 of file EventBase.h.
References larcv::EventBase::_subrun.
Referenced by larcv::IOManager::clear_entry(), larcv::IOManager::get_data(), larcv::EventBase::operator<(), larcv::EventBase::operator==(), larcv::IOManager::register_producer(), larcv::EventBase::set_id(), and larcv::IOManager::set_id().
 { return _subrun; }
bool larcv::EventBase::valid () const inline inherited
Make sure run/subrun/event ID is set.
Definition at line 58 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, and larcv::kINVALID_SIZE.
Referenced by larcv::IOManager::clear_entry(), larcv::IOManager::event_id(), larcv::IOManager::get_data(), larcv::IOManager::register_producer(), and larcv::IOManager::set_id().
     { return !(_run == kINVALID_SIZE || _subrun == kINVALID_SIZE || _event == kINVALID_SIZE); }
const larcv::VoxelSet & larcv::VoxelSetArray::voxel_set (InstanceID_t id) const inherited
Access specific VoxelSet.
Definition at line 91 of file Voxel.cxx.
References larcv::VoxelSetArray::_voxel_vv.
   {
     if(id >= _voxel_vv.size()) {
       std::cerr << "VoxelSetArray has no VoxelSet with InstanceID_t " << id << std::endl;
       throw std::exception();
     }
     return _voxel_vv[id];
   }
larcv::VoxelSet & larcv::VoxelSetArray::writeable_voxel_set (const InstanceID_t id) inherited
Access non-const reference of a specific VoxelSet.
Definition at line 136 of file Voxel.cxx.
References larcv::VoxelSetArray::_voxel_vv.
   {
     if(id >= _voxel_vv.size()) {
       std::cerr << "VoxelSetArray has no VoxelSet with InstanceID_t " << id << std::endl;
       throw std::exception();
     }
     return _voxel_vv[id];
   }
The documentation for this class was generated from the following file:
EventVoxel3D.h