LArCV: larcv::EventSparseTensor2D Class Reference
larcv::EventSparseTensor2D Class Reference
Event-wise class to store a collection of VoxelSet (cluster) per projection id.
#include <EventVoxel2D.h>
Public Member Functions
EventSparseTensor2D ()
Default constructor.
virtual ~EventSparseTensor2D ()
Default destructor.
const std::vector
< larcv::SparseTensor2D > & as_vector () const
Access to all stores larcv::SparseTensor2D.
const larcv::SparseTensor2D & sparse_tensor_2d (const ProjectionID_t id) const
Access SparseTensor2D of a specific projection ID.
size_t size () const
Number of valid projection id.
void clear ()
EventBase::clear() override.
void emplace (larcv::SparseTensor2D &&clusters)
Emplace data.
void set (const larcv::SparseTensor2D &clusters)
Set data.
void emplace (larcv::VoxelSet &&cluster, larcv::ImageMeta &&meta)
Emplace a new element.
void set (const larcv::VoxelSet &cluster, const larcv::ImageMeta &meta)
Set a new element.
const std::string & producer () const
Producer name getter.
size_t run () const
Run number getter.
size_t subrun () const
SubRun number getter.
size_t event () const
Event number getter.
bool valid () const
Make sure run/subrun/event ID is set.
bool operator== (const EventBase &rhs) const
Comparison opearator for run/subrun/event id.
bool operator!= (const EventBase &rhs) const
Comparison opearator for run/subrun/event id.
bool operator< (const EventBase &rhs) const
Comparison opearator for run/subrun/event id (for sorted container like std::set and/or std::map)
std::string event_key () const
Formatted string key getter (a string key consists of 0-padded run, subrun, and event id)
void set_id (const size_t run, const size_t subrun, const size_t event)
Setting the id.
Private Attributes
std::vector
< larcv::SparseTensor2D > _tensor_v
Detailed Description
Event-wise class to store a collection of VoxelSet (cluster) per projection id.
A concrete factory class for larcv::EventSparseTensor2D.
Definition at line 70 of file EventVoxel2D.h.
Constructor & Destructor Documentation
larcv::EventSparseTensor2D::EventSparseTensor2D () inline
Default constructor.
Definition at line 75 of file EventVoxel2D.h.
 {}
virtual larcv::EventSparseTensor2D::~EventSparseTensor2D () inline virtual
Default destructor.
Definition at line 78 of file EventVoxel2D.h.
 {}
Member Function Documentation
const std::vector<larcv::SparseTensor2D>& larcv::EventSparseTensor2D::as_vector () const inline
Access to all stores larcv::SparseTensor2D.
Definition at line 84 of file EventVoxel2D.h.
References _tensor_v.
 { return _tensor_v; }
void larcv::EventSparseTensor2D::clear () inline virtual
EventBase::clear() override.
Reimplemented from larcv::EventBase.
Definition at line 94 of file EventVoxel2D.h.
References _tensor_v, and larcv::EventBase::clear().
 {EventBase::clear(); _tensor_v.clear();}
void larcv::EventSparseTensor2D::emplace (larcv::SparseTensor2D && clusters)
Emplace data.
Definition at line 68 of file EventVoxel2D.cxx.
References _tensor_v.
Referenced by emplace(), and set().
   {
     if(_tensor_v.size() <= cluster.meta().id())
       _tensor_v.resize(cluster.meta().id()+1);
     _tensor_v[cluster.meta().id()] = std::move(cluster);
   }
void larcv::EventSparseTensor2D::emplace (larcv::VoxelSet && cluster, larcv::ImageMeta && meta)
Emplace a new element.
Definition at line 82 of file EventVoxel2D.cxx.
References emplace().
   {
     larcv::SparseTensor2D source(std::move(cluster),std::move(meta));
     emplace(std::move(source));
   }
size_t larcv::EventBase::event () const inline inherited
Event number getter.
Definition at line 56 of file EventBase.h.
References larcv::EventBase::_event.
Referenced by larcv::IOManager::clear_entry(), larcv::IOManager::get_data(), larcv::EventBase::operator<(), larcv::EventBase::operator==(), larcv::IOManager::register_producer(), larcv::EventBase::set_id(), and larcv::IOManager::set_id().
 { return _event;  }
std::string larcv::EventBase::event_key () const inherited
Formatted string key getter (a string key consists of 0-padded run, subrun, and event id)
Definition at line 13 of file EventBase.cxx.
References larcv::EventBase::_event, larcv::EventBase::_run, and larcv::EventBase::_subrun.
Referenced by larcv::IOManager::set_id().
   {
     std::stringstream ss;
     ss << std::setw( 7 ) << std::setfill( '0' ) << _run << "_"
        << std::setw( 5 ) << std::setfill( '0' ) << _subrun << "_"
        << std::setw( 6 ) << std::setfill( '0' ) << _event;
     return ss.str();
   }
bool larcv::EventBase::operator!= (const EventBase & rhs) const inline inherited
Comparison opearator for run/subrun/event id.
Definition at line 64 of file EventBase.h.
     { return !((*this) == rhs); }
bool larcv::EventBase::operator< (const EventBase & rhs) const inline inherited
Comparison opearator for run/subrun/event id (for sorted container like std::set and/or std::map)
Definition at line 67 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, larcv::EventBase::event(), larcv::EventBase::run(), and larcv::EventBase::subrun().
     {
       if(_run < rhs.run()) return true;
       if(_run > rhs.run()) return false;
       if(_subrun < rhs.subrun()) return true;
       if(_subrun > rhs.subrun()) return false;
       if(_event < rhs.event()) return true;
       if(_event > rhs.event()) return false;
       return false;
     }
bool larcv::EventBase::operator== (const EventBase & rhs) const inline inherited
Comparison opearator for run/subrun/event id.
Definition at line 61 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, larcv::EventBase::event(), larcv::EventBase::run(), and larcv::EventBase::subrun().
     { return (_run == rhs.run() && _subrun == rhs.subrun() && _event == rhs.event()); }
const std::string& larcv::EventBase::producer () const inline inherited
Producer name getter.
Definition at line 50 of file EventBase.h.
References larcv::EventBase::_producer.
 { return _producer; }
size_t larcv::EventBase::run () const inline inherited
Run number getter.
Definition at line 52 of file EventBase.h.
References larcv::EventBase::_run.
Referenced by larcv::IOManager::clear_entry(), larcv::IOManager::get_data(), larcv::EventBase::operator<(), larcv::EventBase::operator==(), larcv::IOManager::register_producer(), larcv::EventBase::set_id(), and larcv::IOManager::set_id().
 { return _run;    }
void larcv::EventSparseTensor2D::set (const larcv::SparseTensor2D & clusters)
Set data.
Definition at line 75 of file EventVoxel2D.cxx.
References _tensor_v, larcv::BBox2D::id(), and larcv::SparseTensor2D::meta().
   {
     if(_tensor_v.size() <= cluster.meta().id())
       _tensor_v.resize(cluster.meta().id()+1);
     _tensor_v[cluster.meta().id()] = cluster;
   }
void larcv::EventSparseTensor2D::set (const larcv::VoxelSet & cluster, const larcv::ImageMeta & meta)
Set a new element.
Definition at line 88 of file EventVoxel2D.cxx.
References emplace(), and larcv::SparseTensor2D::meta().
   {
     larcv::SparseTensor2D source(cluster);
     source.meta(meta);
     emplace(std::move(source));
   }
void larcv::EventBase::set_id (const size_t run, const size_t subrun, const size_t event) inline inherited
Setting the id.
Definition at line 82 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, larcv::EventBase::event(), larcv::EventBase::run(), and larcv::EventBase::subrun().
Referenced by larcv::IOManager::get_data().
     { _run = run; _subrun = subrun; _event = event; }
size_t larcv::EventSparseTensor2D::size () const inline
Number of valid projection id.
Definition at line 88 of file EventVoxel2D.h.
References _tensor_v.
 { return _tensor_v.size(); }
const larcv::SparseTensor2D & larcv::EventSparseTensor2D::sparse_tensor_2d (const ProjectionID_t id) const
Access SparseTensor2D of a specific projection ID.
Definition at line 59 of file EventVoxel2D.cxx.
References _tensor_v.
   {
     if(id >= _tensor_v.size()) {
       std::cerr << "EventSparseTensor2D does not hold any SparseTensor2D for ProjectionID_t " << id << std::endl;
       throw larbys();
     }
     return _tensor_v[id];
   }
size_t larcv::EventBase::subrun () const inline inherited
SubRun number getter.
Definition at line 54 of file EventBase.h.
References larcv::EventBase::_subrun.
Referenced by larcv::IOManager::clear_entry(), larcv::IOManager::get_data(), larcv::EventBase::operator<(), larcv::EventBase::operator==(), larcv::IOManager::register_producer(), larcv::EventBase::set_id(), and larcv::IOManager::set_id().
 { return _subrun; }
bool larcv::EventBase::valid () const inline inherited
Make sure run/subrun/event ID is set.
Definition at line 58 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, and larcv::kINVALID_SIZE.
Referenced by larcv::IOManager::clear_entry(), larcv::IOManager::event_id(), larcv::IOManager::get_data(), larcv::IOManager::register_producer(), and larcv::IOManager::set_id().
     { return !(_run == kINVALID_SIZE || _subrun == kINVALID_SIZE || _event == kINVALID_SIZE); }
Member Data Documentation
std::vector<larcv::SparseTensor2D> larcv::EventSparseTensor2D::_tensor_v private
Definition at line 106 of file EventVoxel2D.h.
Referenced by as_vector(), clear(), emplace(), set(), size(), and sparse_tensor_2d().
The documentation for this class was generated from the following files:
EventVoxel2D.h
EventVoxel2D.cxx