LArCV: larcv::BBox3D Class Reference
larcv::BBox3D Class Reference
Bounding box in 3D.
#include <BBox.h>
Public Member Functions
BBox3D (double xmin=0, double ymin=0, double zmin=0, double xmax=0, double ymax=0, double zmax=0)
Default constructor.
virtual ~BBox3D ()
Default destructor.
bool operator== (const BBox3D &rhs) const
void update (double xmin, double ymin, double zmin, double xmax, double ymax, double zmax)
void update (const Point3D &pt1, const Point3D &pt2)
bool empty () const
const Point3D & origin () const
const Point3D & bottom_left () const
const Point3D & top_right () const
Point3D center () const
double center_x () const
double center_y () const
double center_z () const
double min_x () const
double min_y () const
double min_z () const
double max_x () const
double max_y () const
double max_z () const
double width () const
double height () const
double depth () const
double volume () const
double area (int axis) const
BBox3D overlap (const BBox3D &box) const
BBox3D inclusive (const BBox3D &box) const
std::string dump () const
Private Attributes
Point3D _p1
bottom-left point coordinate (x1,y1,z1) where x1<x2 and y1<y2 and z1<z2
Point3D _p2
top-right point coordinate (x2,y2,z2) where x1<x2 and y1<y2 and z1<z2
Detailed Description
Bounding box in 3D.
Definition at line 77 of file BBox.h.
Constructor & Destructor Documentation
larcv::BBox3D::BBox3D (double xmin = 0, double ymin = 0, double zmin = 0, double xmax = 0, double ymax = 0, double zmax = 0)
Default constructor.
Definition at line 68 of file BBox.cxx.
Referenced by larcv::Voxel3DMeta::clear(), inclusive(), and overlap().
     : _p1(xmin,ymin,zmin) , _p2(xmax,ymax,zmax)
   {
     if(xmin > xmax) throw larbys("xmin > xmax not allowed for BBox3D construction!");
     if(ymin > ymax) throw larbys("ymin > ymax not allowed for BBox3D construction!");
     if(zmin > zmax) throw larbys("zmin > zmax not allowed for BBox3D construction!");
   }
virtual larcv::BBox3D::~BBox3D () inline virtual
Default destructor.
Definition at line 86 of file BBox.h.
 {}
Member Function Documentation
double larcv::BBox3D::area (int axis) const
Definition at line 92 of file BBox.cxx.
References _p1, _p2, larcv::Point3D::x, larcv::Point3D::y, and larcv::Point3D::z.
   {
     if(axis == 0) return (_p2.x - _p1.x) * (_p2.y - _p1.y); // xy projection
     if(axis == 1) return (_p2.x - _p1.x) * (_p2.z - _p1.z); // xz projection
     if(axis == 2) return (_p2.y - _p1.y) * (_p2.z - _p1.z); // yz projection
     throw larbys("BBox3D::area can only take axis=[0,1,2]!");
   }
const Point3D& larcv::BBox3D::bottom_left () const inline
Definition at line 97 of file BBox.h.
References _p1.
 { return _p1; }
Point3D larcv::BBox3D::center () const inline
Definition at line 99 of file BBox.h.
References center_x(), center_y(), and center_z().
 { return Point3D(center_x(), center_y(), center_z()); }
double larcv::BBox3D::center_x () const inline
Definition at line 100 of file BBox.h.
References _p1, _p2, and larcv::Point3D::x.
Referenced by center().
 { return _p1.x + 0.5*(_p2.x - _p1.x); }
double larcv::BBox3D::center_y () const inline
Definition at line 101 of file BBox.h.
References _p1, _p2, and larcv::Point3D::y.
Referenced by center().
 { return _p1.y + 0.5*(_p2.y - _p1.y); }
double larcv::BBox3D::center_z () const inline
Definition at line 102 of file BBox.h.
References _p1, _p2, and larcv::Point3D::z.
Referenced by center().
 { return _p1.z + 0.5*(_p2.z - _p1.z); }
double larcv::BBox3D::depth () const inline
Definition at line 111 of file BBox.h.
References _p1, _p2, and larcv::Point3D::z.
 { return _p2.z - _p1.z; }
std::string larcv::BBox3D::dump () const
Definition at line 142 of file BBox.cxx.
References _p1, _p2, larcv::Point3D::x, larcv::Point3D::y, and larcv::Point3D::z.
Referenced by larcv::Particle::dump().
   {
     std::stringstream ss;
     ss << "    (" << _p1.x << "," << _p1.y << "," << _p1.z << ") => (" << _p2.x << "," << _p2.y << "," << _p2.z << ")" << std::endl;;
     return ss.str();
   }
bool larcv::BBox3D::empty () const inline
Definition at line 95 of file BBox.h.
References _p1, and _p2.
Referenced by larcv::Voxel3DMeta::update().
 { return (_p1 == _p2); }
double larcv::BBox3D::height () const inline
Definition at line 110 of file BBox.h.
References _p1, _p2, and larcv::Point3D::y.
 { return _p2.y - _p1.y; }
BBox3D larcv::BBox3D::inclusive (const BBox3D & box) const
Definition at line 128 of file BBox.cxx.
References BBox3D(), max_x(), max_y(), max_z(), min_x(), min_y(), and min_z().
   {
     double min_x = ( box.min_x() < this->min_x() ? box.min_x() : this->min_x() ); //pick smaller x min-boudn
     double max_x = ( box.max_x() > this->max_x() ? box.max_x() : this->max_x() ); //pick larger x max-bound
     double min_y = ( box.min_y() < this->min_y() ? box.min_y() : this->min_y() ); //pick smaller y min-boudn
     double max_y = ( box.max_y() > this->max_y() ? box.max_y() : this->max_y() ); //pick larger y max-bound
     double min_z = ( box.min_z() < this->min_z() ? box.min_z() : this->min_z() ); //pick smaller z min-boudn
     double max_z = ( box.max_z() > this->max_z() ? box.max_z() : this->max_z() ); //pick larger z max-bound
     return BBox3D(min_x, min_y, min_z, max_x, max_y, max_z);
   }
double larcv::BBox3D::max_x () const inline
Definition at line 106 of file BBox.h.
References _p2, and larcv::Point3D::x.
Referenced by larcv::Voxel3DMeta::dump(), larcv::Voxel3DMeta::id(), inclusive(), overlap(), and larcv::Voxel3DMeta::update().
 { return _p2.x; }
double larcv::BBox3D::max_y () const inline
Definition at line 107 of file BBox.h.
References _p2, and larcv::Point3D::y.
Referenced by larcv::Voxel3DMeta::dump(), larcv::Voxel3DMeta::id(), inclusive(), overlap(), and larcv::Voxel3DMeta::update().
 { return _p2.y; }
double larcv::BBox3D::max_z () const inline
Definition at line 108 of file BBox.h.
References _p2, and larcv::Point3D::z.
Referenced by larcv::Voxel3DMeta::dump(), larcv::Voxel3DMeta::id(), inclusive(), overlap(), and larcv::Voxel3DMeta::update().
 { return _p2.z; }
double larcv::BBox3D::min_x () const inline
Definition at line 103 of file BBox.h.
References _p1, and larcv::Point3D::x.
Referenced by larcv::Voxel3DMeta::dump(), larcv::Voxel3DMeta::id(), inclusive(), overlap(), larcv::Voxel3DMeta::pos_x(), larcv::Voxel3DMeta::position(), and larcv::Voxel3DMeta::update().
 { return _p1.x; }
double larcv::BBox3D::min_y () const inline
Definition at line 104 of file BBox.h.
References _p1, and larcv::Point3D::y.
Referenced by larcv::Voxel3DMeta::dump(), larcv::Voxel3DMeta::id(), inclusive(), overlap(), larcv::Voxel3DMeta::pos_y(), larcv::Voxel3DMeta::position(), and larcv::Voxel3DMeta::update().
 { return _p1.y; }
double larcv::BBox3D::min_z () const inline
Definition at line 105 of file BBox.h.
References _p1, and larcv::Point3D::z.
Referenced by larcv::Voxel3DMeta::dump(), larcv::Voxel3DMeta::id(), inclusive(), overlap(), larcv::Voxel3DMeta::pos_z(), larcv::Voxel3DMeta::position(), and larcv::Voxel3DMeta::update().
 { return _p1.z; }
bool larcv::BBox3D::operator== (const BBox3D & rhs) const inline
Definition at line 88 of file BBox.h.
References _p1, and _p2.
     { return (_p1 == rhs._p1 && _p2 == rhs._p2); }
const Point3D& larcv::BBox3D::origin () const inline
Definition at line 96 of file BBox.h.
References _p1.
 { return _p1; }
BBox3D larcv::BBox3D::overlap (const BBox3D & box) const
Definition at line 101 of file BBox.cxx.
References BBox3D(), max_x(), max_y(), max_z(), min_x(), min_y(), and min_z().
   {
     double minx = ( box.min_x() < this->min_x() ? this->min_x() : box.min_x()  ); //pick larger x min-bound
     double maxx = ( box.max_x() < this->max_x() ? box.max_x()  : this->max_x() ); //pick smaller x max-bound
     double miny = ( box.min_y() < this->min_y() ? this->min_y() : box.min_y()  ); //pick larger x min-bound
     double maxy = ( box.max_y() < this->max_y() ? box.max_y()  : this->max_y() ); //pick smaller x max-bound
     double minz = ( box.min_z() < this->min_z() ? this->min_z() : box.min_z()  ); //pick larger x min-bound
     double maxz = ( box.max_z() < this->max_z() ? box.max_z()  : this->max_z() ); //pick smaller x max-bound
     if(!(minx < maxx && miny < maxy && minz < maxz)) {
       std::stringstream ss;
       ss << "No overlap found ... this"
      << " X: " << this->min_x() << " => " << this->max_x()
      << " Y: " << this->min_y() << " => " << this->max_y()
      << " Z: " << this->min_z() << " => " << this->max_z()
      << " ... the other"
      << " X: " << box.min_x() << " => " << box.max_x()
      << " Y: " << box.min_y() << " => " << box.max_y()
      << " Z: " << box.min_z() << " => " << box.max_z()
      << std::endl;
       throw larbys(ss.str());
     }
     return BBox3D(minx, miny, minz, maxx, maxy, maxz);
   }
const Point3D& larcv::BBox3D::top_right () const inline
Definition at line 98 of file BBox.h.
References _p2.
 { return _p2; }
void larcv::BBox3D::update (double xmin, double ymin, double zmin, double xmax, double ymax, double zmax)
Definition at line 79 of file BBox.cxx.
References _p1, _p2, larcv::Point3D::x, larcv::Point3D::y, and larcv::Point3D::z.
Referenced by larcv::Voxel3DMeta::set(), and update().
   {
     if(xmin > xmax) throw larbys("xmin > xmax not allowed for BBox3D::Update!");
     if(ymin > ymax) throw larbys("ymin > ymax not allowed for BBox3D::Update!");
     if(zmin > zmax) throw larbys("zmin > zmax not allowed for BBox3D::Update!");
     _p1.x = xmin; _p1.y = ymin; _p1.z = zmin;
     _p2.x = xmax, _p2.y = ymax; _p2.z = zmax;
   }
void larcv::BBox3D::update (const Point3D & pt1, const Point3D & pt2)
Definition at line 89 of file BBox.cxx.
References update(), larcv::Point3D::x, larcv::Point3D::y, and larcv::Point3D::z.
   { update(p1.x,p1.y,p1.z,p2.x,p2.y,p2.z); }
double larcv::BBox3D::volume () const inline
Definition at line 112 of file BBox.h.
References _p1, _p2, larcv::Point3D::x, larcv::Point3D::y, and larcv::Point3D::z.
 { return (_p2.x - _p1.x) * (_p2.y - _p1.y) * (_p2.z - _p1.z); }
double larcv::BBox3D::width () const inline
Definition at line 109 of file BBox.h.
References _p1, _p2, and larcv::Point3D::x.
 { return _p2.x - _p1.x; }
Member Data Documentation
Point3D larcv::BBox3D::_p1 private
bottom-left point coordinate (x1,y1,z1) where x1<x2 and y1<y2 and z1<z2
Definition at line 121 of file BBox.h.
Referenced by area(), bottom_left(), center_x(), center_y(), center_z(), depth(), dump(), empty(), height(), min_x(), min_y(), min_z(), operator==(), origin(), update(), volume(), and width().
Point3D larcv::BBox3D::_p2 private
top-right point coordinate (x2,y2,z2) where x1<x2 and y1<y2 and z1<z2
Definition at line 122 of file BBox.h.
Referenced by area(), center_x(), center_y(), center_z(), depth(), dump(), empty(), height(), max_x(), max_y(), max_z(), operator==(), top_right(), update(), volume(), and width().
The documentation for this class was generated from the following files:
BBox.h
BBox.cxx