LArCV: larcv::VoxelSetArray Class Reference
larcv::VoxelSetArray Class Reference
Container of multiple VoxelSet (i.e.
#include <Voxel.h>
Public Member Functions
VoxelSetArray ()
Default ctor.
virtual ~VoxelSetArray ()
Default dtor.
size_t size () const
Get # of VoxelSet.
const larcv::VoxelSet & voxel_set (InstanceID_t id) const
Access specific VoxelSet.
const std::vector
< larcv::VoxelSet > & as_vector () const
Access all VoxelSet as a vector.
void clear_data ()
Clear everything.
void resize (const size_t num)
Resize voxel array.
larcv::VoxelSet & writeable_voxel_set (const InstanceID_t id)
Access non-const reference of a specific VoxelSet.
void emplace (std::vector< larcv::VoxelSet > &&voxel_vv)
Move an arrray of VoxelSet. Each element's InstanceID_t gets updated.
void insert (const std::vector< larcv::VoxelSet > &voxel_vv)
Set an array of VoxelSet. Each element's InstanceID_t gets updated.
void emplace (larcv::VoxelSet &&voxel_v)
Move a VoxelSet into a collection. The InstanceID_t is respected.
void insert (const larcv::VoxelSet &voxel_v)
Set a VoxelSet into a collection. The InstanceID_t is respected.
void move (larcv::VoxelSetArray &&orig)
Mover.
Private Attributes
std::vector< larcv::VoxelSet > _voxel_vv
Detailed Description
Container of multiple VoxelSet (i.e.
container w/ InstanceID_t & VoxelSet pairs)
Definition at line 154 of file Voxel.h.
Constructor & Destructor Documentation
larcv::VoxelSetArray::VoxelSetArray () inline
Default ctor.
Definition at line 157 of file Voxel.h.
 {}
virtual larcv::VoxelSetArray::~VoxelSetArray () inline virtual
Default dtor.
Definition at line 159 of file Voxel.h.
 {}
Member Function Documentation
const std::vector<larcv::VoxelSet>& larcv::VoxelSetArray::as_vector () const inline
Access all VoxelSet as a vector.
Definition at line 169 of file Voxel.h.
References _voxel_vv.
Referenced by larcv::as_image2d(), larcv::as_sparse_tensor2d(), larcv::as_sparse_tensor3d(), larcv::ClusterPixel2D::meta(), and larcv::ClusterVoxel3D::meta().
     { return _voxel_vv; }
void larcv::VoxelSetArray::clear_data () inline
Clear everything.
Definition at line 176 of file Voxel.h.
References _voxel_vv.
Referenced by larcv::ClusterVoxel3D::clear_data(), larcv::ClusterPixel2D::clear_data(), larcv::PyCluster3DMaker::initialize(), and larcv::PyCluster3DMaker::process().
 { _voxel_vv.clear(); }
void larcv::VoxelSetArray::emplace (std::vector< larcv::VoxelSet > && voxel_vv)
Move an arrray of VoxelSet. Each element's InstanceID_t gets updated.
Definition at line 100 of file Voxel.cxx.
References _voxel_vv.
Referenced by larcv::PyCluster3DMaker::append_ndarray().
   {
     _voxel_vv = std::move(voxel_vv);
     for(size_t id=0; id<_voxel_vv.size(); ++id)
       _voxel_vv[id].id(id);
   }
void larcv::VoxelSetArray::emplace (larcv::VoxelSet && voxel_v)
Move a VoxelSet into a collection. The InstanceID_t is respected.
Definition at line 114 of file Voxel.cxx.
References _voxel_vv.
   {
     if(voxel_v.id() >= _voxel_vv.size()) {
       size_t orig_size = _voxel_vv.size();
       _voxel_vv.resize(voxel_v.id()+1);
       for(size_t id=orig_size; id<_voxel_vv.size(); ++id)
         _voxel_vv[id].id(id);
     }
     _voxel_vv[voxel_v.id()] = std::move(voxel_v);
   }
void larcv::VoxelSetArray::insert (const std::vector< larcv::VoxelSet > & voxel_vv) inline
Set an array of VoxelSet. Each element's InstanceID_t gets updated.
Definition at line 107 of file Voxel.cxx.
References _voxel_vv.
   {
     _voxel_vv = voxel_vv;
     for(size_t id=0; id<_voxel_vv.size(); ++id)
       _voxel_vv[id].id(id);
   }
void larcv::VoxelSetArray::insert (const larcv::VoxelSet & voxel_v)
Set a VoxelSet into a collection. The InstanceID_t is respected.
Definition at line 125 of file Voxel.cxx.
References _voxel_vv, and larcv::VoxelSet::id().
   {
     if(voxel_v.id() >= _voxel_vv.size()) {
       size_t orig_size = _voxel_vv.size();
       _voxel_vv.resize(voxel_v.id()+1);
       for(size_t id=orig_size; id<_voxel_vv.size(); ++id)
         _voxel_vv[id].id(id);
     }
     _voxel_vv[voxel_v.id()] = voxel_v;
   }
void larcv::VoxelSetArray::move (larcv::VoxelSetArray && orig) inline
Mover.
Definition at line 191 of file Voxel.h.
References _voxel_vv.
     { _voxel_vv = std::move(orig._voxel_vv); }
void larcv::VoxelSetArray::resize (const size_t num) inline
Resize voxel array.
Definition at line 178 of file Voxel.h.
References _voxel_vv.
     { _voxel_vv.resize(num); for(size_t i=0; i<num; ++i) _voxel_vv[i].id(i); }
size_t larcv::VoxelSetArray::size () const inline
Get # of VoxelSet.
Definition at line 165 of file Voxel.h.
References _voxel_vv.
Referenced by larcv::PyCluster3DMaker::append_ndarray().
 { return _voxel_vv.size(); }
const larcv::VoxelSet & larcv::VoxelSetArray::voxel_set (InstanceID_t id) const
Access specific VoxelSet.
Definition at line 91 of file Voxel.cxx.
References _voxel_vv.
   {
     if(id >= _voxel_vv.size()) {
       std::cerr << "VoxelSetArray has no VoxelSet with InstanceID_t " << id << std::endl;
       throw std::exception();
     }
     return _voxel_vv[id];
   }
larcv::VoxelSet & larcv::VoxelSetArray::writeable_voxel_set (const InstanceID_t id)
Access non-const reference of a specific VoxelSet.
Definition at line 136 of file Voxel.cxx.
References _voxel_vv.
   {
     if(id >= _voxel_vv.size()) {
       std::cerr << "VoxelSetArray has no VoxelSet with InstanceID_t " << id << std::endl;
       throw std::exception();
     }
     return _voxel_vv[id];
   }
Member Data Documentation
std::vector<larcv::VoxelSet> larcv::VoxelSetArray::_voxel_vv private
Definition at line 195 of file Voxel.h.
Referenced by as_vector(), clear_data(), emplace(), insert(), move(), resize(), size(), voxel_set(), and writeable_voxel_set().
The documentation for this class was generated from the following files:
Voxel.h
Voxel.cxx