LArCV: larcv::BBox2D Class Reference
larcv::BBox2D Class Reference
Bounding box in 2D.
#include <BBox.h>
Public Member Functions
BBox2D (double xmin=0, double ymin=0, double xmax=0, double ymax=0, ProjectionID_t id=kINVALID_PROJECTIONID)
Default constructor.
virtual ~BBox2D ()
Default destructor.
bool operator== (const BBox2D &rhs) const
void update (double xmin, double ymin, double xmax, double ymax, ProjectionID_t id=kINVALID_PROJECTIONID)
void update (const Point2D &pt1, const Point2D &pt2, ProjectionID_t id=kINVALID_PROJECTIONID)
bool empty () const
const Point2D & origin () const
const Point2D & bottom_left () const
const Point2D & top_right () const
Point2D center () const
double center_x () const
double center_y () const
double min_x () const
double min_y () const
double max_x () const
double max_y () const
double width () const
double height () const
double area () const
ProjectionID_t id () const
std::string dump () const
BBox2D overlap (const BBox2D &box) const
BBox2D inclusive (const BBox2D &box) const
Private Attributes
ProjectionID_t _id
ProjectionID_t identifies types of 2D projections to which BBox belongs.
Point2D _p1
bottom-left point coordinate (x1,y1) where x1<x2 and y1<y2
Point2D _p2
top-right point coordinate (x2,y2) where x1<x2 and y1<y2
Detailed Description
Bounding box in 2D.
Definition at line 26 of file BBox.h.
Constructor & Destructor Documentation
larcv::BBox2D::BBox2D (double xmin = 0, double ymin = 0, double xmax = 0, double ymax = 0, ProjectionID_t id = kINVALID_PROJECTIONID)
Default constructor.
Definition at line 10 of file BBox.cxx.
Referenced by inclusive(), and overlap().
     : _id(id), _p1(xmin,ymin) , _p2(xmax,ymax)
   {
     if(xmin > xmax) throw larbys("xmin > xmax not allowed for BBox2D construction!");
     if(ymin > ymax) throw larbys("ymin > ymax not allowed for BBox2D construction!");
   }
virtual larcv::BBox2D::~BBox2D () inline virtual
Default destructor.
Definition at line 36 of file BBox.h.
 {}
Member Function Documentation
double larcv::BBox2D::area () const inline
Definition at line 59 of file BBox.h.
References _p1, _p2, larcv::Point2D::x, and larcv::Point2D::y.
 { return (_p2.y - _p1.y) * (_p2.x - _p1.x); }
const Point2D& larcv::BBox2D::bottom_left () const inline
Definition at line 48 of file BBox.h.
References _p1.
 { return _p1; }
Point2D larcv::BBox2D::center () const inline
Definition at line 50 of file BBox.h.
References center_x(), and center_y().
 { return Point2D(center_x(), center_y()); }
double larcv::BBox2D::center_x () const inline
Definition at line 51 of file BBox.h.
References _p1, _p2, and larcv::Point2D::x.
Referenced by center().
 { return _p1.x + 0.5*(_p2.x - _p1.x); }
double larcv::BBox2D::center_y () const inline
Definition at line 52 of file BBox.h.
References _p1, _p2, and larcv::Point2D::y.
Referenced by center().
 { return _p1.y + 0.5*(_p2.y - _p1.y); }
std::string larcv::BBox2D::dump () const
Definition at line 57 of file BBox.cxx.
References _p1, _p2, larcv::Point2D::x, and larcv::Point2D::y.
   {
     std::stringstream ss;
     ss << "    (" << _p1.x << "," << _p1.y << ") => (" << _p2.x << "," << _p2.y << ")" << std::endl;;
     return ss.str();
   }
bool larcv::BBox2D::empty () const inline
Definition at line 46 of file BBox.h.
References _p1, and _p2.
 { return (_p1 == _p2); }
double larcv::BBox2D::height () const inline
Definition at line 58 of file BBox.h.
References _p1, _p2, and larcv::Point2D::y.
Referenced by larcv::ImageMeta::pixel_height().
 { return _p2.y - _p1.y; }
ProjectionID_t larcv::BBox2D::id () const inline
Definition at line 60 of file BBox.h.
References _id.
Referenced by larcv::Image2D::crop(), larcv::ImageMeta::dump(), larcv::EventClusterPixel2D::set(), larcv::EventSparseTensor2D::set(), and update().
 { return _id; }
BBox2D larcv::BBox2D::inclusive (const BBox2D & box) const
Definition at line 46 of file BBox.cxx.
References BBox2D(), max_x(), max_y(), min_x(), and min_y().
Referenced by larcv::ImageMeta::inclusive().
   {
     double min_x = ( box.min_x() < this->min_x() ? box.min_x() : this->min_x() ); //pick smaller x min-boudn
     double max_x = ( box.max_x() > this->max_x() ? box.max_x() : this->max_x() ); //pick larger x max-bound
     double min_y = ( box.min_y() < this->min_y() ? box.min_y() : this->min_y() ); //pick smaller y min-boudn
     double max_y = ( box.max_y() > this->max_y() ? box.max_y() : this->max_y() ); //pick larger y max-bound
     return BBox2D(min_x, min_y, max_x, max_y);
   }
double larcv::BBox2D::max_x () const inline
Definition at line 55 of file BBox.h.
References _p2, and larcv::Point2D::x.
Referenced by larcv::ImageMeta::col(), larcv::Image2D::crop(), inclusive(), overlap(), larcv::Image2D::overlay(), and larcv::ImageMeta::reset_origin().
 { return _p2.x; }
double larcv::BBox2D::max_y () const inline
Definition at line 56 of file BBox.h.
References _p2, and larcv::Point2D::y.
Referenced by larcv::Image2D::crop(), larcv::fill_img_col(), inclusive(), overlap(), larcv::Image2D::overlay(), larcv::ImageMeta::reset_origin(), and larcv::ImageMeta::row().
 { return _p2.y; }
double larcv::BBox2D::min_x () const inline
Definition at line 53 of file BBox.h.
References _p1, and larcv::Point2D::x.
Referenced by larcv::ImageMeta::col(), larcv::Image2D::crop(), inclusive(), overlap(), larcv::Image2D::overlay(), and larcv::ImageMeta::pos_x().
 { return _p1.x; }
double larcv::BBox2D::min_y () const inline
Definition at line 54 of file BBox.h.
References _p1, and larcv::Point2D::y.
Referenced by larcv::Image2D::crop(), larcv::fill_img_col(), inclusive(), overlap(), larcv::Image2D::overlay(), larcv::ImageMeta::pos_y(), and larcv::ImageMeta::row().
 { return _p1.y; }
bool larcv::BBox2D::operator== (const BBox2D & rhs) const inline
Definition at line 38 of file BBox.h.
References _p1, and _p2.
     { return (_p1 == rhs._p1 && _p2 == rhs._p2); }
const Point2D& larcv::BBox2D::origin () const inline
Definition at line 47 of file BBox.h.
References _p1.
 { return _p1; }
BBox2D larcv::BBox2D::overlap (const BBox2D & box) const
Definition at line 29 of file BBox.cxx.
References BBox2D(), max_x(), max_y(), min_x(), and min_y().
Referenced by larcv::ImageMeta::overlap().
   {
     double minx = ( box.min_x() < this->min_x() ? this->min_x() : box.min_x()  ); //pick larger x min-bound
     double maxx = ( box.max_x() < this->max_x() ? box.max_x()  : this->max_x() ); //pick smaller x max-bound
     double miny = ( box.min_y() < this->min_y() ? this->min_y() : box.min_y()  ); //pick larger x min-bound
     double maxy = ( box.max_y() < this->max_y() ? box.max_y()  : this->max_y() ); //pick smaller x max-bound
     if(!(minx < maxx && miny < maxy)) {
       std::stringstream ss;
       ss << "No overlap found ... this X: " << this->min_x() << " => " << this->max_x() << " Y: " << this->min_y() << " => " << this->max_y()
      << " ... the other X: " << box.min_x() << " => " << box.max_x() << " Y: " << box.min_y() << " => " << box.max_y() << std::endl;
       throw larbys(ss.str());
     }
     return BBox2D(minx, miny, maxx, maxy);
   }
const Point2D& larcv::BBox2D::top_right () const inline
Definition at line 49 of file BBox.h.
References _p2.
 { return _p2; }
void larcv::BBox2D::update (double xmin, double ymin, double xmax, double ymax, ProjectionID_t id = kINVALID_PROJECTIONID)
Definition at line 17 of file BBox.cxx.
References _id, _p1, _p2, id(), larcv::Point2D::x, and larcv::Point2D::y.
Referenced by larcv::ImageMeta::reset_origin(), and update().
   {
     if(xmin > xmax) throw larbys("xmin > xmax not allowed for BBox2D::Update!");
     if(ymin > ymax) throw larbys("ymin > ymax not allowed for BBox2D::Update!");
     _p1.x = xmin; _p1.y = ymin;
     _p2.x = xmax, _p2.y = ymax;
     _id = id;
   }
void larcv::BBox2D::update (const Point2D & pt1, const Point2D & pt2, ProjectionID_t id = kINVALID_PROJECTIONID)
Definition at line 26 of file BBox.cxx.
References _id, id(), update(), larcv::Point2D::x, and larcv::Point2D::y.
   { update(p1.x,p1.y,p2.x,p2.y); _id = id; }
double larcv::BBox2D::width () const inline
Definition at line 57 of file BBox.h.
References _p1, _p2, and larcv::Point2D::x.
Referenced by larcv::ImageMeta::pixel_width().
 { return _p2.x - _p1.x; }
Member Data Documentation
ProjectionID_t larcv::BBox2D::_id private
ProjectionID_t identifies types of 2D projections to which BBox belongs.
Definition at line 68 of file BBox.h.
Referenced by id(), and update().
Point2D larcv::BBox2D::_p1 private
bottom-left point coordinate (x1,y1) where x1<x2 and y1<y2
Definition at line 69 of file BBox.h.
Referenced by area(), bottom_left(), center_x(), center_y(), dump(), empty(), height(), min_x(), min_y(), operator==(), origin(), update(), and width().
Point2D larcv::BBox2D::_p2 private
top-right point coordinate (x2,y2) where x1<x2 and y1<y2
Definition at line 70 of file BBox.h.
Referenced by area(), center_x(), center_y(), dump(), empty(), height(), max_x(), max_y(), operator==(), top_right(), update(), and width().
The documentation for this class was generated from the following files:
BBox.h
BBox.cxx