LArCV: larcv::Vertex Class Reference
larcv::Vertex Class Reference
#include <Vertex.h>
Public Member Functions
Vertex ()
Particle ID default constructor.
Vertex (double x, double y, double z, double t)
void reset ()
Reset function.
void reset (double x, double y, double z, double t)
Reset function for x, y, z, t.
double x () const
double y () const
double z () const
double t () const
virtual ~Vertex ()
Default destructor.
bool operator== (const Vertex &rhs) const
bool operator!= (const Vertex &rhs) const
bool operator< (const Vertex &rhs) const
Private Member Functions
void approx ()
Private Attributes
double _x
double _y
double _z
double _t
Detailed Description
Definition at line 6 of file Vertex.h.
Constructor & Destructor Documentation
larcv::Vertex::Vertex ()
Particle ID default constructor.
Definition at line 9 of file Vertex.cxx.
References approx().
     : _x(0)
     , _y(0)
     , _z(0)
     , _t(0)
   {approx();}
larcv::Vertex::Vertex (double x, double y, double z, double t)
Definition at line 16 of file Vertex.cxx.
References approx().
     : _x(x), _y(y), _z(z), _t(t)
   {approx();}
virtual larcv::Vertex::~Vertex () inline virtual
Default destructor.
Definition at line 24 of file Vertex.h.
 {};
Member Function Documentation
void larcv::Vertex::approx () private
Definition at line 33 of file Vertex.cxx.
References _t, _x, _y, and _z.
Referenced by reset(), and Vertex().
   {
     _x = (double)( ((double)((signed long long)(_x * 1.e6)) * 1.e-6 ));
     _y = (double)( ((double)((signed long long)(_y * 1.e6)) * 1.e-6 ));
     _z = (double)( ((double)((signed long long)(_z * 1.e6)) * 1.e-6 ));
     _t = (double)( ((double)((signed long long)(_t * 1.e6)) * 1.e-6 ));
   }
bool larcv::Vertex::operator!= (const Vertex & rhs) const inline
Definition at line 31 of file Vertex.h.
     {
       return !((*this) == rhs);
     }
bool larcv::Vertex::operator< (const Vertex & rhs) const inline
Definition at line 36 of file Vertex.h.
References _t, _x, _y, and _z.
     {
       if( _x     < rhs._x ) return true;
       if( rhs._x < _x     ) return false;
       if( _y     < rhs._y ) return true;
       if( rhs._y < _y     ) return false;
       if( _z     < rhs._z ) return true;
       if( rhs._z < _z     ) return false;
       if( _t     < rhs._t ) return true;
       if( rhs._t < _t     ) return false;
       return false;
     }
bool larcv::Vertex::operator== (const Vertex & rhs) const inline
Definition at line 26 of file Vertex.h.
References _t, _x, _y, and _z.
     {
       return ( _x == rhs._x && _y == rhs._y && _z == rhs._z && _t == rhs._t );
     }
void larcv::Vertex::reset ()
Reset function.
Definition at line 20 of file Vertex.cxx.
References _t, _x, _y, and _z.
                     {
     _x = _y = _z = _t = 0;
   }
void larcv::Vertex::reset (double x, double y, double z, double t)
Reset function for x, y, z, t.
Definition at line 24 of file Vertex.cxx.
References _t, _x, _y, _z, approx(), t(), x(), y(), and z().
   {
     _x = x;
     _y = y;
     _z = z;
     _t = t;
     approx();
   }
double larcv::Vertex::t () const inline
Definition at line 21 of file Vertex.h.
References _t.
Referenced by larcv::Particle::ancestor_t(), larcv::Particle::parent_t(), reset(), and larcv::Particle::t().
 { return _t; }
double larcv::Vertex::x () const inline
Definition at line 18 of file Vertex.h.
References _x.
Referenced by larcv::Particle::ancestor_x(), larcv::Particle::parent_x(), reset(), and larcv::Particle::x().
 { return _x; }
double larcv::Vertex::y () const inline
Definition at line 19 of file Vertex.h.
References _y.
Referenced by larcv::Particle::ancestor_y(), larcv::Particle::parent_y(), reset(), and larcv::Particle::y().
 { return _y; }
double larcv::Vertex::z () const inline
Definition at line 20 of file Vertex.h.
References _z.
Referenced by larcv::Particle::ancestor_z(), larcv::Particle::parent_z(), reset(), and larcv::Particle::z().
 { return _z; }
Member Data Documentation
double larcv::Vertex::_t private
Definition at line 51 of file Vertex.h.
Referenced by approx(), operator<(), operator==(), reset(), and t().
double larcv::Vertex::_x private
Definition at line 51 of file Vertex.h.
Referenced by approx(), operator<(), operator==(), reset(), and x().
double larcv::Vertex::_y private
Definition at line 51 of file Vertex.h.
Referenced by approx(), operator<(), operator==(), reset(), and y().
double larcv::Vertex::_z private
Definition at line 51 of file Vertex.h.
Referenced by approx(), operator<(), operator==(), reset(), and z().
The documentation for this class was generated from the following files:
Vertex.h
Vertex.cxx