LArCV: larcv::EventSparseTensor3D Class Reference
larcv::EventSparseTensor3D Class Reference
Event-wise class to store a collection of VoxelSet.
#include <EventVoxel3D.h>
Public Member Functions
EventSparseTensor3D ()
Default constructor.
virtual ~EventSparseTensor3D ()
Default destructor.
void clear ()
EventBase::clear() override.
const std::string & producer () const
Producer name getter.
size_t run () const
Run number getter.
size_t subrun () const
SubRun number getter.
size_t event () const
Event number getter.
bool valid () const
Make sure run/subrun/event ID is set.
bool operator== (const EventBase &rhs) const
Comparison opearator for run/subrun/event id.
bool operator!= (const EventBase &rhs) const
Comparison opearator for run/subrun/event id.
bool operator< (const EventBase &rhs) const
Comparison opearator for run/subrun/event id (for sorted container like std::set and/or std::map)
std::string event_key () const
Formatted string key getter (a string key consists of 0-padded run, subrun, and event id)
void set_id (const size_t run, const size_t subrun, const size_t event)
Setting the id.
const larcv::Voxel3DMeta & meta () const
Access Voxel3DMeta of specific projection.
void meta (const larcv::Voxel3DMeta &meta)
Meta setter.
void emplace (const double x, const double y, const double z, const float val, const bool add=true)
Create & add/set a single voxel.
void emplace (VoxelSet &&vs, const Voxel3DMeta &meta)
Emplace the whole voxel set w/ meta.
void emplace (Voxel &&vox, const bool add)
Emplace a new voxel. Same logic as VoxelSet::add but consumes removable reference.
void emplace (VoxelID_t id, float value, const bool add)
Emplace a new voxel from id & value.
void set (const VoxelSet &vs, const Voxel3DMeta &meta)
Set the whole voxel set w/ meta.
void clear_data ()
Clear everything.
InstanceID_t id () const
InstanceID_t getter.
void id (const InstanceID_t id)
InstanceID_t setter.
const std::vector< larcv::Voxel > & as_vector () const
Access as a raw vector.
const Voxel & find (VoxelID_t id) const
Returns a const reference to a voxel with specified id. if not present, invalid voxel is returned.
float sum () const
Sum of contained voxel values.
float mean () const
Mean of contained voxel values.
void add (const Voxel &vox)
Add a new voxel. If another voxel instance w/ same VoxelID exists, value is added.
void insert (const Voxel &vox)
Set a voxel. If another voxel instance w/ same VoxelID exists, value is set.
VoxelSet & operator+= (float value)
VoxelSet & operator-= (float value)
VoxelSet & operator*= (float factor)
VoxelSet & operator/= (float factor)
Detailed Description
Event-wise class to store a collection of VoxelSet.
A concrete factory class for larcv::EventSparseTensor3D.
Definition at line 47 of file EventVoxel3D.h.
Constructor & Destructor Documentation
larcv::EventSparseTensor3D::EventSparseTensor3D () inline
Default constructor.
Definition at line 53 of file EventVoxel3D.h.
 {}
virtual larcv::EventSparseTensor3D::~EventSparseTensor3D () inline virtual
Default destructor.
Definition at line 56 of file EventVoxel3D.h.
 {}
Member Function Documentation
void larcv::VoxelSet::add (const Voxel & vox) inherited
Add a new voxel. If another voxel instance w/ same VoxelID exists, value is added.
Definition at line 12 of file Voxel.cxx.
References larcv::VoxelSet::emplace().
Referenced by larcv::as_sparse_tensor2d(), and larcv::as_sparse_tensor3d().
   {
     Voxel copy(vox);
     emplace(std::move(copy),true);
   }
const std::vector<larcv::Voxel>& larcv::VoxelSet::as_vector () const inline inherited
Access as a raw vector.
Definition at line 106 of file Voxel.h.
References larcv::VoxelSet::_voxel_v.
Referenced by larcv::as_image2d(), larcv::SparseTensor2D::meta(), and larcv::SparseTensor3D::meta().
 { return _voxel_v; }
void larcv::EventSparseTensor3D::clear () inline virtual
EventBase::clear() override.
Reimplemented from larcv::EventBase.
Definition at line 59 of file EventVoxel3D.h.
References larcv::EventBase::clear(), and larcv::SparseTensor3D::clear_data().
 {EventBase::clear(); SparseTensor3D::clear_data();}
void larcv::SparseTensor3D::clear_data () inline virtual inherited
Clear everything.
Reimplemented from larcv::VoxelSet.
Definition at line 53 of file Voxel3D.h.
References larcv::SparseTensor3D::_meta, and larcv::VoxelSet::clear_data().
Referenced by clear().
 { VoxelSet::clear_data(); _meta = Voxel3DMeta(); }
void larcv::SparseTensor3D::emplace (const double x, const double y, const double z, const float val, const bool add = true) inherited
Create & add/set a single voxel.
Definition at line 24 of file Voxel3D.cxx.
References larcv::SparseTensor3D::_meta, larcv::VoxelSet::emplace(), larcv::Voxel3DMeta::id(), and larcv::kINVALID_VOXELID.
Referenced by larcv::PyTensor3DMaker::process().
     {
         auto id = _meta.id(x, y, z);
         if (id != kINVALID_VOXELID) VoxelSet::emplace(id, val, add);
     }
void larcv::SparseTensor3D::emplace (VoxelSet && vs, const Voxel3DMeta & meta) inline inherited
Emplace the whole voxel set w/ meta.
Definition at line 47 of file Voxel3D.h.
References larcv::SparseTensor3D::meta().
     {*((VoxelSet*)this) = std::move(vs); this->meta(meta);}
void larcv::VoxelSet::emplace (Voxel && vox, const bool add) inherited
Emplace a new voxel. Same logic as VoxelSet::add but consumes removable reference.
Definition at line 41 of file Voxel.cxx.
References larcv::VoxelSet::_voxel_v.
Referenced by larcv::VoxelSet::add(), larcv::as_tensor3d(), larcv::SparseTensor3D::emplace(), larcv::VoxelSet::emplace(), and larcv::VoxelSet::insert().
   {
     // In case it's empty or greater than the last one
     if (_voxel_v.empty() || _voxel_v.back() < vox) {
       _voxel_v.emplace_back(std::move(vox));
       return;
     }
     // In case it's smaller than the first one
     if (_voxel_v.front() > vox) {
       _voxel_v.emplace_back(std::move(vox));
       for (size_t idx = 0; (idx + 1) < _voxel_v.size(); ++idx) {
         auto& element1 = _voxel_v[ _voxel_v.size() - (idx + 1) ];
         auto& element2 = _voxel_v[ _voxel_v.size() - (idx + 2) ];
         std::swap( element1, element2 );
       }
       return;
     }
     // Else do log(N) search
     auto iter = std::lower_bound(_voxel_v.begin(), _voxel_v.end(), vox);
     // Cannot be the end
     if ( iter == _voxel_v.end() ) {
       std::cerr << "VoxelSet sorting logic error!" << std::endl;
       throw std::exception();
     }
     // If found, merge
     if ( vox.id() == (*iter).id() ) {
       if(add) (*iter) += vox.value();
       else (*iter).set(vox.id(),vox.value());
       return;
     }
     // Else insert @ appropriate place
     else {
       size_t target_ctr = _voxel_v.size() - (iter - _voxel_v.begin());
       _voxel_v.emplace_back(std::move(vox));
       for (size_t idx = 0; idx < target_ctr; ++idx) {
         auto& element1 = _voxel_v[ _voxel_v.size() - (idx + 1) ];
         auto& element2 = _voxel_v[ _voxel_v.size() - (idx + 2) ];
         std::swap( element1, element2 );
       }
     }
     return;
   }
void larcv::VoxelSet::emplace (VoxelID_t id, float value, const bool add) inline inherited
Emplace a new voxel from id & value.
Definition at line 126 of file Voxel.h.
References larcv::VoxelSet::emplace().
     { emplace(Voxel(id,value),add); }
size_t larcv::EventBase::event () const inline inherited
Event number getter.
Definition at line 56 of file EventBase.h.
References larcv::EventBase::_event.
Referenced by larcv::IOManager::clear_entry(), larcv::IOManager::get_data(), larcv::EventBase::operator<(), larcv::EventBase::operator==(), larcv::IOManager::register_producer(), larcv::EventBase::set_id(), and larcv::IOManager::set_id().
 { return _event;  }
std::string larcv::EventBase::event_key () const inherited
Formatted string key getter (a string key consists of 0-padded run, subrun, and event id)
Definition at line 13 of file EventBase.cxx.
References larcv::EventBase::_event, larcv::EventBase::_run, and larcv::EventBase::_subrun.
Referenced by larcv::IOManager::set_id().
   {
     std::stringstream ss;
     ss << std::setw( 7 ) << std::setfill( '0' ) << _run << "_"
        << std::setw( 5 ) << std::setfill( '0' ) << _subrun << "_"
        << std::setw( 6 ) << std::setfill( '0' ) << _event;
     return ss.str();
   }
const Voxel & larcv::VoxelSet::find (VoxelID_t id) const inherited
Returns a const reference to a voxel with specified id. if not present, invalid voxel is returned.
Definition at line 24 of file Voxel.cxx.
References larcv::VoxelSet::_voxel_v, larcv::VoxelSet::id(), and larcv::kINVALID_VOXEL().
   {
     if(_voxel_v.empty() ||
        id < _voxel_v.front().id() ||
        id > _voxel_v.back().id())
       return kINVALID_VOXEL;
     Voxel vox(id,0.);
     // Else do log(N) search
     auto iter = std::lower_bound(_voxel_v.begin(), _voxel_v.end(), vox);
     if( (*iter).id() == id ) return (*iter);
     else {
       //std::cout << "Returning invalid voxel since lower_bound had an id " << (*iter).id() << std::endl;
       return kINVALID_VOXEL;
     }
   }
InstanceID_t larcv::VoxelSet::id () const inline inherited
InstanceID_t getter.
Definition at line 104 of file Voxel.h.
References larcv::VoxelSet::_id.
Referenced by larcv::VoxelSet::find(), and larcv::VoxelSetArray::insert().
 { return _id; }
void larcv::VoxelSet::id (const InstanceID_t id) inline inherited
InstanceID_t setter.
Definition at line 129 of file Voxel.h.
References larcv::VoxelSet::_id, and larcv::VoxelSet::id().
Referenced by larcv::VoxelSet::id().
 { _id = id; }
void larcv::VoxelSet::insert (const Voxel & vox) inherited
Set a voxel. If another voxel instance w/ same VoxelID exists, value is set.
Definition at line 18 of file Voxel.cxx.
References larcv::VoxelSet::emplace().
   {
     Voxel copy(vox);
     emplace(std::move(copy),false);
   }
float larcv::VoxelSet::mean () const inline inherited
Mean of contained voxel values.
Definition at line 112 of file Voxel.h.
References larcv::VoxelSet::_voxel_v, and larcv::VoxelSet::sum().
 { return (_voxel_v.empty() ? 0. : sum() / (float)(_voxel_v.size())); }
const larcv::Voxel3DMeta& larcv::SparseTensor3D::meta () const inline inherited
Access Voxel3DMeta of specific projection.
Definition at line 39 of file Voxel3D.h.
References larcv::SparseTensor3D::_meta.
Referenced by larcv::SparseTensor3D::emplace(), larcv::SparseTensor3D::meta(), larcv::SparseTensor3D::operator=(), larcv::SparseTensor3D::set(), and larcv::SparseTensor3D::SparseTensor3D().
 { return _meta; }
void larcv::SparseTensor3D::meta (const larcv::Voxel3DMeta & meta) inherited
Meta setter.
Definition at line 12 of file Voxel3D.cxx.
References larcv::SparseTensor3D::_meta, larcv::VoxelSet::as_vector(), larcv::Voxel3DMeta::id(), larcv::SparseTensor3D::meta(), and larcv::Voxel3DMeta::size().
     {
         for (auto const& vox : this->as_vector()) {
             if (vox.id() < meta.size()) continue;
             std::cerr << "VoxelSet contains ID " << vox.id()
                       << " which cannot exists in Voxel3DMeta with size " << meta.size()
                       << std::endl;
             throw std::exception();
         }
         _meta = meta;
     }
bool larcv::EventBase::operator!= (const EventBase & rhs) const inline inherited
Comparison opearator for run/subrun/event id.
Definition at line 64 of file EventBase.h.
     { return !((*this) == rhs); }
VoxelSet& larcv::VoxelSet::operator*= (float factor) inline inherited
Definition at line 138 of file Voxel.h.
References larcv::VoxelSet::_voxel_v.
     { for(auto& vox : _voxel_v) vox *= factor; return (*this); }
VoxelSet& larcv::VoxelSet::operator+= (float value) inline inherited
Definition at line 134 of file Voxel.h.
References larcv::VoxelSet::_voxel_v.
     { for(auto& vox : _voxel_v) vox += value; return (*this); }
VoxelSet& larcv::VoxelSet::operator-= (float value) inline inherited
Definition at line 136 of file Voxel.h.
References larcv::VoxelSet::_voxel_v.
     { for(auto& vox : _voxel_v) vox -= value; return (*this); }
VoxelSet& larcv::VoxelSet::operator/= (float factor) inline inherited
Definition at line 140 of file Voxel.h.
References larcv::VoxelSet::_voxel_v.
     { for(auto& vox : _voxel_v) vox /= factor; return (*this); }
bool larcv::EventBase::operator< (const EventBase & rhs) const inline inherited
Comparison opearator for run/subrun/event id (for sorted container like std::set and/or std::map)
Definition at line 67 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, larcv::EventBase::event(), larcv::EventBase::run(), and larcv::EventBase::subrun().
     {
       if(_run < rhs.run()) return true;
       if(_run > rhs.run()) return false;
       if(_subrun < rhs.subrun()) return true;
       if(_subrun > rhs.subrun()) return false;
       if(_event < rhs.event()) return true;
       if(_event > rhs.event()) return false;
       return false;
     }
bool larcv::EventBase::operator== (const EventBase & rhs) const inline inherited
Comparison opearator for run/subrun/event id.
Definition at line 61 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, larcv::EventBase::event(), larcv::EventBase::run(), and larcv::EventBase::subrun().
     { return (_run == rhs.run() && _subrun == rhs.subrun() && _event == rhs.event()); }
const std::string& larcv::EventBase::producer () const inline inherited
Producer name getter.
Definition at line 50 of file EventBase.h.
References larcv::EventBase::_producer.
 { return _producer; }
size_t larcv::EventBase::run () const inline inherited
Run number getter.
Definition at line 52 of file EventBase.h.
References larcv::EventBase::_run.
Referenced by larcv::IOManager::clear_entry(), larcv::IOManager::get_data(), larcv::EventBase::operator<(), larcv::EventBase::operator==(), larcv::IOManager::register_producer(), larcv::EventBase::set_id(), and larcv::IOManager::set_id().
 { return _run;    }
void larcv::SparseTensor3D::set (const VoxelSet & vs, const Voxel3DMeta & meta) inline inherited
Set the whole voxel set w/ meta.
Definition at line 50 of file Voxel3D.h.
References larcv::SparseTensor3D::meta().
     {*((VoxelSet*)this) = vs; this->meta(meta);}
void larcv::EventBase::set_id (const size_t run, const size_t subrun, const size_t event) inline inherited
Setting the id.
Definition at line 82 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, larcv::EventBase::event(), larcv::EventBase::run(), and larcv::EventBase::subrun().
Referenced by larcv::IOManager::get_data().
     { _run = run; _subrun = subrun; _event = event; }
size_t larcv::EventBase::subrun () const inline inherited
SubRun number getter.
Definition at line 54 of file EventBase.h.
References larcv::EventBase::_subrun.
Referenced by larcv::IOManager::clear_entry(), larcv::IOManager::get_data(), larcv::EventBase::operator<(), larcv::EventBase::operator==(), larcv::IOManager::register_producer(), larcv::EventBase::set_id(), and larcv::IOManager::set_id().
 { return _subrun; }
float larcv::VoxelSet::sum () const inline inherited
Sum of contained voxel values.
Definition at line 110 of file Voxel.h.
References larcv::VoxelSet::_voxel_v.
Referenced by larcv::VoxelSet::mean().
 { float res=0.; for(auto const& vox : _voxel_v) res+=vox.value(); return res;}
bool larcv::EventBase::valid () const inline inherited
Make sure run/subrun/event ID is set.
Definition at line 58 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, and larcv::kINVALID_SIZE.
Referenced by larcv::IOManager::clear_entry(), larcv::IOManager::event_id(), larcv::IOManager::get_data(), larcv::IOManager::register_producer(), and larcv::IOManager::set_id().
     { return !(_run == kINVALID_SIZE || _subrun == kINVALID_SIZE || _event == kINVALID_SIZE); }
The documentation for this class was generated from the following file:
EventVoxel3D.h