LArCV: larcv::ProcessDriver Class Reference
larcv::ProcessDriver Class Reference
Analysis event-loop driver that executes larcv::ProcessBase inherit "process modules".
#include <ProcessDriver.h>
Public Member Functions
ProcessDriver (std::string name="ProcessDriver")
Default constructor.
~ProcessDriver ()
Default destructor.
void configure (const std::string config_file)
Decodes given configuration text file to create larcv::PSet, then calls the other configure function.
void configure (const PSet &cfg)
Configure itself (mainly larcv::IOManager) and also attached process modules.
void override_input_file (const std::vector< std::string > &flist)
When needs to override the list of input files from what's specified in the configuration.
void override_output_file (const std::string fname)
When needs to override the name of output data file from what's specified in the configuration.
void override_ana_file (const std::string fname)
When needs to override the name of output analysis file from what's specified in the configuration.
void random_access (int flag)
When needs to override the randomized event access in IO from what's specified in the configuration.
void reset ()
Resets the states & all variables. Attached process modules would be removed.
void initialize ()
Must be called after configure. This initializes larcv::IOManager (open files) and initialize attached process modules.
bool process_entry ()
Processes the "next entry" automatically (you don't have to control the counter to specify which entry)
void batch_process (size_t start_entry=0, size_t num_entries=0)
Processes multiple entries (specified in the 2nd argument) from a specified entry (1st argument)
bool process_entry (size_t entry, bool force_reload=false)
Processes a specific entry specified in the argument.
void finalize ()
Must be called after initialize() or process_entry/batch_process. Closes IO and calls finalize method of process modules.
void clear_entry ()
void set_id (size_t run, size_t subrun, size_t event)
A method to force re-set the run/subrun/event ID of a currently processed event, useful when "creating an event".
const EventBase & event_id () const
Returns larcv::EventBase object that contains an "ID" (run/event integers)
ProcessID_t process_id (std::string name) const
Returns a unique ID (integer) assigned for a process module (provide the module's name in argument)
std::vector< std::string > process_names () const
Returns the set of process modules' name.
const std::map< std::string,
size_t > & process_map () const
Returns a mapping between process modules' name and their unique process ID number.
const ProcessBase * process_ptr (ProcessID_t id) const
Returns an attached process module's pointer given a unique ID in the argument.
const IOManager & io () const
Returns read-only larcv::IOManager instance.
size_t get_tree_index (size_t entry) const
When run in random-access IO mode, returns original event entry number for a randomized index number.
bool processing () const
Returns true if after any entry is processed (process_entry/batch_process) but not yet finalized.
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Member Functions
bool _process_entry_ ()
Private Attributes
size_t _batch_start_entry
size_t _batch_num_entry
size_t _current_entry
bool _enable_filter
int _random_access
std::vector< size_t > _access_entry_v
IOManager _io
std::map< std::string,
larcv::ProcessID_t > _proc_m
std::vector< larcv::ProcessBase * > _proc_v
bool _processing
TFile * _fout
std::string _fout_name
bool _has_event_creator
Detailed Description
Analysis event-loop driver that executes larcv::ProcessBase inherit "process modules".
It uses larcv::IOManager behind the scene to run the event loop.
Responsible for propagating a structured configuration parameter sets to configure each process module.
The configuration of larcv::ProcessDriver itself can contain larcv::IOManager configuration.
Definition at line 29 of file ProcessDriver.h.
Constructor & Destructor Documentation
larcv::ProcessDriver::ProcessDriver (std::string name = "ProcessDriver")
Default constructor.
Definition at line 11 of file ProcessDriver.cxx.
     : larcv_base(name)
     , _batch_start_entry(0)
     , _batch_num_entry(0)
     , _enable_filter(false)
     , _random_access(0)
     , _proc_v()
     , _processing(false)
     , _fout(nullptr)
     , _fout_name("")
   {}
larcv::ProcessDriver::~ProcessDriver () inline
Default destructor.
Definition at line 36 of file ProcessDriver.h.
 {}
Member Function Documentation
bool larcv::ProcessDriver::_process_entry_ () private
Definition at line 276 of file ProcessDriver.cxx.
References _current_entry, _enable_filter, _has_event_creator, _io, _proc_v, larcv::IOManager::io_mode(), larcv::IOManager::kREAD, and larcv::IOManager::save_entry().
Referenced by batch_process(), and process_entry().
   {
     // Private method to execute processes and change entry number record
     // This method does not perform any sanity check, hence private and
     // should be used by wrapper method which performs necessary checks.
     // Execute
     bool good_status=true;
     //bool cleared=false;
     for(auto& p : _proc_v) {
       good_status = good_status && p->_process_(_io);
       if(!good_status && _enable_filter) break;
     }
     // No event-write to be done if _has_event_creator is set. Otherwise go ahead
     if(!_has_event_creator) {
       // If not read mode save entry
       if(_io.io_mode() != IOManager::kREAD && (!_enable_filter || good_status)) {
     //cleared = true;
     _io.save_entry();
       }
       /*
       if(!cleared)
     _io.clear_entry();
       cleared=true;
       */
     }
     /*
     if(!cleared && _io.io_mode() == IOManager::kREAD)
       _io.clear_entry();
     */
     // Bump up entry record
     ++_current_entry;
     return good_status;
   }
void larcv::ProcessDriver::batch_process (size_t start_entry = 0, size_t num_entries = 0)
Processes multiple entries (specified in the 2nd argument) from a specified entry (1st argument)
Definition at line 365 of file ProcessDriver.cxx.
References _access_entry_v, _batch_num_entry, _batch_start_entry, _current_entry, _io, _process_entry_(), _processing, larcv::IOManager::get_n_entries(), larcv::IOManager::io_mode(), larcv::IOManager::kWRITE, LARCV_CRITICAL, LARCV_DEBUG, LARCV_NORMAL, LARCV_WARNING, and larcv::IOManager::read_entry().
{
     LARCV_DEBUG() << "Called" << std::endl;
     // Public method to execute num_entries starting from start_entry
     if(!start_entry) start_entry = _batch_start_entry;
     if(!num_entries) num_entries = _batch_num_entry;
     // Check state
     if(!_processing) {
       LARCV_CRITICAL() << "Must call initialize() before start processing!" << std::endl;
       throw larbys();
     }
     // Define the max entry index for processing (1 above last entry to be processed)
     size_t max_entry = start_entry + num_entries;
     // Check if start_entry is 0 for write mode (no entry should be specified for write mode)
     if(_io.io_mode() == IOManager::kWRITE){
       if(start_entry) {
     LARCV_CRITICAL() << "Cannot specify start entry (1st arg) in kWRITE IO mode!" << std::endl;
     throw larbys();
       }
       max_entry = _current_entry + num_entries;
     }else{
       _current_entry = start_entry;
       if(!num_entries) max_entry = start_entry + _io.get_n_entries();
     }
     // Make sure max entry does not exceed the physical max from input. If so, truncate.
     if(_io.io_mode() != IOManager::kWRITE && max_entry > _access_entry_v.size()){
       LARCV_WARNING() << "Requested to process entries from " << start_entry << " to " << max_entry-1
               << " ... but there are only " << _access_entry_v.size() << " entries in input!" << std::endl
               << "Truncating the end entry to " << _access_entry_v.size()-1 << std::endl;
       max_entry = _access_entry_v.size();
     }
     // Batch-execute in while loop
     size_t num_processed=0;
     size_t num_fraction=(max_entry - _current_entry)/10;
     while(_current_entry < max_entry) {
       if(_io.io_mode() != IOManager::kWRITE) {
     //_io.clear_entry();
     _io.read_entry(_access_entry_v[_current_entry]);
       }
       _process_entry_();
       ++num_processed;
       if(!num_fraction) {
     LARCV_NORMAL() << "Processed " << num_processed << " entries..." << std::endl;
       }else if(num_processed%num_fraction==0) {
     LARCV_NORMAL() << "Processed " << 10*int(num_processed/num_fraction) << " %..." << std::endl;
       }
     }
   }
void larcv::ProcessDriver::clear_entry () inline
Definition at line 73 of file ProcessDriver.h.
References _io, and larcv::IOManager::clear_entry().
 {_io.clear_entry();}
void larcv::ProcessDriver::configure (const std::string config_file)
Decodes given configuration text file to create larcv::PSet, then calls the other configure function.
Definition at line 92 of file ProcessDriver.cxx.
References _processing, larcv::CreatePSetFromFile(), LARCV_CRITICAL, LARCV_DEBUG, and larcv::larcv_base::name().
   {
     LARCV_DEBUG() << "Called" << std::endl;
     // check state
     if(_processing) {
       LARCV_CRITICAL() << "Must call finalize() before calling initialize() after starting to process..." << std::endl;
       throw larbys();
     }
     // check cfg file
     if(config_file.empty()) {
       LARCV_CRITICAL() << "Config file not set!" << std::endl;
       throw larbys();
     }
     // check cfg content top level
     auto main_cfg = CreatePSetFromFile(config_file);
     if(!main_cfg.contains_pset(name())) {
       LARCV_CRITICAL() << "ProcessDriver configuration (" << name() << ") not found in the config file (dump below)" << std::endl
                << main_cfg.dump()
                << std::endl;
       throw larbys();
     }
     auto const cfg = main_cfg.get<larcv::PSet>(name());
     configure(cfg);
   }
void larcv::ProcessDriver::configure (const PSet & cfg)
Configure itself (mainly larcv::IOManager) and also attached process modules.
Definition at line 118 of file ProcessDriver.cxx.
References _batch_num_entry, _batch_start_entry, _enable_filter, _fout_name, _has_event_creator, larcv::ProcessBase::_id, _io, _proc_m, _proc_v, _random_access, larcv::PSet::clear(), larcv::PSet::contains_pset(), larcv::ProcessFactory::create(), larcv::PSet::dump(), larcv::ProcessFactory::get(), larcv::PSet::get(), larcv::logger::get_shared(), LARCV_CRITICAL, LARCV_INFO, LARCV_NORMAL, larcv::larcv_base::logger(), larcv::larcv_base::name(), reset(), larcv::logger::set(), and larcv::larcv_base::set_verbosity().
   {
     reset();
     // check io config exists
     LARCV_INFO() << "Retrieving IO config" << std::endl;
     PSet io_config("Empty");
     if(cfg.contains_pset("IOManager"))
       io_config = cfg.get<larcv::PSet>("IOManager");
     else if(cfg.contains_pset(std::string(name() + "IOManager")))
       io_config = cfg.get<larcv::PSet>(name() + "IOManager");
     else {
       LARCV_CRITICAL() << "IOManager config not found!" << std::endl
                << cfg.dump()
                << std::endl;
       throw larbys();
     }
     // check process config exists
     LARCV_INFO() << "Retrieving ProcessList" << std::endl;
     if(!cfg.contains_pset("ProcessList")) {
       LARCV_CRITICAL() << "ProcessList config not found!" << std::endl
                << cfg.dump()
                << std::endl;
       throw larbys();
     }
     auto const proc_config = cfg.get<larcv::PSet>("ProcessList");
     // Prepare IO manager
     LARCV_INFO() << "Configuring IO" << std::endl;
     _io = IOManager(io_config);
     // Set ProcessDriver
     LARCV_INFO() << "Retrieving self (ProcessDriver) config" << std::endl;
     set_verbosity((msg::Level_t)(cfg.get<unsigned short>("Verbosity",logger().level())));
     larcv::logger::get_shared().set(logger().level());
     _enable_filter = cfg.get<bool>("EnableFilter",false);
     auto random_access_bool = cfg.get<bool>("RandomAccess");
     if(!random_access_bool) _random_access = 0;
     else _random_access = -1;
     try{
       auto random_access_int = cfg.get<int>("RandomAccess");
       if(random_access_int!=0) _random_access = random_access_int;
     }catch(...){}
     _fout_name = cfg.get<std::string>("AnaFile","");
     _batch_start_entry = cfg.get<int>("StartEntry",0);
     _batch_num_entry   = cfg.get<int>("NumEntries",0);
     // Process list
     auto process_instance_type_v = cfg.get<std::vector<std::string> >("ProcessType");
     auto process_instance_name_v = cfg.get<std::vector<std::string> >("ProcessName");
     if(process_instance_type_v.size() != process_instance_name_v.size()) {
       LARCV_CRITICAL() << "ProcessType and ProcessName config parameters have different length! "
                << "(" << process_instance_type_v.size() << " vs. " << process_instance_name_v.size() << ")" << std::endl;
       throw larbys();
     }
     LARCV_INFO() << "Start looping process list to instantiate processes" << std::endl;
     for(auto& p : _proc_v) if(p) { delete p; }
     _proc_v.clear();
     _proc_m.clear();
     _has_event_creator=false;
     for(size_t i=0; i<process_instance_type_v.size(); ++i) {
       auto const& name = process_instance_name_v[i];
       auto const& type = process_instance_type_v[i];
       if(_proc_m.find(name) != _proc_m.end()) {
     LARCV_CRITICAL() << "Duplicate Process name found: " << name << std::endl;
     throw larbys("Duplicate algorithm name found!");
       }
       size_t id = _proc_v.size();
       LARCV_NORMAL() << "Instantiating Process ID=" << id << " Type: " << type << " w/ Name: " << name << std::endl;
       /*
       if(!proc_config.contains_pset(name)) {
     LARCV_CRITICAL() << "Could not locate configuration for " << name << std::endl
              << proc_config.dump() << std::endl;
     throw larbys();
       }
       */
       auto ptr = ProcessFactory::get().create(type,name);
       ptr->_id = id;
       ptr->_configure_(proc_config.get_pset(name));
       _proc_m[name] = id;
       if(ptr->event_creator()) {
          if(_has_event_creator) {
            LARCV_CRITICAL() << "Only 1 event creator is allowed to exist!" << std::endl;
            throw larbys();
          }
          if((i+1) != process_instance_type_v.size()) {
            LARCV_CRITICAL() << "Event creator must be set to the last of ProcessList!" << std::endl;
            throw larbys();
          }
          _has_event_creator=true;
       }
       _proc_v.push_back(ptr);
     }
   }
const EventBase& larcv::ProcessDriver::event_id () const inline
Returns larcv::EventBase object that contains an "ID" (run/event integers)
Definition at line 85 of file ProcessDriver.h.
References _io, larcv::IOManager::event_id(), larcv::IOManager::io_mode(), larcv::IOManager::kREAD, and larcv::IOManager::last_event_id().
     { return ( _io.io_mode() == larcv::IOManager::kREAD ? _io.event_id() : _io.last_event_id()); }
void larcv::ProcessDriver::finalize ()
Must be called after initialize() or process_entry/batch_process. Closes IO and calls finalize method of process modules.
Definition at line 422 of file ProcessDriver.cxx.
References _fout, _io, _proc_v, larcv::IOManager::finalize(), LARCV_DEBUG, LARCV_INFO, LARCV_NORMAL, larcv::larcv_base::name(), and reset().
   {
     LARCV_DEBUG() << "called" << std::endl;
     for(auto& p : _proc_v) {
       LARCV_INFO() << "Finalizing: " << p->name() << std::endl;
       if(_fout) _fout->cd();
       p->_fout = _fout;
       p->finalize();
     }
     // Profile repor
     LARCV_INFO() << "Compiling time profile..." << std::endl;
     std::stringstream ss;
     for(auto& p : _proc_v) {
       if(!p->_profile) continue;
       ss << "  \033[93m" << std::setw(20) << std::setfill(' ') << p->name() << "\033[00m"
      << " ... # call " << std::setw(5) << std::setfill(' ') << p->_proc_count
      << " ... total time " << p->_proc_time << " [s]"
      << " ... average time " << p->_proc_time / p->_proc_count << " [s/process]"
      << std::endl;
     }
     std::string msg(ss.str());
     if(!msg.empty())
       LARCV_NORMAL() << "Simple time profiling requested and run..." << std::endl
              << "  ================== " << name() << " Profile Report ==================" << std::endl
              << msg
              << std::endl;
     if(_fout) {
       LARCV_NORMAL() << "Closing analysis output file..." << std::endl;
       _fout->Close();
     }
     LARCV_INFO() << "Finalizing IO..." << std::endl;
     _io.finalize();
     LARCV_INFO() << "Resetting..." << std::endl;
     reset();
   }
size_t larcv::ProcessDriver::get_tree_index (size_t entry) const
When run in random-access IO mode, returns original event entry number for a randomized index number.
Definition at line 463 of file ProcessDriver.cxx.
References _access_entry_v.
{
     if (entry<_access_entry_v.size() )
       return _access_entry_v.at(entry);
     else
       throw larbys();
     return 0;
   }
void larcv::ProcessDriver::initialize ()
Must be called after configure. This initializes larcv::IOManager (open files) and initialize attached process modules.
Definition at line 214 of file ProcessDriver.cxx.
References _access_entry_v, _current_entry, _fout, _fout_name, _io, _proc_v, _processing, _random_access, larcv::IOManager::get_n_entries(), larcv::IOManager::initialize(), larcv::IOManager::io_mode(), larcv::IOManager::kWRITE, LARCV_CRITICAL, LARCV_DEBUG, LARCV_INFO, and LARCV_NORMAL.
   {
     LARCV_DEBUG() << "Called" << std::endl;
     // check state
     if(_processing) {
       LARCV_CRITICAL() << "Must call finalize() before calling initialize() after starting to process..." << std::endl;
       throw larbys();
     }
     // Initialize IO
     LARCV_INFO() << "Initializing IO " << std::endl;
     _io.initialize();
     // Handle invalid cases
     auto const nentries = _io.get_n_entries();
     auto const io_mode  = _io.io_mode();
     // Random access + write mode cannot be combined
     if(_random_access!=0 && io_mode == IOManager::kWRITE) {
       LARCV_CRITICAL() << "Random access mode not supported for kWRITE IO mode!" << std::endl;
       throw larbys();
     }
     // No entries means nothing to do unless write mode
     if(!nentries && io_mode != IOManager::kWRITE) {
       LARCV_CRITICAL() << "No entries found from IO (kREAD/kBOTH mode cannot be run)!" << std::endl;
       throw larbys();
     }
     // Prepare analysis output file if needed
     if(!_fout_name.empty()) {
       LARCV_NORMAL() << "Opening analysis output file " << _fout_name << std::endl;
       _fout = TFile::Open(_fout_name.c_str(),"RECREATE");
     }
     // Initialize process
     for(auto& p : _proc_v) {
       LARCV_INFO() << "Initializing: " << p->name() << std::endl;
       p->initialize();
     }
     // Change state from to-be-initialized to to-process
     _processing = true;
     // Prepare ttree entry index array to follow in execution (randomize if specified
     LARCV_INFO() << "Preparing access index vector" << std::endl;
     if(nentries) {
       _access_entry_v.resize(nentries);
       for(size_t i=0; i<_access_entry_v.size(); ++i) _access_entry_v[i] = i;
       //if(_random_access) std::random_shuffle(_access_entry_v.begin(),_access_entry_v.end());
       if(_random_access!=0) {
     unsigned int seed = 0;
     if(_random_access<0)
       seed = std::chrono::system_clock::now().time_since_epoch().count();
     else
       seed = _random_access;
     std::shuffle(_access_entry_v.begin(), _access_entry_v.end(), std::default_random_engine(seed));
       }
     }
     _current_entry = 0;
   }
const IOManager& larcv::ProcessDriver::io () const inline
Returns read-only larcv::IOManager instance.
Definition at line 96 of file ProcessDriver.h.
References _io.
 { return _io; }
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by configure(), and larcv::larcv_base::name().
     { return *_logger; }
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::ProcessFactory::add_factory(), configure(), larcv::ProcessFactory::create(), finalize(), larcv::IOManager::initialize(), larcv::IOManager::IOManager(), larcv::IOManager::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
void larcv::ProcessDriver::override_ana_file (const std::string fname)
When needs to override the name of output analysis file from what's specified in the configuration.
Definition at line 49 of file ProcessDriver.cxx.
References _fout_name, _processing, LARCV_CRITICAL, and LARCV_DEBUG.
   {
     LARCV_DEBUG() << "Called" << std::endl;
     if(_processing) {
       LARCV_CRITICAL() << "Cannot change ana file name during processing!" << std::endl;
       throw larbys();
     }
     _fout_name = fname;
   }
void larcv::ProcessDriver::override_input_file (const std::vector< std::string > & flist)
When needs to override the list of input files from what's specified in the configuration.
Definition at line 36 of file ProcessDriver.cxx.
References _io, larcv::IOManager::add_in_file(), larcv::IOManager::clear_in_file(), and LARCV_DEBUG.
   {
     LARCV_DEBUG() << "Called" << std::endl;
     _io.clear_in_file();
     for(auto const& f : flist) _io.add_in_file(f);
   }
void larcv::ProcessDriver::override_output_file (const std::string fname)
When needs to override the name of output data file from what's specified in the configuration.
Definition at line 43 of file ProcessDriver.cxx.
References _io, LARCV_DEBUG, and larcv::IOManager::set_out_file().
   {
     LARCV_DEBUG() << "Called" << std::endl;
     _io.set_out_file(fname);
   }
bool larcv::ProcessDriver::process_entry ()
Processes the "next entry" automatically (you don't have to control the counter to specify which entry)
Definition at line 312 of file ProcessDriver.cxx.
References _access_entry_v, _current_entry, _io, _process_entry_(), _processing, larcv::IOManager::io_mode(), larcv::IOManager::kWRITE, LARCV_CRITICAL, LARCV_DEBUG, LARCV_NORMAL, and larcv::IOManager::read_entry().
   {
     LARCV_DEBUG() << "Called" << std::endl;
     // Public method to process "next" entry
     // Check state
     if(!_processing) {
       LARCV_CRITICAL() << "Must call initialize() before start processing!" << std::endl;
       throw larbys();
     }
     // Check if input entry exists in case of read/both io mode
     if(_io.io_mode() != IOManager::kWRITE) {
       if(_access_entry_v.size() <= _current_entry) {
     LARCV_NORMAL() << "Entry " << _current_entry << " exceeds available events in a file!" << std::endl;
     return false;
       }
       // if exist then move read pointer
       //_io.clear_entry();
       _io.read_entry(_access_entry_v[_current_entry]);
     }
     // Execute processes
     return _process_entry_();
   }
bool larcv::ProcessDriver::process_entry (size_t entry, bool force_reload = false)
Processes a specific entry specified in the argument.
If calling this function with the same entry twice, the 2nd bloolean can be used to force re-loading data from disk.
Definition at line 338 of file ProcessDriver.cxx.
References _access_entry_v, _current_entry, _io, _process_entry_(), _processing, larcv::IOManager::io_mode(), larcv::IOManager::kWRITE, LARCV_CRITICAL, LARCV_DEBUG, LARCV_ERROR, and larcv::IOManager::read_entry().
   {
     LARCV_DEBUG() << "Called" << std::endl;
     // Public method to process "specified" entry
     // Check state
     if(!_processing) {
       LARCV_CRITICAL() << "Must call initialize() before start processing!" << std::endl;
       throw larbys();
     }
     // Check if input entry exists in case of read/both io mode
     if(_io.io_mode() != IOManager::kWRITE) {
       if(_access_entry_v.size() <= entry) {
     LARCV_ERROR() << "Entry " << entry << " exceeds available events in a file!" << std::endl;
     return false;
       }
       // if exist then move read pointer
       //_io.clear_entry();
       _io.read_entry(_access_entry_v[entry],force_reload);
       _current_entry = entry;
     }
     // Execute processes
     return _process_entry_();
   }
ProcessID_t larcv::ProcessDriver::process_id (std::string name) const
Returns a unique ID (integer) assigned for a process module (provide the module's name in argument)
Definition at line 59 of file ProcessDriver.cxx.
References _proc_m, LARCV_CRITICAL, and LARCV_DEBUG.
   {
     LARCV_DEBUG() << "Called" << std::endl;
     auto iter = _proc_m.find(name);
     if(iter == _proc_m.end()) {
       LARCV_CRITICAL() << "Process w/ name " << name << " not found..." << std::endl;
       throw larbys();
     }
     return (*iter).second;
   }
const std::map< std::string, larcv::ProcessID_t > & larcv::ProcessDriver::process_map () const
Returns a mapping between process modules' name and their unique process ID number.
Definition at line 79 of file ProcessDriver.cxx.
References _proc_m, and LARCV_DEBUG.
   { LARCV_DEBUG() << "Called" << std::endl; return _proc_m; }
std::vector< std::string > larcv::ProcessDriver::process_names () const
Returns the set of process modules' name.
Definition at line 70 of file ProcessDriver.cxx.
References _proc_m, and LARCV_DEBUG.
   {
     LARCV_DEBUG() << "Called" << std::endl;
     std::vector<std::string> res;
     res.reserve(_proc_m.size());
     for(auto const& name_id : _proc_m) res.push_back(name_id.first);
     return res;
   }
const ProcessBase * larcv::ProcessDriver::process_ptr (ProcessID_t id) const
Returns an attached process module's pointer given a unique ID in the argument.
Definition at line 82 of file ProcessDriver.cxx.
References _proc_v, LARCV_CRITICAL, and LARCV_DEBUG.
   {
     LARCV_DEBUG() << "Called" << std::endl;
     if(id >= _proc_v.size()) {
       LARCV_CRITICAL() << "Invalid ID requested: " << id << std::endl;
       throw larbys();
     }
     return _proc_v[id];
   }
bool larcv::ProcessDriver::processing () const inline
Returns true if after any entry is processed (process_entry/batch_process) but not yet finalized.
Definition at line 100 of file ProcessDriver.h.
References _processing.
 { return _processing; }
void larcv::ProcessDriver::random_access (int flag) inline
When needs to override the randomized event access in IO from what's specified in the configuration.
Definition at line 52 of file ProcessDriver.h.
References _random_access.
 { _random_access = flag; }
void larcv::ProcessDriver::reset ()
Resets the states & all variables. Attached process modules would be removed.
Definition at line 23 of file ProcessDriver.cxx.
References _enable_filter, _fout, _fout_name, _io, _proc_v, _processing, _random_access, LARCV_DEBUG, and larcv::IOManager::reset().
Referenced by configure(), and finalize().
   {
     LARCV_DEBUG() << "Called" << std::endl;
     _io.reset();
     _enable_filter = false;
     _random_access = 0;
     for(size_t i=0; i<_proc_v.size(); ++i) { delete _proc_v[i]; _proc_v[i]=nullptr; }
     _proc_v.clear();
     _processing = false;
     _fout = nullptr;
     _fout_name = "";
   }
void larcv::ProcessDriver::set_id (size_t run, size_t subrun, size_t event) inline
A method to force re-set the run/subrun/event ID of a currently processed event, useful when "creating an event".
Definition at line 79 of file ProcessDriver.h.
References _io, and larcv::IOManager::set_id().
     { _io.set_id(run,subrun,event); }
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), configure(), and larcv::IOManager::configure().
     { _logger->set(level); }
Member Data Documentation
std::vector<size_t> larcv::ProcessDriver::_access_entry_v private
Definition at line 111 of file ProcessDriver.h.
Referenced by batch_process(), get_tree_index(), initialize(), and process_entry().
size_t larcv::ProcessDriver::_batch_num_entry private
Definition at line 107 of file ProcessDriver.h.
Referenced by batch_process(), and configure().
size_t larcv::ProcessDriver::_batch_start_entry private
Definition at line 106 of file ProcessDriver.h.
Referenced by batch_process(), and configure().
size_t larcv::ProcessDriver::_current_entry private
Definition at line 108 of file ProcessDriver.h.
Referenced by _process_entry_(), batch_process(), initialize(), and process_entry().
bool larcv::ProcessDriver::_enable_filter private
Definition at line 109 of file ProcessDriver.h.
Referenced by _process_entry_(), configure(), and reset().
TFile* larcv::ProcessDriver::_fout private
Definition at line 116 of file ProcessDriver.h.
Referenced by finalize(), initialize(), and reset().
std::string larcv::ProcessDriver::_fout_name private
Definition at line 117 of file ProcessDriver.h.
Referenced by configure(), initialize(), override_ana_file(), and reset().
bool larcv::ProcessDriver::_has_event_creator private
Definition at line 118 of file ProcessDriver.h.
Referenced by _process_entry_(), and configure().
IOManager larcv::ProcessDriver::_io private
Definition at line 112 of file ProcessDriver.h.
Referenced by _process_entry_(), batch_process(), clear_entry(), configure(), event_id(), finalize(), initialize(), io(), override_input_file(), override_output_file(), process_entry(), reset(), and set_id().
std::map<std::string,larcv::ProcessID_t> larcv::ProcessDriver::_proc_m private
Definition at line 113 of file ProcessDriver.h.
Referenced by configure(), process_id(), process_map(), and process_names().
std::vector<larcv::ProcessBase*> larcv::ProcessDriver::_proc_v private
Definition at line 114 of file ProcessDriver.h.
Referenced by _process_entry_(), configure(), finalize(), initialize(), process_ptr(), and reset().
bool larcv::ProcessDriver::_processing private
Definition at line 115 of file ProcessDriver.h.
Referenced by batch_process(), configure(), initialize(), override_ana_file(), process_entry(), processing(), and reset().
int larcv::ProcessDriver::_random_access private
Definition at line 110 of file ProcessDriver.h.
Referenced by configure(), initialize(), random_access(), and reset().
The documentation for this class was generated from the following files:
ProcessDriver.h
ProcessDriver.cxx