LArCV: larcv::EventImage2D Class Reference
larcv::EventImage2D Class Reference
Event-wise class to store a collection of larcv::Image2D.
#include <EventImage2D.h>
Public Member Functions
EventImage2D ()
Default constructor.
virtual ~EventImage2D ()
Default destructor.
void clear ()
Clears an array of larcv::Image2D.
const std::vector
< larcv::Image2D > & as_vector () const
Const reference getter to an array of larcv::Image2D.
const std::vector
< larcv::Image2D > & image2d_array () const
Deprecated (use as_vector): const reference getter to an array of larcv::Image2D.
const Image2D & at (ImageIndex_t id) const
larcv::Image2D const reference getter for a specified index number
void append (const Image2D &img)
Inserter into larcv::Image2D array.
void emplace (Image2D &&img)
Emplace into larcv::Image2D array.
void emplace (std::vector< larcv::Image2D > &&image_v)
Emplace into larcv::Image2D array.
void move (std::vector< larcv::Image2D > &image_v)
std::move to retrieve content larcv::Image2D array
const std::string & producer () const
Producer name getter.
size_t run () const
Run number getter.
size_t subrun () const
SubRun number getter.
size_t event () const
Event number getter.
bool valid () const
Make sure run/subrun/event ID is set.
bool operator== (const EventBase &rhs) const
Comparison opearator for run/subrun/event id.
bool operator!= (const EventBase &rhs) const
Comparison opearator for run/subrun/event id.
bool operator< (const EventBase &rhs) const
Comparison opearator for run/subrun/event id (for sorted container like std::set and/or std::map)
std::string event_key () const
Formatted string key getter (a string key consists of 0-padded run, subrun, and event id)
void set_id (const size_t run, const size_t subrun, const size_t event)
Setting the id.
Private Attributes
std::vector< larcv::Image2D > _image_v
Detailed Description
Event-wise class to store a collection of larcv::Image2D.
A concrete factory class for larcv::EventImage2D.
Definition at line 27 of file EventImage2D.h.
Constructor & Destructor Documentation
larcv::EventImage2D::EventImage2D () inline
Default constructor.
Definition at line 32 of file EventImage2D.h.
 {}
virtual larcv::EventImage2D::~EventImage2D () inline virtual
Default destructor.
Definition at line 35 of file EventImage2D.h.
 {}
Member Function Documentation
void larcv::EventImage2D::append (const Image2D & img)
Inserter into larcv::Image2D array.
Definition at line 24 of file EventImage2D.cxx.
References _image_v.
   {
     _image_v.push_back(img);
     _image_v.back().index((ImageIndex_t)(_image_v.size()-1));
   }
const std::vector<larcv::Image2D>& larcv::EventImage2D::as_vector () const inline
Const reference getter to an array of larcv::Image2D.
Definition at line 41 of file EventImage2D.h.
References _image_v.
 { return _image_v; }
const Image2D & larcv::EventImage2D::at (ImageIndex_t id) const
larcv::Image2D const reference getter for a specified index number
Definition at line 18 of file EventImage2D.cxx.
References _image_v.
   {
     if( id >= _image_v.size() ) throw larbys("Invalid request (ImageIndex_t out-o-range)!");
     return _image_v[id];
   }
void larcv::EventImage2D::clear () virtual
Clears an array of larcv::Image2D.
Reimplemented from larcv::EventBase.
Definition at line 12 of file EventImage2D.cxx.
References _image_v, and larcv::EventBase::clear().
   {
     EventBase::clear();
     _image_v.clear();
   }
void larcv::EventImage2D::emplace (Image2D && img)
Emplace into larcv::Image2D array.
Definition at line 30 of file EventImage2D.cxx.
References _image_v.
   {
     _image_v.emplace_back(std::move(img));
     _image_v.back().index((ImageIndex_t)(_image_v.size()-1));
   }
void larcv::EventImage2D::emplace (std::vector< larcv::Image2D > && image_v)
Emplace into larcv::Image2D array.
Definition at line 36 of file EventImage2D.cxx.
References _image_v.
   {
     _image_v = std::move(image_v);
     for(size_t i=0; i<_image_v.size(); ++i) _image_v[i].index((ImageIndex_t)i);
   }
size_t larcv::EventBase::event () const inline inherited
Event number getter.
Definition at line 56 of file EventBase.h.
References larcv::EventBase::_event.
Referenced by larcv::IOManager::clear_entry(), larcv::IOManager::get_data(), larcv::EventBase::operator<(), larcv::EventBase::operator==(), larcv::IOManager::register_producer(), larcv::EventBase::set_id(), and larcv::IOManager::set_id().
 { return _event;  }
std::string larcv::EventBase::event_key () const inherited
Formatted string key getter (a string key consists of 0-padded run, subrun, and event id)
Definition at line 13 of file EventBase.cxx.
References larcv::EventBase::_event, larcv::EventBase::_run, and larcv::EventBase::_subrun.
Referenced by larcv::IOManager::set_id().
   {
     std::stringstream ss;
     ss << std::setw( 7 ) << std::setfill( '0' ) << _run << "_"
        << std::setw( 5 ) << std::setfill( '0' ) << _subrun << "_"
        << std::setw( 6 ) << std::setfill( '0' ) << _event;
     return ss.str();
   }
const std::vector<larcv::Image2D>& larcv::EventImage2D::image2d_array () const inline
Deprecated (use as_vector): const reference getter to an array of larcv::Image2D.
Definition at line 44 of file EventImage2D.h.
References _image_v.
 { return _image_v; }
void larcv::EventImage2D::move (std::vector< larcv::Image2D > & image_v) inline
std::move to retrieve content larcv::Image2D array
Definition at line 57 of file EventImage2D.h.
References _image_v.
     { image_v = std::move(_image_v); }
bool larcv::EventBase::operator!= (const EventBase & rhs) const inline inherited
Comparison opearator for run/subrun/event id.
Definition at line 64 of file EventBase.h.
     { return !((*this) == rhs); }
bool larcv::EventBase::operator< (const EventBase & rhs) const inline inherited
Comparison opearator for run/subrun/event id (for sorted container like std::set and/or std::map)
Definition at line 67 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, larcv::EventBase::event(), larcv::EventBase::run(), and larcv::EventBase::subrun().
     {
       if(_run < rhs.run()) return true;
       if(_run > rhs.run()) return false;
       if(_subrun < rhs.subrun()) return true;
       if(_subrun > rhs.subrun()) return false;
       if(_event < rhs.event()) return true;
       if(_event > rhs.event()) return false;
       return false;
     }
bool larcv::EventBase::operator== (const EventBase & rhs) const inline inherited
Comparison opearator for run/subrun/event id.
Definition at line 61 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, larcv::EventBase::event(), larcv::EventBase::run(), and larcv::EventBase::subrun().
     { return (_run == rhs.run() && _subrun == rhs.subrun() && _event == rhs.event()); }
const std::string& larcv::EventBase::producer () const inline inherited
Producer name getter.
Definition at line 50 of file EventBase.h.
References larcv::EventBase::_producer.
 { return _producer; }
size_t larcv::EventBase::run () const inline inherited
Run number getter.
Definition at line 52 of file EventBase.h.
References larcv::EventBase::_run.
Referenced by larcv::IOManager::clear_entry(), larcv::IOManager::get_data(), larcv::EventBase::operator<(), larcv::EventBase::operator==(), larcv::IOManager::register_producer(), larcv::EventBase::set_id(), and larcv::IOManager::set_id().
 { return _run;    }
void larcv::EventBase::set_id (const size_t run, const size_t subrun, const size_t event) inline inherited
Setting the id.
Definition at line 82 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, larcv::EventBase::event(), larcv::EventBase::run(), and larcv::EventBase::subrun().
Referenced by larcv::IOManager::get_data().
     { _run = run; _subrun = subrun; _event = event; }
size_t larcv::EventBase::subrun () const inline inherited
SubRun number getter.
Definition at line 54 of file EventBase.h.
References larcv::EventBase::_subrun.
Referenced by larcv::IOManager::clear_entry(), larcv::IOManager::get_data(), larcv::EventBase::operator<(), larcv::EventBase::operator==(), larcv::IOManager::register_producer(), larcv::EventBase::set_id(), and larcv::IOManager::set_id().
 { return _subrun; }
bool larcv::EventBase::valid () const inline inherited
Make sure run/subrun/event ID is set.
Definition at line 58 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, and larcv::kINVALID_SIZE.
Referenced by larcv::IOManager::clear_entry(), larcv::IOManager::event_id(), larcv::IOManager::get_data(), larcv::IOManager::register_producer(), and larcv::IOManager::set_id().
     { return !(_run == kINVALID_SIZE || _subrun == kINVALID_SIZE || _event == kINVALID_SIZE); }
Member Data Documentation
std::vector<larcv::Image2D> larcv::EventImage2D::_image_v private
Definition at line 63 of file EventImage2D.h.
Referenced by append(), as_vector(), at(), clear(), emplace(), image2d_array(), and move().
The documentation for this class was generated from the following files:
EventImage2D.h
EventImage2D.cxx