LArCV: larcv::EventBBox2D Class Reference
larcv::EventBBox2D Class Reference
Event-wise class to store a collection of larcv::BBox.
#include <EventBBox.h>
Public Member Functions
EventBBox2D ()
Default constructor.
~EventBBox2D ()
Default destructor.
void clear ()
larcv::BBox2D array clearer
const std::string & producer () const
Producer name getter.
size_t run () const
Run number getter.
size_t subrun () const
SubRun number getter.
size_t event () const
Event number getter.
bool valid () const
Make sure run/subrun/event ID is set.
bool operator== (const EventBase &rhs) const
Comparison opearator for run/subrun/event id.
bool operator!= (const EventBase &rhs) const
Comparison opearator for run/subrun/event id.
bool operator< (const EventBase &rhs) const
Comparison opearator for run/subrun/event id (for sorted container like std::set and/or std::map)
std::string event_key () const
Formatted string key getter (a string key consists of 0-padded run, subrun, and event id)
void set_id (const size_t run, const size_t subrun, const size_t event)
Setting the id.
Public Attributes
DistanceUnit_t unit
Units.
std::string info
Description (optional)
T elements
STL member.
Detailed Description
Event-wise class to store a collection of larcv::BBox.
A concrete factory class for larcv::EventBBox2D.
Definition at line 27 of file EventBBox.h.
Constructor & Destructor Documentation
larcv::EventBBox2D::EventBBox2D () inline
Default constructor.
Definition at line 33 of file EventBBox.h.
 {}
larcv::EventBBox2D::~EventBBox2D () inline
Default destructor.
Definition at line 36 of file EventBBox.h.
 {}
Member Function Documentation
void larcv::EventBBox2D::clear () inline virtual
larcv::BBox2D array clearer
Reimplemented from larcv::EventBase.
Definition at line 39 of file EventBBox.h.
References larcv::EventBase::clear().
     { EventBase::clear(); std::vector<larcv::BBox2D>::clear(); }
size_t larcv::EventBase::event () const inline inherited
Event number getter.
Definition at line 56 of file EventBase.h.
References larcv::EventBase::_event.
Referenced by larcv::IOManager::clear_entry(), larcv::IOManager::get_data(), larcv::EventBase::operator<(), larcv::EventBase::operator==(), larcv::IOManager::register_producer(), larcv::EventBase::set_id(), and larcv::IOManager::set_id().
 { return _event;  }
std::string larcv::EventBase::event_key () const inherited
Formatted string key getter (a string key consists of 0-padded run, subrun, and event id)
Definition at line 13 of file EventBase.cxx.
References larcv::EventBase::_event, larcv::EventBase::_run, and larcv::EventBase::_subrun.
Referenced by larcv::IOManager::set_id().
   {
     std::stringstream ss;
     ss << std::setw( 7 ) << std::setfill( '0' ) << _run << "_"
        << std::setw( 5 ) << std::setfill( '0' ) << _subrun << "_"
        << std::setw( 6 ) << std::setfill( '0' ) << _event;
     return ss.str();
   }
bool larcv::EventBase::operator!= (const EventBase & rhs) const inline inherited
Comparison opearator for run/subrun/event id.
Definition at line 64 of file EventBase.h.
     { return !((*this) == rhs); }
bool larcv::EventBase::operator< (const EventBase & rhs) const inline inherited
Comparison opearator for run/subrun/event id (for sorted container like std::set and/or std::map)
Definition at line 67 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, larcv::EventBase::event(), larcv::EventBase::run(), and larcv::EventBase::subrun().
     {
       if(_run < rhs.run()) return true;
       if(_run > rhs.run()) return false;
       if(_subrun < rhs.subrun()) return true;
       if(_subrun > rhs.subrun()) return false;
       if(_event < rhs.event()) return true;
       if(_event > rhs.event()) return false;
       return false;
     }
bool larcv::EventBase::operator== (const EventBase & rhs) const inline inherited
Comparison opearator for run/subrun/event id.
Definition at line 61 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, larcv::EventBase::event(), larcv::EventBase::run(), and larcv::EventBase::subrun().
     { return (_run == rhs.run() && _subrun == rhs.subrun() && _event == rhs.event()); }
const std::string& larcv::EventBase::producer () const inline inherited
Producer name getter.
Definition at line 50 of file EventBase.h.
References larcv::EventBase::_producer.
 { return _producer; }
size_t larcv::EventBase::run () const inline inherited
Run number getter.
Definition at line 52 of file EventBase.h.
References larcv::EventBase::_run.
Referenced by larcv::IOManager::clear_entry(), larcv::IOManager::get_data(), larcv::EventBase::operator<(), larcv::EventBase::operator==(), larcv::IOManager::register_producer(), larcv::EventBase::set_id(), and larcv::IOManager::set_id().
 { return _run;    }
void larcv::EventBase::set_id (const size_t run, const size_t subrun, const size_t event) inline inherited
Setting the id.
Definition at line 82 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, larcv::EventBase::event(), larcv::EventBase::run(), and larcv::EventBase::subrun().
Referenced by larcv::IOManager::get_data().
     { _run = run; _subrun = subrun; _event = event; }
size_t larcv::EventBase::subrun () const inline inherited
SubRun number getter.
Definition at line 54 of file EventBase.h.
References larcv::EventBase::_subrun.
Referenced by larcv::IOManager::clear_entry(), larcv::IOManager::get_data(), larcv::EventBase::operator<(), larcv::EventBase::operator==(), larcv::IOManager::register_producer(), larcv::EventBase::set_id(), and larcv::IOManager::set_id().
 { return _subrun; }
bool larcv::EventBase::valid () const inline inherited
Make sure run/subrun/event ID is set.
Definition at line 58 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, and larcv::kINVALID_SIZE.
Referenced by larcv::IOManager::clear_entry(), larcv::IOManager::event_id(), larcv::IOManager::get_data(), larcv::IOManager::register_producer(), and larcv::IOManager::set_id().
     { return !(_run == kINVALID_SIZE || _subrun == kINVALID_SIZE || _event == kINVALID_SIZE); }
Member Data Documentation
T std::vector< T >::elements inherited
STL member.
std::string larcv::EventBBox2D::info
Description (optional)
Definition at line 46 of file EventBBox.h.
DistanceUnit_t larcv::EventBBox2D::unit
Units.
Definition at line 43 of file EventBBox.h.
The documentation for this class was generated from the following file:
EventBBox.h