LArCV: larcv::Particle Class Reference
larcv::Particle Class Reference
Particle/Interaction-wise truth information data.
#include <Particle.h>
Public Member Functions
Particle (larcv::ShapeType_t shape=larcv::kShapeUnknown)
Default constructor.
~Particle ()
Default destructor.
ParticleIndex_t id () const
particle's ID getter
ShapeType_t shape () const
MCSTIndex_t mcst_index () const
MCTIndex_t mct_index () const
short nu_current_type () const
short nu_interaction_type () const
unsigned int track_id () const
int pdg_code () const
double px () const
double py () const
double pz () const
const larcv::Vertex & position () const
double x () const
double y () const
double z () const
double t () const
const larcv::Vertex & end_position () const
const larcv::Vertex & first_step () const
const larcv::Vertex & last_step () const
double distance_travel () const
double energy_init () const
double energy_deposit () const
const std::string & creation_process () const
const BBox2D & boundingbox_2d (ProjectionID_t id) const
const std::vector
< larcv::BBox2D > & boundingbox_2d () const
const BBox3D & boundingbox_3d () const
unsigned int parent_track_id () const
int parent_pdg_code () const
const larcv::Vertex & parent_position () const
double parent_x () const
double parent_y () const
double parent_z () const
double parent_t () const
unsigned int ancestor_track_id () const
int ancestor_pdg_code () const
const larcv::Vertex & ancestor_position () const
double ancestor_x () const
double ancestor_y () const
double ancestor_z () const
double ancestor_t () const
void id (InstanceID_t id)
void mcst_index (MCSTIndex_t id)
void mct_index (MCTIndex_t id)
void shape (ShapeType_t shape)
void nu_current_type (short curr)
void nu_interaction_type (short itype)
void track_id (unsigned int id)
void pdg_code (int code)
void momentum (double px, double py, double pz)
void position (const larcv::Vertex &vtx)
void position (double x, double y, double z, double t)
void end_position (const larcv::Vertex &vtx)
void end_position (double x, double y, double z, double t)
void first_step (const larcv::Vertex &vtx)
void first_step (double x, double y, double z, double t)
void last_step (const larcv::Vertex &vtx)
void last_step (double x, double y, double z, double t)
void distance_travel (double dist)
void energy_init (double e)
void energy_deposit (double e)
void creation_process (const std::string &proc)
void boundingbox_2d (const std::vector< larcv::BBox2D > &bb_v)
void boundingbox_2d (const BBox2D &bb, ProjectionID_t id)
void boundingbox_3d (const BBox3D &bb)
void parent_track_id (unsigned int id)
void parent_pdg_code (int code)
void parent_position (const larcv::Vertex &vtx)
void parent_position (double x, double y, double z, double t)
void ancestor_track_id (unsigned int id)
void ancestor_pdg_code (int code)
void ancestor_position (const larcv::Vertex &vtx)
void ancestor_position (double x, double y, double z, double t)
std::string dump () const
Private Attributes
InstanceID_t _id
"ID" of this particle
MCSTIndex_t _mcst_index
index number in the origin MCShower/MCTrack container array (kINVALID_USHORT if neither)
MCTIndex_t _mct_index
ShapeType_t _shape
shows if it is (e+/e-/gamma) or other particle types
short _current_type
if neutrino, shows interaction GENIE current type. else kINVALID_USHORT
short _interaction_type
if neutrino, shows interaction GENIE code. else kINVALID_USHORT
unsigned int _trackid
Geant4 track id.
int _pdg
PDG code.
double _px
double _py
double _pz
(x,y,z) component of particle's initial momentum
Vertex _vtx
(x,y,z,t) of particle's vertex information
Vertex _end_pt
(x,y,z,t) at which particle disappeared from G4WorldVolume
Vertex _first_step
(x,y,z,t) of the first energy deposition point in the detector
Vertex _last_step
(x,y,z,t) of the last energy deposition point in the detector
double _dist_travel
filled only if MCTrack origin: distance measured along the trajectory
double _energy_init
initial energy of the particle
double _energy_deposit
deposited energy of the particle in the detector
std::string _process
string identifier of the particle's creation process from Geant4
std::vector< larcv::BBox2D > _bb2d_v
bounding box of particle's trajectory in 2D projections. index = ProjectionID_t
larcv::BBox3D _bb3d
bounding box of particle's trajectory in 3D
unsigned int _parent_trackid
Geant4 track id of the parent particle.
int _parent_pdg
PDG code of the parent particle.
Vertex _parent_vtx
(x,y,z,t) of parent's vertex information
unsigned int _ancestor_trackid
Geant4 track id of the ancestor particle.
int _ancestor_pdg
PDG code of the ancestor particle.
Vertex _ancestor_vtx
(x,y,z,t) of ancestor's vertex information
Detailed Description
Particle/Interaction-wise truth information data.
Definition at line 27 of file Particle.h.
Constructor & Destructor Documentation
larcv::Particle::Particle (larcv::ShapeType_t shape = larcv::kShapeUnknown) inline
Default constructor.
Definition at line 32 of file Particle.h.
       : _id         (kINVALID_INDEX)
       , _mcst_index (kINVALID_INDEX)
       , _mct_index  (kINVALID_INDEX)
       , _shape      (shape)
       , _current_type     (-1)
       , _interaction_type (-1)
       , _trackid          (kINVALID_UINT)
       , _pdg              (0)
       , _px               (0.)
       , _py               (0.)
       , _pz               (0.)
       , _dist_travel      (-1)
       , _energy_init      (0.)
       , _energy_deposit   (0.)
       , _process          ("")
       , _parent_trackid   (kINVALID_UINT)
       , _parent_pdg       (0)
       , _ancestor_trackid (kINVALID_UINT)
       , _ancestor_pdg     (0)
     {}
larcv::Particle::~Particle () inline
Default destructor.
Definition at line 55 of file Particle.h.
 {}
Member Function Documentation
int larcv::Particle::ancestor_pdg_code () const inline
Definition at line 97 of file Particle.h.
References _ancestor_pdg.
 { return _ancestor_pdg;     }
void larcv::Particle::ancestor_pdg_code (int code) inline
Definition at line 141 of file Particle.h.
References _ancestor_pdg.
 { _ancestor_pdg = code;  }
const larcv::Vertex& larcv::Particle::ancestor_position () const inline
Definition at line 98 of file Particle.h.
References _ancestor_vtx.
 { return _ancestor_vtx;}
void larcv::Particle::ancestor_position (const larcv::Vertex & vtx) inline
Definition at line 142 of file Particle.h.
References _ancestor_vtx.
 { _ancestor_vtx = vtx; }
void larcv::Particle::ancestor_position (double x, double y, double z, double t) inline
Definition at line 143 of file Particle.h.
References _ancestor_vtx.
 { _ancestor_vtx = Vertex(x,y,z,t); }
double larcv::Particle::ancestor_t () const inline
Definition at line 102 of file Particle.h.
References _ancestor_vtx, and larcv::Vertex::t().
 { return _ancestor_vtx.t(); }
unsigned int larcv::Particle::ancestor_track_id () const inline
Definition at line 96 of file Particle.h.
References _ancestor_trackid.
 { return _ancestor_trackid; }
void larcv::Particle::ancestor_track_id (unsigned int id) inline
Definition at line 140 of file Particle.h.
References _ancestor_trackid, and id().
 { _ancestor_trackid = id;}
double larcv::Particle::ancestor_x () const inline
Definition at line 99 of file Particle.h.
References _ancestor_vtx, and larcv::Vertex::x().
 { return _ancestor_vtx.x(); }
double larcv::Particle::ancestor_y () const inline
Definition at line 100 of file Particle.h.
References _ancestor_vtx, and larcv::Vertex::y().
 { return _ancestor_vtx.y(); }
double larcv::Particle::ancestor_z () const inline
Definition at line 101 of file Particle.h.
References _ancestor_vtx, and larcv::Vertex::z().
 { return _ancestor_vtx.z(); }
const BBox2D & larcv::Particle::boundingbox_2d (ProjectionID_t id) const
Definition at line 10 of file Particle.cxx.
References _bb2d_v.
   {
     std::stringstream ss;
     if(id < _bb2d_v.size()) return _bb2d_v[id];
     ss << "BBox2D not stored for ProjectionID_t " << id << std::endl;
     throw larbys(ss.str());
   }
const std::vector<larcv::BBox2D>& larcv::Particle::boundingbox_2d () const inline
Definition at line 83 of file Particle.h.
References _bb2d_v.
 { return _bb2d_v; }
void larcv::Particle::boundingbox_2d (const std::vector< larcv::BBox2D > & bb_v) inline
Definition at line 130 of file Particle.h.
References _bb2d_v.
 { _bb2d_v = bb_v; }
void larcv::Particle::boundingbox_2d (const BBox2D & bb, ProjectionID_t id) inline
Definition at line 131 of file Particle.h.
References _bb2d_v, and id().
 { _bb2d_v.resize(id+1); _bb2d_v[id] = bb; }
const BBox3D& larcv::Particle::boundingbox_3d () const inline
Definition at line 84 of file Particle.h.
References _bb3d.
 { return _bb3d; }
void larcv::Particle::boundingbox_3d (const BBox3D & bb) inline
Definition at line 132 of file Particle.h.
References _bb3d.
 { _bb3d = bb; }
const std::string& larcv::Particle::creation_process () const inline
Definition at line 81 of file Particle.h.
References _process.
Referenced by dump().
 { return _process; }
void larcv::Particle::creation_process (const std::string & proc) inline
Definition at line 129 of file Particle.h.
References _process.
 { _process = proc; }
double larcv::Particle::distance_travel () const inline
Definition at line 78 of file Particle.h.
References _dist_travel.
 { return _dist_travel;     }
void larcv::Particle::distance_travel (double dist) inline
Definition at line 126 of file Particle.h.
References _dist_travel.
 { _dist_travel = dist; }
std::string larcv::Particle::dump () const
Definition at line 18 of file Particle.cxx.
References _bb2d_v, _bb3d, creation_process(), larcv::BBox3D::dump(), energy_deposit(), energy_init(), parent_pdg_code(), parent_track_id(), pdg_code(), px(), py(), pz(), t(), track_id(), x(), y(), and z().
   {
     std::stringstream ss;
     std::stringstream buf;
     ss  << "      \033[95m" << "Particle " << " (PdgCode,TrackID) = (" << pdg_code() << "," << track_id() << ")\033[00m "
     << "... with Parent (" << parent_pdg_code() << "," << parent_track_id() << ")" << std::endl;
     buf << "      ";
     ss << buf.str() << "Vertex   (x, y, z, t) = (" << x() << "," << y() << "," << z() << "," << t() << ")" << std::endl
        << buf.str() << "Momentum (px, py, pz) = (" << px() << "," << py() << "," << pz() << ")" << std::endl
        << buf.str() << "Inittial Energy  = " << energy_init() << std::endl
        << buf.str() << "Deposit  Energy  = " << energy_deposit() << std::endl
        << buf.str() << "Creation Process = " << creation_process() << std::endl;
     ss << buf.str() << "BBox3D: " << _bb3d.dump();
     buf << "    ";
     for(size_t i=0; i<_bb2d_v.size(); ++i)
       ss << buf.str() << "Plane " << i << " BBox2D: " << _bb2d_v[i].dump();
     return ss.str();
   }
const larcv::Vertex& larcv::Particle::end_position () const inline
Definition at line 75 of file Particle.h.
References _end_pt.
 { return _end_pt;     }
void larcv::Particle::end_position (const larcv::Vertex & vtx) inline
Definition at line 120 of file Particle.h.
References _end_pt.
 { _end_pt = vtx; }
void larcv::Particle::end_position (double x, double y, double z, double t) inline
Definition at line 121 of file Particle.h.
References _end_pt.
 { _end_pt = Vertex(x,y,z,t); }
double larcv::Particle::energy_deposit () const inline
Definition at line 80 of file Particle.h.
References _energy_deposit.
Referenced by dump().
 { return _energy_deposit;  }
void larcv::Particle::energy_deposit (double e) inline
Definition at line 128 of file Particle.h.
References _energy_deposit.
 { _energy_deposit = e; }
double larcv::Particle::energy_init () const inline
Definition at line 79 of file Particle.h.
References _energy_init.
Referenced by dump().
 { return _energy_init;     }
void larcv::Particle::energy_init (double e) inline
Definition at line 127 of file Particle.h.
References _energy_init.
 { _energy_init = e;    }
const larcv::Vertex& larcv::Particle::first_step () const inline
Definition at line 76 of file Particle.h.
References _first_step.
 { return _first_step; }
void larcv::Particle::first_step (const larcv::Vertex & vtx) inline
Definition at line 122 of file Particle.h.
References _first_step.
 { _first_step = vtx; }
void larcv::Particle::first_step (double x, double y, double z, double t) inline
Definition at line 123 of file Particle.h.
References _first_step.
 { _first_step = Vertex(x,y,z,t); }
ParticleIndex_t larcv::Particle::id () const inline
particle's ID getter
Definition at line 57 of file Particle.h.
References _id.
Referenced by ancestor_track_id(), boundingbox_2d(), mcst_index(), mct_index(), parent_track_id(), and track_id().
 { return _id;         }
void larcv::Particle::id (InstanceID_t id) inline
Definition at line 108 of file Particle.h.
References _id, and id().
Referenced by id().
 { _id = id;         }
const larcv::Vertex& larcv::Particle::last_step () const inline
Definition at line 77 of file Particle.h.
References _last_step.
 { return _last_step;  }
void larcv::Particle::last_step (const larcv::Vertex & vtx) inline
Definition at line 124 of file Particle.h.
References _last_step.
 { _last_step = vtx; }
void larcv::Particle::last_step (double x, double y, double z, double t) inline
Definition at line 125 of file Particle.h.
References _last_step.
 { _last_step = Vertex(x,y,z,t); }
MCSTIndex_t larcv::Particle::mcst_index () const inline
Definition at line 60 of file Particle.h.
References _mcst_index.
 { return _mcst_index; }
void larcv::Particle::mcst_index (MCSTIndex_t id) inline
Definition at line 109 of file Particle.h.
References _mcst_index, and id().
 { _mcst_index = id;    }
MCTIndex_t larcv::Particle::mct_index () const inline
Definition at line 61 of file Particle.h.
References _mct_index.
 { return _mct_index;  }
void larcv::Particle::mct_index (MCTIndex_t id) inline
Definition at line 110 of file Particle.h.
References _mct_index, and id().
 { _mct_index = id;     }
void larcv::Particle::momentum (double px, double py, double pz) inline
Definition at line 117 of file Particle.h.
References _px, _py, _pz, px(), py(), and pz().
 { _px = px; _py = py; _pz = pz; }
short larcv::Particle::nu_current_type () const inline
Definition at line 62 of file Particle.h.
References _current_type.
 { return _current_type; }
void larcv::Particle::nu_current_type (short curr) inline
Definition at line 112 of file Particle.h.
References _current_type.
 { curr = -1; _current_type = curr; }
short larcv::Particle::nu_interaction_type () const inline
Definition at line 63 of file Particle.h.
References _interaction_type.
 { return _interaction_type; }
void larcv::Particle::nu_interaction_type (short itype) inline
Definition at line 113 of file Particle.h.
References _interaction_type.
 { itype = -1; _interaction_type = itype; }
int larcv::Particle::parent_pdg_code () const inline
Definition at line 88 of file Particle.h.
References _parent_pdg.
Referenced by dump().
 { return _parent_pdg;     }
void larcv::Particle::parent_pdg_code (int code) inline
Definition at line 136 of file Particle.h.
References _parent_pdg.
 { _parent_pdg = code;  }
const larcv::Vertex& larcv::Particle::parent_position () const inline
Definition at line 89 of file Particle.h.
References _parent_vtx.
 { return _parent_vtx;}
void larcv::Particle::parent_position (const larcv::Vertex & vtx) inline
Definition at line 137 of file Particle.h.
References _parent_vtx.
 { _parent_vtx = vtx; }
void larcv::Particle::parent_position (double x, double y, double z, double t) inline
Definition at line 138 of file Particle.h.
References _parent_vtx.
 { _parent_vtx = Vertex(x,y,z,t); }
double larcv::Particle::parent_t () const inline
Definition at line 93 of file Particle.h.
References _parent_vtx, and larcv::Vertex::t().
 { return _parent_vtx.t(); }
unsigned int larcv::Particle::parent_track_id () const inline
Definition at line 87 of file Particle.h.
References _parent_trackid.
Referenced by dump().
 { return _parent_trackid; }
void larcv::Particle::parent_track_id (unsigned int id) inline
Definition at line 135 of file Particle.h.
References _parent_trackid, and id().
 { _parent_trackid = id;}
double larcv::Particle::parent_x () const inline
Definition at line 90 of file Particle.h.
References _parent_vtx, and larcv::Vertex::x().
 { return _parent_vtx.x(); }
double larcv::Particle::parent_y () const inline
Definition at line 91 of file Particle.h.
References _parent_vtx, and larcv::Vertex::y().
 { return _parent_vtx.y(); }
double larcv::Particle::parent_z () const inline
Definition at line 92 of file Particle.h.
References _parent_vtx, and larcv::Vertex::z().
 { return _parent_vtx.z(); }
int larcv::Particle::pdg_code () const inline
Definition at line 66 of file Particle.h.
References _pdg.
Referenced by dump().
 { return _pdg;        }
void larcv::Particle::pdg_code (int code) inline
Definition at line 116 of file Particle.h.
References _pdg.
 { _pdg = code;         }
const larcv::Vertex& larcv::Particle::position () const inline
Definition at line 70 of file Particle.h.
References _vtx.
 { return _vtx;   }
void larcv::Particle::position (const larcv::Vertex & vtx) inline
Definition at line 118 of file Particle.h.
References _vtx.
 { _vtx = vtx;    }
void larcv::Particle::position (double x, double y, double z, double t) inline
Definition at line 119 of file Particle.h.
References _vtx.
 { _vtx = Vertex(x,y,z,t); }
double larcv::Particle::px () const inline
Definition at line 67 of file Particle.h.
References _px.
Referenced by dump(), and momentum().
 { return _px;         }
double larcv::Particle::py () const inline
Definition at line 68 of file Particle.h.
References _py.
Referenced by dump(), and momentum().
 { return _py;         }
double larcv::Particle::pz () const inline
Definition at line 69 of file Particle.h.
References _pz.
Referenced by dump(), and momentum().
 { return _pz;         }
ShapeType_t larcv::Particle::shape () const inline
Definition at line 59 of file Particle.h.
References _shape.
 { return _shape;      }
void larcv::Particle::shape (ShapeType_t shape) inline
Definition at line 111 of file Particle.h.
References _shape, and shape().
Referenced by shape().
 { _shape = shape;      }
double larcv::Particle::t () const inline
Definition at line 74 of file Particle.h.
References _vtx, and larcv::Vertex::t().
Referenced by dump().
 { return _vtx.t();    }
unsigned int larcv::Particle::track_id () const inline
Definition at line 65 of file Particle.h.
References _trackid.
Referenced by dump().
 { return _trackid;    }
void larcv::Particle::track_id (unsigned int id) inline
Definition at line 115 of file Particle.h.
References _trackid, and id().
 { _trackid = id;       }
double larcv::Particle::x () const inline
Definition at line 71 of file Particle.h.
References _vtx, and larcv::Vertex::x().
Referenced by dump().
 { return _vtx.x();    }
double larcv::Particle::y () const inline
Definition at line 72 of file Particle.h.
References _vtx, and larcv::Vertex::y().
Referenced by dump().
 { return _vtx.y();    }
double larcv::Particle::z () const inline
Definition at line 73 of file Particle.h.
References _vtx, and larcv::Vertex::z().
Referenced by dump().
 { return _vtx.z();    }
Member Data Documentation
int larcv::Particle::_ancestor_pdg private
PDG code of the ancestor particle.
Definition at line 178 of file Particle.h.
Referenced by ancestor_pdg_code().
unsigned int larcv::Particle::_ancestor_trackid private
Geant4 track id of the ancestor particle.
Definition at line 177 of file Particle.h.
Referenced by ancestor_track_id().
Vertex larcv::Particle::_ancestor_vtx private
(x,y,z,t) of ancestor's vertex information
Definition at line 179 of file Particle.h.
Referenced by ancestor_position(), ancestor_t(), ancestor_x(), ancestor_y(), and ancestor_z().
std::vector<larcv::BBox2D> larcv::Particle::_bb2d_v private
bounding box of particle's trajectory in 2D projections. index = ProjectionID_t
Definition at line 170 of file Particle.h.
Referenced by boundingbox_2d(), and dump().
larcv::BBox3D larcv::Particle::_bb3d private
bounding box of particle's trajectory in 3D
Definition at line 171 of file Particle.h.
Referenced by boundingbox_3d(), and dump().
short larcv::Particle::_current_type private
if neutrino, shows interaction GENIE current type. else kINVALID_USHORT
Definition at line 156 of file Particle.h.
Referenced by nu_current_type().
double larcv::Particle::_dist_travel private
filled only if MCTrack origin: distance measured along the trajectory
Definition at line 166 of file Particle.h.
Referenced by distance_travel().
Vertex larcv::Particle::_end_pt private
(x,y,z,t) at which particle disappeared from G4WorldVolume
Definition at line 163 of file Particle.h.
Referenced by end_position().
double larcv::Particle::_energy_deposit private
deposited energy of the particle in the detector
Definition at line 168 of file Particle.h.
Referenced by energy_deposit().
double larcv::Particle::_energy_init private
initial energy of the particle
Definition at line 167 of file Particle.h.
Referenced by energy_init().
Vertex larcv::Particle::_first_step private
(x,y,z,t) of the first energy deposition point in the detector
Definition at line 164 of file Particle.h.
Referenced by first_step().
InstanceID_t larcv::Particle::_id private
"ID" of this particle
Definition at line 150 of file Particle.h.
Referenced by id().
short larcv::Particle::_interaction_type private
if neutrino, shows interaction GENIE code. else kINVALID_USHORT
Definition at line 157 of file Particle.h.
Referenced by nu_interaction_type().
Vertex larcv::Particle::_last_step private
(x,y,z,t) of the last energy deposition point in the detector
Definition at line 165 of file Particle.h.
Referenced by last_step().
MCSTIndex_t larcv::Particle::_mcst_index private
index number in the origin MCShower/MCTrack container array (kINVALID_USHORT if neither)
index number in the origin MCTruth container array (kINVALID_USHORT if MCShower/MCTrack)
Definition at line 152 of file Particle.h.
Referenced by mcst_index().
MCTIndex_t larcv::Particle::_mct_index private
Definition at line 154 of file Particle.h.
Referenced by mct_index().
int larcv::Particle::_parent_pdg private
PDG code of the parent particle.
Definition at line 174 of file Particle.h.
Referenced by parent_pdg_code().
unsigned int larcv::Particle::_parent_trackid private
Geant4 track id of the parent particle.
Definition at line 173 of file Particle.h.
Referenced by parent_track_id().
Vertex larcv::Particle::_parent_vtx private
(x,y,z,t) of parent's vertex information
Definition at line 175 of file Particle.h.
Referenced by parent_position(), parent_t(), parent_x(), parent_y(), and parent_z().
int larcv::Particle::_pdg private
PDG code.
Definition at line 160 of file Particle.h.
Referenced by pdg_code().
std::string larcv::Particle::_process private
string identifier of the particle's creation process from Geant4
Definition at line 169 of file Particle.h.
Referenced by creation_process().
double larcv::Particle::_px private
Definition at line 161 of file Particle.h.
Referenced by momentum(), and px().
double larcv::Particle::_py private
Definition at line 161 of file Particle.h.
Referenced by momentum(), and py().
double larcv::Particle::_pz private
(x,y,z) component of particle's initial momentum
Definition at line 161 of file Particle.h.
Referenced by momentum(), and pz().
ShapeType_t larcv::Particle::_shape private
shows if it is (e+/e-/gamma) or other particle types
Definition at line 155 of file Particle.h.
Referenced by shape().
unsigned int larcv::Particle::_trackid private
Geant4 track id.
Definition at line 159 of file Particle.h.
Referenced by track_id().
Vertex larcv::Particle::_vtx private
(x,y,z,t) of particle's vertex information
Definition at line 162 of file Particle.h.
Referenced by position(), t(), x(), y(), and z().
The documentation for this class was generated from the following files:
Particle.h
Particle.cxx