LArCV: larcv::ChStatus Class Reference
larcv::ChStatus Class Reference
Data rep.
#include <ChStatus.h>
Public Member Functions
ChStatus ()
Default constructor.
ChStatus (ProjectionID_t id, std::vector< short > &&data)
Status vector move ctor.
~ChStatus ()
Default destructor.
void initialize (size_t nwires, short status=chstatus::kUNKNOWN)
Initialize instance (nullify status + set dimension)
void reset (short status=chstatus::kUNKNOWN)
Set all channels' status to what's specified.
void id (ProjectionID_t p)
Set Projection id.
void status (size_t wire, short status)
Set wire status.
ProjectionID_t id () const
ProjectionID_t getter.
short status (size_t wire) const
Status getter.
const std::vector< short > & as_vector () const
Status vector const reference getter.
std::string dump () const
Status vector dumper.
Private Attributes
std::vector< short > _status_v
larcv::ProjectionID_t _id
Detailed Description
Data rep.
to hold channel-wise "status" (such as dead wire, etc.).
Definition at line 24 of file ChStatus.h.
Constructor & Destructor Documentation
larcv::ChStatus::ChStatus () inline
Default constructor.
Definition at line 29 of file ChStatus.h.
 {}
larcv::ChStatus::ChStatus (ProjectionID_t id, std::vector< short > && data) inline
Status vector move ctor.
Definition at line 33 of file ChStatus.h.
       : _status_v(std::move(data))
       , _id(id)
     {}
larcv::ChStatus::~ChStatus () inline
Default destructor.
Definition at line 39 of file ChStatus.h.
 {}
Member Function Documentation
const std::vector<short>& larcv::ChStatus::as_vector () const inline
Status vector const reference getter.
Definition at line 54 of file ChStatus.h.
References _status_v.
 { return _status_v; }
std::string larcv::ChStatus::dump () const
Status vector dumper.
Definition at line 43 of file ChStatus.cxx.
References _id, _status_v, and larcv::chstatus::kGOOD.
   {
     std::stringstream ss;
     ss << "Projection " << _id << " ... " << _status_v.size() << " wires:" << std::endl;
     for(size_t i=0; i<_status_v.size(); ++i) {
       if(_status_v[i] >= chstatus::kGOOD)
     ss << _status_v[i] << " ";
       else
     ss << "\033[93m" << _status_v[i] << "\033[00m ";
       if(i && (i+1)%50==0) ss << std::endl;
     }
     if(_status_v.size()%50)
       ss << std::endl;
     return ss.str();
   }
void larcv::ChStatus::id (ProjectionID_t p) inline
Set Projection id.
Definition at line 46 of file ChStatus.h.
References _id.
Referenced by larcv::EventChStatus::emplace(), and larcv::EventChStatus::insert().
 { _id = p; }
ProjectionID_t larcv::ChStatus::id () const inline
ProjectionID_t getter.
Definition at line 50 of file ChStatus.h.
References _id.
 { return _id; }
void larcv::ChStatus::initialize (size_t nwires, short status = chstatus::kUNKNOWN)
Initialize instance (nullify status + set dimension)
Definition at line 10 of file ChStatus.cxx.
References _status_v, and reset().
   {
     _status_v.resize(nwires);
     reset(init_status);
   }
void larcv::ChStatus::reset (short status = chstatus::kUNKNOWN)
Set all channels' status to what's specified.
Definition at line 16 of file ChStatus.cxx.
References _status_v.
Referenced by initialize().
   { for(auto& s : _status_v) s = init_status; }
void larcv::ChStatus::status (size_t wire, short status)
Set wire status.
Definition at line 19 of file ChStatus.cxx.
References _status_v.
   {
     if(wire >= _status_v.size()) {
       std::stringstream ss;
       ss << "<<ChStatus::" << __FUNCTION__ << ">>"
      << " Invalid wire requested (" << wire
      << " while currently registered # wires: " << _status_v.size() << ")";
       throw larbys(ss.str());
     }
     _status_v[wire] = status;
   }
short larcv::ChStatus::status (size_t wire) const
Status getter.
Definition at line 31 of file ChStatus.cxx.
References _status_v.
   {
     if(wire >= _status_v.size()) {
       std::stringstream ss;
       ss << "<<ChStatus::" << __FUNCTION__ << ">>"
      << " Invalid wire requested (" << wire
      << " while currently registered # wires: " << _status_v.size() << ")";
       throw larbys(ss.str());
     }
     return _status_v[wire];
   }
Member Data Documentation
larcv::ProjectionID_t larcv::ChStatus::_id private
Definition at line 60 of file ChStatus.h.
Referenced by dump(), and id().
std::vector<short> larcv::ChStatus::_status_v private
Definition at line 59 of file ChStatus.h.
Referenced by as_vector(), dump(), initialize(), reset(), and status().
The documentation for this class was generated from the following files:
ChStatus.h
ChStatus.cxx