LArCV: larcv::ClusterPixel2D Class Reference
larcv::ClusterPixel2D Class Reference
Container of multiple (2D-projected) voxel set array.
#include <Voxel2D.h>
Public Member Functions
ClusterPixel2D ()
Default ctor.
virtual ~ClusterPixel2D ()
Default dtor.
ClusterPixel2D (const VoxelSetArray &vsa)
Copy ctor w/ VoxelSetArray.
ClusterPixel2D (larcv::VoxelSetArray &&vsa, larcv::ImageMeta meta)
move ctor
const larcv::ImageMeta & meta () const
Access ImageMeta of specific projection.
void clear_data ()
Clear everything.
void meta (const larcv::ImageMeta &meta)
Meta setter.
size_t size () const
Get # of VoxelSet.
const larcv::VoxelSet & voxel_set (InstanceID_t id) const
Access specific VoxelSet.
const std::vector
< larcv::VoxelSet > & as_vector () const
Access all VoxelSet as a vector.
void resize (const size_t num)
Resize voxel array.
larcv::VoxelSet & writeable_voxel_set (const InstanceID_t id)
Access non-const reference of a specific VoxelSet.
void emplace (std::vector< larcv::VoxelSet > &&voxel_vv)
Move an arrray of VoxelSet. Each element's InstanceID_t gets updated.
void emplace (larcv::VoxelSet &&voxel_v)
Move a VoxelSet into a collection. The InstanceID_t is respected.
void insert (const std::vector< larcv::VoxelSet > &voxel_vv)
Set an array of VoxelSet. Each element's InstanceID_t gets updated.
void insert (const larcv::VoxelSet &voxel_v)
Set a VoxelSet into a collection. The InstanceID_t is respected.
void move (larcv::VoxelSetArray &&orig)
Mover.
Private Attributes
larcv::ImageMeta _meta
Detailed Description
Container of multiple (2D-projected) voxel set array.
Definition at line 61 of file Voxel2D.h.
Constructor & Destructor Documentation
larcv::ClusterPixel2D::ClusterPixel2D () inline
Default ctor.
Definition at line 64 of file Voxel2D.h.
 {}
virtual larcv::ClusterPixel2D::~ClusterPixel2D () inline virtual
Default dtor.
Definition at line 66 of file Voxel2D.h.
 {}
larcv::ClusterPixel2D::ClusterPixel2D (const VoxelSetArray & vsa) inline
Copy ctor w/ VoxelSetArray.
Definition at line 68 of file Voxel2D.h.
       : VoxelSetArray(vsa)
     {}
larcv::ClusterPixel2D::ClusterPixel2D (larcv::VoxelSetArray && vsa, larcv::ImageMeta meta)
move ctor
Definition at line 25 of file Voxel2D.cxx.
References meta().
         : VoxelSetArray(vsa)
     {this->meta(meta);}
Member Function Documentation
const std::vector<larcv::VoxelSet>& larcv::VoxelSetArray::as_vector () const inline inherited
Access all VoxelSet as a vector.
Definition at line 169 of file Voxel.h.
References larcv::VoxelSetArray::_voxel_vv.
Referenced by larcv::as_image2d(), larcv::as_sparse_tensor2d(), larcv::as_sparse_tensor3d(), meta(), and larcv::ClusterVoxel3D::meta().
     { return _voxel_vv; }
void larcv::ClusterPixel2D::clear_data () inline
Clear everything.
Definition at line 84 of file Voxel2D.h.
References _meta, and larcv::VoxelSetArray::clear_data().
 { VoxelSetArray::clear_data(); _meta = ImageMeta(); }
void larcv::VoxelSetArray::emplace (std::vector< larcv::VoxelSet > && voxel_vv) inherited
Move an arrray of VoxelSet. Each element's InstanceID_t gets updated.
Definition at line 100 of file Voxel.cxx.
References larcv::VoxelSetArray::_voxel_vv.
Referenced by larcv::PyCluster3DMaker::append_ndarray().
   {
     _voxel_vv = std::move(voxel_vv);
     for(size_t id=0; id<_voxel_vv.size(); ++id)
       _voxel_vv[id].id(id);
   }
void larcv::VoxelSetArray::emplace (larcv::VoxelSet && voxel_v) inherited
Move a VoxelSet into a collection. The InstanceID_t is respected.
Definition at line 114 of file Voxel.cxx.
References larcv::VoxelSetArray::_voxel_vv.
   {
     if(voxel_v.id() >= _voxel_vv.size()) {
       size_t orig_size = _voxel_vv.size();
       _voxel_vv.resize(voxel_v.id()+1);
       for(size_t id=orig_size; id<_voxel_vv.size(); ++id)
         _voxel_vv[id].id(id);
     }
     _voxel_vv[voxel_v.id()] = std::move(voxel_v);
   }
void larcv::VoxelSetArray::insert (const std::vector< larcv::VoxelSet > & voxel_vv) inline inherited
Set an array of VoxelSet. Each element's InstanceID_t gets updated.
Definition at line 107 of file Voxel.cxx.
References larcv::VoxelSetArray::_voxel_vv.
   {
     _voxel_vv = voxel_vv;
     for(size_t id=0; id<_voxel_vv.size(); ++id)
       _voxel_vv[id].id(id);
   }
void larcv::VoxelSetArray::insert (const larcv::VoxelSet & voxel_v) inherited
Set a VoxelSet into a collection. The InstanceID_t is respected.
Definition at line 125 of file Voxel.cxx.
References larcv::VoxelSetArray::_voxel_vv, and larcv::VoxelSet::id().
   {
     if(voxel_v.id() >= _voxel_vv.size()) {
       size_t orig_size = _voxel_vv.size();
       _voxel_vv.resize(voxel_v.id()+1);
       for(size_t id=orig_size; id<_voxel_vv.size(); ++id)
         _voxel_vv[id].id(id);
     }
     _voxel_vv[voxel_v.id()] = voxel_v;
   }
const larcv::ImageMeta& larcv::ClusterPixel2D::meta () const inline
Access ImageMeta of specific projection.
Definition at line 78 of file Voxel2D.h.
References _meta.
Referenced by larcv::as_image2d(), larcv::as_sparse_tensor2d(), ClusterPixel2D(), meta(), and larcv::EventClusterPixel2D::set().
 { return _meta; }
void larcv::ClusterPixel2D::meta (const larcv::ImageMeta & meta)
Meta setter.
Definition at line 29 of file Voxel2D.cxx.
References _meta, larcv::VoxelSetArray::as_vector(), meta(), and larcv::ImageMeta::size().
     {
         auto const max_id = meta.size();
         for (auto const& vs : this->as_vector()) {
             for (auto const& vox : vs.as_vector()) {
                 if (vox.id() < max_id) continue;
                 std::cerr << "VoxelSet contains ID " << vox.id()
                           << " which cannot exists in ImageMeta with size " << max_id
                           << std::endl;
                 throw std::exception();
             }
         }
         _meta = meta;
     }
void larcv::VoxelSetArray::move (larcv::VoxelSetArray && orig) inline inherited
Mover.
Definition at line 191 of file Voxel.h.
References larcv::VoxelSetArray::_voxel_vv.
     { _voxel_vv = std::move(orig._voxel_vv); }
void larcv::VoxelSetArray::resize (const size_t num) inline inherited
Resize voxel array.
Definition at line 178 of file Voxel.h.
References larcv::VoxelSetArray::_voxel_vv.
     { _voxel_vv.resize(num); for(size_t i=0; i<num; ++i) _voxel_vv[i].id(i); }
size_t larcv::VoxelSetArray::size () const inline inherited
Get # of VoxelSet.
Definition at line 165 of file Voxel.h.
References larcv::VoxelSetArray::_voxel_vv.
Referenced by larcv::PyCluster3DMaker::append_ndarray().
 { return _voxel_vv.size(); }
const larcv::VoxelSet & larcv::VoxelSetArray::voxel_set (InstanceID_t id) const inherited
Access specific VoxelSet.
Definition at line 91 of file Voxel.cxx.
References larcv::VoxelSetArray::_voxel_vv.
   {
     if(id >= _voxel_vv.size()) {
       std::cerr << "VoxelSetArray has no VoxelSet with InstanceID_t " << id << std::endl;
       throw std::exception();
     }
     return _voxel_vv[id];
   }
larcv::VoxelSet & larcv::VoxelSetArray::writeable_voxel_set (const InstanceID_t id) inherited
Access non-const reference of a specific VoxelSet.
Definition at line 136 of file Voxel.cxx.
References larcv::VoxelSetArray::_voxel_vv.
   {
     if(id >= _voxel_vv.size()) {
       std::cerr << "VoxelSetArray has no VoxelSet with InstanceID_t " << id << std::endl;
       throw std::exception();
     }
     return _voxel_vv[id];
   }
Member Data Documentation
larcv::ImageMeta larcv::ClusterPixel2D::_meta private
Definition at line 89 of file Voxel2D.h.
Referenced by clear_data(), and meta().
The documentation for this class was generated from the following files:
Voxel2D.h
Voxel2D.cxx