LArCV: larcv::PyCluster3DMaker Class Reference
larcv::PyCluster3DMaker Class Reference
#include <PyCluster3DMaker.h>
Public Member Functions
PyCluster3DMaker (const std::string name="PyCluster3DMaker")
Default constructor.
~PyCluster3DMaker ()
Default destructor.
void configure (const PSet &)
Called first with the argument passing the configuration parameters.
void initialize ()
Called after configure, this is where you should initialize variables to be stored in an output analysis file.
bool process (IOManager &mgr)
Called per-event, this is where you should implement your per-event action/analysis.
void finalize ()
Called after event loop is over. This is where you can store your histograms etc. to an output analysis file.
void append_ndarray (PyObject *img)
void set_meta (const Voxel3DMeta &meta)
void set_id (size_t run, size_t subrun, size_t event)
bool has_ana_file () const
Returns true/false if there is an analysis ROOT file to store the output objects.
TFile & ana_file ()
Returns analysis ROOT file if exits (else throws an exception)
virtual bool is (const std::string question) const
Only for experts: allows a loose grouping for a set of ProcessBase inherit classes via true/false return to a "question".
bool event_creator () const
Only for experts: larcv::ProcessDriver to see if this module can create a new event or not.
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Private Attributes
std::string _producer_name
size_t _run
size_t _subrun
size_t _event
larcv::VoxelSetArray _cluster3d_v
Voxel3DMeta _meta
Detailed Description
Definition at line 29 of file PyCluster3DMaker.h.
Constructor & Destructor Documentation
larcv::PyCluster3DMaker::PyCluster3DMaker (const std::string name = "PyCluster3DMaker")
Default constructor.
Definition at line 11 of file PyCluster3DMaker.cxx.
         : ProcessBase(name)
     {}
larcv::PyCluster3DMaker::~PyCluster3DMaker () inline
Default destructor.
Definition at line 37 of file PyCluster3DMaker.h.
 {}
Member Function Documentation
TFile& larcv::ProcessBase::ana_file () inline inherited
Returns analysis ROOT file if exits (else throws an exception)
Definition at line 61 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
     { if(!_fout) throw larbys("ana file does not exist"); return *_fout; }
void larcv::PyCluster3DMaker::append_ndarray (PyObject * img)
Definition at line 25 of file PyCluster3DMaker.cxx.
References _cluster3d_v, larcv::as_tensor3d(), larcv::VoxelSetArray::emplace(), LARCV_INFO, and larcv::VoxelSetArray::size().
     {
         LARCV_INFO() << "Appending an Cluster3D (current size=" << _cluster3d_v.size() << ")" << std::endl;
         _cluster3d_v.emplace(std::move(as_tensor3d(img)));
     }
void larcv::PyCluster3DMaker::configure (const PSet &) virtual
Called first with the argument passing the configuration parameters.
Implements larcv::ProcessBase.
Definition at line 15 of file PyCluster3DMaker.cxx.
References _producer_name, and larcv::PSet::get().
     { _producer_name = cfg.get<std::string>("Cluster3DProducer"); }
bool larcv::ProcessBase::event_creator () const inline inherited
Only for experts: larcv::ProcessDriver to see if this module can create a new event or not.
Definition at line 70 of file ProcessBase.h.
References larcv::ProcessBase::_event_creator.
     { return _event_creator; }
void larcv::PyCluster3DMaker::finalize () virtual
Called after event loop is over. This is where you can store your histograms etc. to an output analysis file.
Implements larcv::ProcessBase.
Definition at line 40 of file PyCluster3DMaker.cxx.
     {}
bool larcv::ProcessBase::has_ana_file () const inline inherited
Returns true/false if there is an analysis ROOT file to store the output objects.
Definition at line 58 of file ProcessBase.h.
References larcv::ProcessBase::_fout.
     { return _fout != nullptr; }
void larcv::PyCluster3DMaker::initialize () virtual
Called after configure, this is where you should initialize variables to be stored in an output analysis file.
Implements larcv::ProcessBase.
Definition at line 18 of file PyCluster3DMaker.cxx.
References _cluster3d_v, _event, _meta, _run, _subrun, larcv::Voxel3DMeta::clear(), larcv::VoxelSetArray::clear_data(), and larcv::kINVALID_SIZE.
     {
         _run = _subrun = _event = kINVALID_SIZE;
         _cluster3d_v.clear_data();
         _meta.clear();
     }
bool larcv::ProcessBase::is (const std::string question) const virtual inherited
Only for experts: allows a loose grouping for a set of ProcessBase inherit classes via true/false return to a "question".
Definition at line 17 of file ProcessBase.cxx.
   { return !(question.empty()); }
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::ProcessDriver::configure(), and larcv::larcv_base::name().
     { return *_logger; }
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::ProcessFactory::add_factory(), larcv::ProcessDriver::configure(), larcv::ProcessFactory::create(), larcv::ProcessDriver::finalize(), larcv::IOManager::initialize(), larcv::IOManager::IOManager(), larcv::IOManager::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
bool larcv::PyCluster3DMaker::process (IOManager & mgr) virtual
Called per-event, this is where you should implement your per-event action/analysis.
Implements larcv::ProcessBase.
Definition at line 31 of file PyCluster3DMaker.cxx.
References _cluster3d_v, _meta, _producer_name, larcv::Voxel3DMeta::clear(), larcv::VoxelSetArray::clear_data(), larcv::ClusterVoxel3D::emplace(), and larcv::IOManager::get_data().
     {
             auto& ev_output = mgr.get_data<larcv::EventClusterVoxel3D>(_producer_name);
         ev_output.emplace(std::move(_cluster3d_v),_meta);
         _cluster3d_v.clear_data();
         _meta.clear();
         return true;
     }
void larcv::PyCluster3DMaker::set_id (size_t run, size_t subrun, size_t event) inline
Definition at line 51 of file PyCluster3DMaker.h.
References _event, _run, and _subrun.
     { _run = run; _subrun = subrun; _event = event; }
void larcv::PyCluster3DMaker::set_meta (const Voxel3DMeta & meta) inline
Definition at line 49 of file PyCluster3DMaker.h.
References _meta.
 { _meta = meta; }
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::ProcessDriver::configure(), and larcv::IOManager::configure().
     { _logger->set(level); }
Member Data Documentation
larcv::VoxelSetArray larcv::PyCluster3DMaker::_cluster3d_v private
Definition at line 58 of file PyCluster3DMaker.h.
Referenced by append_ndarray(), initialize(), and process().
size_t larcv::PyCluster3DMaker::_event private
Definition at line 57 of file PyCluster3DMaker.h.
Referenced by initialize(), and set_id().
Voxel3DMeta larcv::PyCluster3DMaker::_meta private
Definition at line 59 of file PyCluster3DMaker.h.
Referenced by initialize(), process(), and set_meta().
std::string larcv::PyCluster3DMaker::_producer_name private
Definition at line 56 of file PyCluster3DMaker.h.
Referenced by configure(), and process().
size_t larcv::PyCluster3DMaker::_run private
Definition at line 57 of file PyCluster3DMaker.h.
Referenced by initialize(), and set_id().
size_t larcv::PyCluster3DMaker::_subrun private
Definition at line 57 of file PyCluster3DMaker.h.
Referenced by initialize(), and set_id().
The documentation for this class was generated from the following files:
PyCluster3DMaker.h
PyCluster3DMaker.cxx