LArCV: larcv::EventChStatus Class Reference
larcv::EventChStatus Class Reference
Event-wise class to store a collection of larcv::ChStatus (one per plane)
#include <EventChStatus.h>
Public Member Functions
EventChStatus ()
Default constructor.
virtual ~EventChStatus ()
Default destructor.
void clear ()
Clears an array of larcv::ChStatus.
const std::map
< larcv::ProjectionID_t,
larcv::ChStatus > & chstatus_map () const
Getter for a const reference of core data.
const ChStatus & status (larcv::ProjectionID_t id) const
Get larcv::ChStatus for a specified plane.
void insert (const ChStatus &status)
Insert larcv::ChStatus into a collection.
void emplace (ChStatus &&status)
Emplace larcv::ChStatus into a collection.
std::string dump () const
Dump contents in string representation.
const std::string & producer () const
Producer name getter.
size_t run () const
Run number getter.
size_t subrun () const
SubRun number getter.
size_t event () const
Event number getter.
bool valid () const
Make sure run/subrun/event ID is set.
bool operator== (const EventBase &rhs) const
Comparison opearator for run/subrun/event id.
bool operator!= (const EventBase &rhs) const
Comparison opearator for run/subrun/event id.
bool operator< (const EventBase &rhs) const
Comparison opearator for run/subrun/event id (for sorted container like std::set and/or std::map)
std::string event_key () const
Formatted string key getter (a string key consists of 0-padded run, subrun, and event id)
void set_id (const size_t run, const size_t subrun, const size_t event)
Setting the id.
Private Attributes
std::map
< ::larcv::ProjectionID_t,::larcv::ChStatus > _status_m
Detailed Description
Event-wise class to store a collection of larcv::ChStatus (one per plane)
A concrete factory class for larcv::EventChStatus.
Definition at line 29 of file EventChStatus.h.
Constructor & Destructor Documentation
larcv::EventChStatus::EventChStatus () inline
Default constructor.
Definition at line 34 of file EventChStatus.h.
 {}
virtual larcv::EventChStatus::~EventChStatus () inline virtual
Default destructor.
Definition at line 37 of file EventChStatus.h.
 {}
Member Function Documentation
const std::map<larcv::ProjectionID_t,larcv::ChStatus>& larcv::EventChStatus::chstatus_map () const inline
Getter for a const reference of core data.
Definition at line 43 of file EventChStatus.h.
References _status_m.
 { return _status_m; }
void larcv::EventChStatus::clear () virtual
Clears an array of larcv::ChStatus.
Reimplemented from larcv::EventBase.
Definition at line 12 of file EventChStatus.cxx.
References _status_m, and larcv::EventBase::clear().
   {
     EventBase::clear();
     _status_m.clear();
   }
std::string larcv::EventChStatus::dump () const
Dump contents in string representation.
Definition at line 31 of file EventChStatus.cxx.
References _status_m.
   {
     std::string res;
     for(auto const& id_status : _status_m) res += id_status.second.dump() + "\n";
     return res;
   }
void larcv::EventChStatus::emplace (ChStatus && status)
Emplace larcv::ChStatus into a collection.
Definition at line 28 of file EventChStatus.cxx.
References _status_m, larcv::ChStatus::id(), and status().
   { _status_m.emplace(status.id(),std::move(status)); }
size_t larcv::EventBase::event () const inline inherited
Event number getter.
Definition at line 56 of file EventBase.h.
References larcv::EventBase::_event.
Referenced by larcv::IOManager::clear_entry(), larcv::IOManager::get_data(), larcv::EventBase::operator<(), larcv::EventBase::operator==(), larcv::IOManager::register_producer(), larcv::EventBase::set_id(), and larcv::IOManager::set_id().
 { return _event;  }
std::string larcv::EventBase::event_key () const inherited
Formatted string key getter (a string key consists of 0-padded run, subrun, and event id)
Definition at line 13 of file EventBase.cxx.
References larcv::EventBase::_event, larcv::EventBase::_run, and larcv::EventBase::_subrun.
Referenced by larcv::IOManager::set_id().
   {
     std::stringstream ss;
     ss << std::setw( 7 ) << std::setfill( '0' ) << _run << "_"
        << std::setw( 5 ) << std::setfill( '0' ) << _subrun << "_"
        << std::setw( 6 ) << std::setfill( '0' ) << _event;
     return ss.str();
   }
void larcv::EventChStatus::insert (const ChStatus & status)
Insert larcv::ChStatus into a collection.
Definition at line 25 of file EventChStatus.cxx.
References _status_m, larcv::ChStatus::id(), and status().
   { _status_m[status.id()] = status; }
bool larcv::EventBase::operator!= (const EventBase & rhs) const inline inherited
Comparison opearator for run/subrun/event id.
Definition at line 64 of file EventBase.h.
     { return !((*this) == rhs); }
bool larcv::EventBase::operator< (const EventBase & rhs) const inline inherited
Comparison opearator for run/subrun/event id (for sorted container like std::set and/or std::map)
Definition at line 67 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, larcv::EventBase::event(), larcv::EventBase::run(), and larcv::EventBase::subrun().
     {
       if(_run < rhs.run()) return true;
       if(_run > rhs.run()) return false;
       if(_subrun < rhs.subrun()) return true;
       if(_subrun > rhs.subrun()) return false;
       if(_event < rhs.event()) return true;
       if(_event > rhs.event()) return false;
       return false;
     }
bool larcv::EventBase::operator== (const EventBase & rhs) const inline inherited
Comparison opearator for run/subrun/event id.
Definition at line 61 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, larcv::EventBase::event(), larcv::EventBase::run(), and larcv::EventBase::subrun().
     { return (_run == rhs.run() && _subrun == rhs.subrun() && _event == rhs.event()); }
const std::string& larcv::EventBase::producer () const inline inherited
Producer name getter.
Definition at line 50 of file EventBase.h.
References larcv::EventBase::_producer.
 { return _producer; }
size_t larcv::EventBase::run () const inline inherited
Run number getter.
Definition at line 52 of file EventBase.h.
References larcv::EventBase::_run.
Referenced by larcv::IOManager::clear_entry(), larcv::IOManager::get_data(), larcv::EventBase::operator<(), larcv::EventBase::operator==(), larcv::IOManager::register_producer(), larcv::EventBase::set_id(), and larcv::IOManager::set_id().
 { return _run;    }
void larcv::EventBase::set_id (const size_t run, const size_t subrun, const size_t event) inline inherited
Setting the id.
Definition at line 82 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, larcv::EventBase::event(), larcv::EventBase::run(), and larcv::EventBase::subrun().
Referenced by larcv::IOManager::get_data().
     { _run = run; _subrun = subrun; _event = event; }
const ChStatus & larcv::EventChStatus::status (larcv::ProjectionID_t id) const
Get larcv::ChStatus for a specified plane.
Definition at line 18 of file EventChStatus.cxx.
References _status_m.
Referenced by emplace(), and insert().
   {
     auto iter = _status_m.find(id);
     if( iter == _status_m.end() ) throw larbys("Invalid request (ProjectionID_t not found)!");
     return (*iter).second;
   }
size_t larcv::EventBase::subrun () const inline inherited
SubRun number getter.
Definition at line 54 of file EventBase.h.
References larcv::EventBase::_subrun.
Referenced by larcv::IOManager::clear_entry(), larcv::IOManager::get_data(), larcv::EventBase::operator<(), larcv::EventBase::operator==(), larcv::IOManager::register_producer(), larcv::EventBase::set_id(), and larcv::IOManager::set_id().
 { return _subrun; }
bool larcv::EventBase::valid () const inline inherited
Make sure run/subrun/event ID is set.
Definition at line 58 of file EventBase.h.
References larcv::EventBase::_event, larcv::EventBase::_run, larcv::EventBase::_subrun, and larcv::kINVALID_SIZE.
Referenced by larcv::IOManager::clear_entry(), larcv::IOManager::event_id(), larcv::IOManager::get_data(), larcv::IOManager::register_producer(), and larcv::IOManager::set_id().
     { return !(_run == kINVALID_SIZE || _subrun == kINVALID_SIZE || _event == kINVALID_SIZE); }
Member Data Documentation
std::map< ::larcv::ProjectionID_t, ::larcv::ChStatus > larcv::EventChStatus::_status_m private
Definition at line 61 of file EventChStatus.h.
Referenced by chstatus_map(), clear(), dump(), emplace(), insert(), and status().
The documentation for this class was generated from the following files:
EventChStatus.h
EventChStatus.cxx