LArCV: larcv::ImageMeta Class Reference
larcv::ImageMeta Class Reference
A simple class to store image's meta data including
0) origin (left-top corner of the picture) absolute coordinate
1) horizontal and vertical size (width and height) in double precision
2) number of horizontal and vertical pixels
It is meant to be associated with a specific cv::Mat or larcv::Image2D object
(where the latter class contains ImageMeta as an attribute).
#include <ImageMeta.h>
Public Member Functions
ImageMeta (double x_min=0., double y_min=0., double x_max=0., double y_max=0., size_t y_row_count=0, size_t x_column_count=0, ProjectionID_t id=larcv::kINVALID_PROJECTIONID, DistanceUnit_t unit=kUnitUnknown)
Default constructor: width, height, and origin coordinate won't be modifiable.
ImageMeta (const BBox2D &box, size_t y_row_count=0, size_t x_column_count=0, DistanceUnit_t unit=kUnitUnknown)
~ImageMeta ()
Default destructor.
bool operator== (const ImageMeta &rhs) const
bool operator!= (const ImageMeta &rhs) const
size_t size () const
size (rows * cols) accessor
size_t rows () const
rows accessor
size_t cols () const
columns accessor
double pixel_width () const
Pixel horizontal size.
double pixel_height () const
Pixel vertical size.
DistanceUnit_t unit () const
2D length unit
size_t index (size_t row, size_t col) const
Provide 1-D array index from row and column.
Point2D position (size_t index) const
Provide absolute coordinate of the center of a specified pixel index.
Point2D position (size_t row, size_t col) const
Provide absolute coordinate of the center of a specified pixel (row,col)
double pos_x (size_t col) const
Provide absolute horizontal coordinate of the center of a specified pixel row.
double pos_y (size_t row) const
Provide absolute vertical coordinate of the center of a specified pixel row.
size_t col (double x) const
Provide horizontal pixel index for a given horizontal x position (in absolute coordinate)
size_t row (double y) const
Provide vertical pixel index for a given vertical y position (in absolute coordinate)
void update (size_t row_count, size_t col_count)
Change # of vertical/horizontal pixels in meta data.
void reset_origin (double x, double y)
Reset origin coordinate.
ImageMeta overlap (const ImageMeta &meta) const
Check if there's an overlap. If so return overlapping bounding box.
ImageMeta inclusive (const ImageMeta &meta) const
Construct a union bounding box.
std::string dump () const
Dump info in text.
bool operator== (const BBox2D &rhs) const
void update (double xmin, double ymin, double xmax, double ymax, ProjectionID_t id=kINVALID_PROJECTIONID)
void update (const Point2D &pt1, const Point2D &pt2, ProjectionID_t id=kINVALID_PROJECTIONID)
bool empty () const
const Point2D & origin () const
const Point2D & bottom_left () const
const Point2D & top_right () const
Point2D center () const
double center_x () const
double center_y () const
double min_x () const
double min_y () const
double max_x () const
double max_y () const
double width () const
double height () const
double area () const
ProjectionID_t id () const
BBox2D overlap (const BBox2D &box) const
BBox2D inclusive (const BBox2D &box) const
Protected Attributes
ImageIndex_t _image_id
Associated image ID (of the same producer name)
size_t _col_count
of pixels in horizontal axis
size_t _row_count
of pixels in vertical axis
DistanceUnit_t _unit
distance unit defined in DataFormatTypes.h
Friends
class Image2D
Detailed Description
A simple class to store image's meta data including
0) origin (left-top corner of the picture) absolute coordinate
1) horizontal and vertical size (width and height) in double precision
2) number of horizontal and vertical pixels
It is meant to be associated with a specific cv::Mat or larcv::Image2D object
(where the latter class contains ImageMeta as an attribute).
For cv::Mat, there
is a function ImageMeta::update to constantly update vertical/horizontal # pixels
as it may change in the course of matrix operation.
Definition at line 35 of file ImageMeta.h.
Constructor & Destructor Documentation
larcv::ImageMeta::ImageMeta (double x_min = 0., double y_min = 0., double x_max = 0., double y_max = 0., size_t y_row_count = 0, size_t x_column_count = 0, ProjectionID_t id = larcv::kINVALID_PROJECTIONID, DistanceUnit_t unit = kUnitUnknown) inline
Default constructor: width, height, and origin coordinate won't be modifiable.
Definition at line 55 of file ImageMeta.h.
References update().
Referenced by inclusive(), and overlap().
       : BBox2D(x_min, y_min, x_max, y_max, id)
       , _unit(unit)
     { update(y_row_count, x_column_count); }
larcv::ImageMeta::ImageMeta (const BBox2D & box, size_t y_row_count = 0, size_t x_column_count = 0, DistanceUnit_t unit = kUnitUnknown) inline
Definition at line 63 of file ImageMeta.h.
References update().
       : BBox2D(box), _unit(unit)
     { update(y_row_count, x_column_count); }
larcv::ImageMeta::~ImageMeta () inline
Default destructor.
Definition at line 70 of file ImageMeta.h.
 {}
Member Function Documentation
double larcv::BBox2D::area () const inline inherited
Definition at line 59 of file BBox.h.
References larcv::BBox2D::_p1, larcv::BBox2D::_p2, larcv::Point2D::x, and larcv::Point2D::y.
 { return (_p2.y - _p1.y) * (_p2.x - _p1.x); }
const Point2D& larcv::BBox2D::bottom_left () const inline inherited
Definition at line 48 of file BBox.h.
References larcv::BBox2D::_p1.
 { return _p1; }
Point2D larcv::BBox2D::center () const inline inherited
Definition at line 50 of file BBox.h.
References larcv::BBox2D::center_x(), and larcv::BBox2D::center_y().
 { return Point2D(center_x(), center_y()); }
double larcv::BBox2D::center_x () const inline inherited
Definition at line 51 of file BBox.h.
References larcv::BBox2D::_p1, larcv::BBox2D::_p2, and larcv::Point2D::x.
Referenced by larcv::BBox2D::center().
 { return _p1.x + 0.5*(_p2.x - _p1.x); }
double larcv::BBox2D::center_y () const inline inherited
Definition at line 52 of file BBox.h.
References larcv::BBox2D::_p1, larcv::BBox2D::_p2, and larcv::Point2D::y.
Referenced by larcv::BBox2D::center().
 { return _p1.y + 0.5*(_p2.y - _p1.y); }
size_t larcv::ImageMeta::col (double x) const
Provide horizontal pixel index for a given horizontal x position (in absolute coordinate)
Definition at line 18 of file ImageMeta.cxx.
References larcv::BBox2D::max_x(), larcv::BBox2D::min_x(), and pixel_width().
Referenced by larcv::Image2D::crop(), larcv::Image2D::overlay(), and pos_x().
   {
     if (x < min_x() || x >= max_x()) {
       std::stringstream ss;
       ss << "Requested col for x=" << x << " ... but the x (cols) span only " << min_x() << " => " << max_x() << "!" << std::endl;
       throw larbys(ss.str());
     }
     return (size_t)((x - min_x()) / pixel_width());
   }
size_t larcv::ImageMeta::cols () const inline
columns accessor
Definition at line 87 of file ImageMeta.h.
References _col_count.
Referenced by larcv::as_caffe_ndarray(), larcv::as_ndarray(), larcv::Image2D::copy_compress(), larcv::Image2D::eltwise(), larcv::fill_img_col(), larcv::Image2D::Image2D(), larcv::Image2D::multiRHS(), larcv::Image2D::operator+=(), larcv::Image2D::paint_row(), larcv::Image2D::reset(), larcv::Image2D::resize(), and larcv::Image2D::set_pixel().
 { return _col_count; }
std::string larcv::ImageMeta::dump () const
Dump info in text.
Definition at line 58 of file ImageMeta.cxx.
References _col_count, _row_count, larcv::BBox2D::id(), and unit().
   {
     std::stringstream ss;
     ss << "ProjectionID " << id() << " (rows,cols) = (" << _row_count << "," << _col_count
        << ") ... Distance Unit: " << (int)(this-> unit())
        << " ... Left Bottom => Right Top " << ((BBox2D*)(this))->dump();
     return ss.str();
   }
bool larcv::BBox2D::empty () const inline inherited
Definition at line 46 of file BBox.h.
References larcv::BBox2D::_p1, and larcv::BBox2D::_p2.
 { return (_p1 == _p2); }
double larcv::BBox2D::height () const inline inherited
Definition at line 58 of file BBox.h.
References larcv::BBox2D::_p1, larcv::BBox2D::_p2, and larcv::Point2D::y.
Referenced by pixel_height().
 { return _p2.y - _p1.y; }
ProjectionID_t larcv::BBox2D::id () const inline inherited
Definition at line 60 of file BBox.h.
References larcv::BBox2D::_id.
Referenced by larcv::Image2D::crop(), dump(), larcv::EventClusterPixel2D::set(), larcv::EventSparseTensor2D::set(), and larcv::BBox2D::update().
 { return _id; }
BBox2D larcv::BBox2D::inclusive (const BBox2D & box) const inherited
Definition at line 46 of file BBox.cxx.
References larcv::BBox2D::BBox2D(), larcv::BBox2D::max_x(), larcv::BBox2D::max_y(), larcv::BBox2D::min_x(), and larcv::BBox2D::min_y().
Referenced by inclusive().
   {
     double min_x = ( box.min_x() < this->min_x() ? box.min_x() : this->min_x() ); //pick smaller x min-boudn
     double max_x = ( box.max_x() > this->max_x() ? box.max_x() : this->max_x() ); //pick larger x max-bound
     double min_y = ( box.min_y() < this->min_y() ? box.min_y() : this->min_y() ); //pick smaller y min-boudn
     double max_y = ( box.max_y() > this->max_y() ? box.max_y() : this->max_y() ); //pick larger y max-bound
     return BBox2D(min_x, min_y, max_x, max_y);
   }
ImageMeta larcv::ImageMeta::inclusive (const ImageMeta & meta) const
Construct a union bounding box.
Definition at line 48 of file ImageMeta.cxx.
References _unit, ImageMeta(), larcv::BBox2D::inclusive(), pixel_height(), and pixel_width().
Referenced by larcv::PyImageStitcher::process().
   {
     auto box = BBox2D::inclusive((BBox2D)meta);
     return ImageMeta(box,
                      box.height() / pixel_height(),
                      box.width() / pixel_width(),
                      _unit);
   }
size_t larcv::ImageMeta::index (size_t row, size_t col) const
Provide 1-D array index from row and column.
Definition at line 8 of file ImageMeta.cxx.
References _col_count, and _row_count.
Referenced by larcv::Image2D::copy(), larcv::Image2D::crop(), larcv::Image2D::overlay(), larcv::Image2D::pixel(), position(), larcv::Image2D::reverse_copy(), and larcv::Image2D::set_pixel().
{
     if ( row >= _row_count || col >= _col_count ) {
       std::stringstream ss;
       ss << "Invalid pixel index queried: (" << row << "," << col << ") but the dimension is only (" << _row_count << "," << _col_count << ")!" << std::endl;
       throw larbys(ss.str());
     }
     return ( col * _row_count + row );
   }
double larcv::BBox2D::max_x () const inline inherited
Definition at line 55 of file BBox.h.
References larcv::BBox2D::_p2, and larcv::Point2D::x.
Referenced by col(), larcv::Image2D::crop(), larcv::BBox2D::inclusive(), larcv::BBox2D::overlap(), larcv::Image2D::overlay(), and reset_origin().
 { return _p2.x; }
double larcv::BBox2D::max_y () const inline inherited
Definition at line 56 of file BBox.h.
References larcv::BBox2D::_p2, and larcv::Point2D::y.
Referenced by larcv::Image2D::crop(), larcv::fill_img_col(), larcv::BBox2D::inclusive(), larcv::BBox2D::overlap(), larcv::Image2D::overlay(), reset_origin(), and row().
 { return _p2.y; }
double larcv::BBox2D::min_x () const inline inherited
Definition at line 53 of file BBox.h.
References larcv::BBox2D::_p1, and larcv::Point2D::x.
Referenced by col(), larcv::Image2D::crop(), larcv::BBox2D::inclusive(), larcv::BBox2D::overlap(), larcv::Image2D::overlay(), and pos_x().
 { return _p1.x; }
double larcv::BBox2D::min_y () const inline inherited
Definition at line 54 of file BBox.h.
References larcv::BBox2D::_p1, and larcv::Point2D::y.
Referenced by larcv::Image2D::crop(), larcv::fill_img_col(), larcv::BBox2D::inclusive(), larcv::BBox2D::overlap(), larcv::Image2D::overlay(), pos_y(), and row().
 { return _p1.y; }
bool larcv::ImageMeta::operator!= (const ImageMeta & rhs) const inline
Definition at line 79 of file ImageMeta.h.
     { return !((*this) == rhs); }
bool larcv::BBox2D::operator== (const BBox2D & rhs) const inline inherited
Definition at line 38 of file BBox.h.
References larcv::BBox2D::_p1, and larcv::BBox2D::_p2.
     { return (_p1 == rhs._p1 && _p2 == rhs._p2); }
bool larcv::ImageMeta::operator== (const ImageMeta & rhs) const inline
Definition at line 72 of file ImageMeta.h.
References _col_count, and _row_count.
     {
       return ( (BBox2D)(*this) == (BBox2D)(rhs) &&
                _row_count == rhs._row_count &&
                _col_count == rhs._col_count );
     }
const Point2D& larcv::BBox2D::origin () const inline inherited
Definition at line 47 of file BBox.h.
References larcv::BBox2D::_p1.
 { return _p1; }
BBox2D larcv::BBox2D::overlap (const BBox2D & box) const inherited
Definition at line 29 of file BBox.cxx.
References larcv::BBox2D::BBox2D(), larcv::BBox2D::max_x(), larcv::BBox2D::max_y(), larcv::BBox2D::min_x(), and larcv::BBox2D::min_y().
Referenced by overlap().
   {
     double minx = ( box.min_x() < this->min_x() ? this->min_x() : box.min_x()  ); //pick larger x min-bound
     double maxx = ( box.max_x() < this->max_x() ? box.max_x()  : this->max_x() ); //pick smaller x max-bound
     double miny = ( box.min_y() < this->min_y() ? this->min_y() : box.min_y()  ); //pick larger x min-bound
     double maxy = ( box.max_y() < this->max_y() ? box.max_y()  : this->max_y() ); //pick smaller x max-bound
     if(!(minx < maxx && miny < maxy)) {
       std::stringstream ss;
       ss << "No overlap found ... this X: " << this->min_x() << " => " << this->max_x() << " Y: " << this->min_y() << " => " << this->max_y()
      << " ... the other X: " << box.min_x() << " => " << box.max_x() << " Y: " << box.min_y() << " => " << box.max_y() << std::endl;
       throw larbys(ss.str());
     }
     return BBox2D(minx, miny, maxx, maxy);
   }
ImageMeta larcv::ImageMeta::overlap (const ImageMeta & meta) const
Check if there's an overlap. If so return overlapping bounding box.
Definition at line 38 of file ImageMeta.cxx.
References _unit, ImageMeta(), larcv::BBox2D::overlap(), pixel_height(), and pixel_width().
   {
     auto box = BBox2D::overlap((BBox2D)meta);
     return ImageMeta(box,
                      box.height() / pixel_height(),
                      box.width() / pixel_width(),
                      _unit);
   }
double larcv::ImageMeta::pixel_height () const inline
Pixel vertical size.
Definition at line 91 of file ImageMeta.h.
References _row_count, and larcv::BBox2D::height().
Referenced by larcv::Image2D::crop(), inclusive(), overlap(), larcv::Image2D::overlay(), pos_y(), and row().
 { return (_row_count ? height() / (double)_row_count : 0.); }
double larcv::ImageMeta::pixel_width () const inline
Pixel horizontal size.
Definition at line 89 of file ImageMeta.h.
References _col_count, and larcv::BBox2D::width().
Referenced by col(), larcv::Image2D::crop(), inclusive(), overlap(), larcv::Image2D::overlay(), and pos_x().
 { return (_col_count ? width()  / (double)_col_count : 0.); }
double larcv::ImageMeta::pos_x (size_t col) const inline
Provide absolute horizontal coordinate of the center of a specified pixel row.
Definition at line 102 of file ImageMeta.h.
References col(), larcv::BBox2D::min_x(), and pixel_width().
Referenced by position().
 { return min_x() + pixel_width() * col; }
double larcv::ImageMeta::pos_y (size_t row) const inline
Provide absolute vertical coordinate of the center of a specified pixel row.
Definition at line 104 of file ImageMeta.h.
References larcv::BBox2D::min_y(), pixel_height(), and row().
Referenced by position().
 { return min_y() + pixel_height() * row; }
Point2D larcv::ImageMeta::position (size_t index) const inline
Provide absolute coordinate of the center of a specified pixel index.
Definition at line 98 of file ImageMeta.h.
References pos_x(), pos_y(), and rows().
 { return Point2D(pos_x(index / rows()), pos_y(index % rows())); }
Point2D larcv::ImageMeta::position (size_t row, size_t col) const inline
Provide absolute coordinate of the center of a specified pixel (row,col)
Definition at line 100 of file ImageMeta.h.
References index().
 { return Point2D(index(row, col)); }
void larcv::ImageMeta::reset_origin (double x, double y) inline
Reset origin coordinate.
Definition at line 112 of file ImageMeta.h.
References larcv::BBox2D::max_x(), larcv::BBox2D::max_y(), and larcv::BBox2D::update().
Referenced by larcv::Image2D::reset_origin().
 { BBox2D::update(x, y, max_x(), max_y()); }
size_t larcv::ImageMeta::row (double y) const
Provide vertical pixel index for a given vertical y position (in absolute coordinate)
Definition at line 28 of file ImageMeta.cxx.
References larcv::BBox2D::max_y(), larcv::BBox2D::min_y(), and pixel_height().
Referenced by larcv::Image2D::crop(), larcv::fill_img_col(), larcv::Image2D::overlay(), and pos_y().
   {
     if (y < min_y() || y >= max_y()) {
       std::stringstream ss;
       ss << "Requested col for y=" << y << " ... but the y (rows) spans only " << min_y() << " => " << max_y() << "!" << std::endl;
       throw larbys(ss.str());
     }
     return (size_t)((y - min_y()) / pixel_height());
   }
size_t larcv::ImageMeta::rows () const inline
rows accessor
Definition at line 85 of file ImageMeta.h.
References _row_count.
Referenced by larcv::as_caffe_ndarray(), larcv::as_ndarray(), larcv::Image2D::copy_compress(), larcv::Image2D::eltwise(), larcv::Image2D::Image2D(), larcv::Image2D::multiRHS(), larcv::Image2D::operator+=(), larcv::Image2D::paint_col(), position(), larcv::Image2D::reset(), larcv::Image2D::resize(), and larcv::Image2D::set_pixel().
 { return _row_count; }
size_t larcv::ImageMeta::size () const inline
size (rows * cols) accessor
Definition at line 83 of file ImageMeta.h.
References _col_count, and _row_count.
Referenced by larcv::as_image2d(), larcv::SparseTensor2D::meta(), and larcv::ClusterPixel2D::meta().
 { return _row_count * _col_count; }
const Point2D& larcv::BBox2D::top_right () const inline inherited
Definition at line 49 of file BBox.h.
References larcv::BBox2D::_p2.
 { return _p2; }
DistanceUnit_t larcv::ImageMeta::unit () const inline
2D length unit
Definition at line 93 of file ImageMeta.h.
References _unit.
Referenced by larcv::Image2D::crop(), and dump().
 { return _unit; }
void larcv::BBox2D::update (double xmin, double ymin, double xmax, double ymax, ProjectionID_t id = kINVALID_PROJECTIONID) inherited
Definition at line 17 of file BBox.cxx.
References larcv::BBox2D::_id, larcv::BBox2D::_p1, larcv::BBox2D::_p2, larcv::BBox2D::id(), larcv::Point2D::x, and larcv::Point2D::y.
Referenced by reset_origin(), and larcv::BBox2D::update().
   {
     if(xmin > xmax) throw larbys("xmin > xmax not allowed for BBox2D::Update!");
     if(ymin > ymax) throw larbys("ymin > ymax not allowed for BBox2D::Update!");
     _p1.x = xmin; _p1.y = ymin;
     _p2.x = xmax, _p2.y = ymax;
     _id = id;
   }
void larcv::BBox2D::update (const Point2D & pt1, const Point2D & pt2, ProjectionID_t id = kINVALID_PROJECTIONID) inherited
Definition at line 26 of file BBox.cxx.
References larcv::BBox2D::_id, larcv::BBox2D::id(), larcv::BBox2D::update(), larcv::Point2D::x, and larcv::Point2D::y.
   { update(p1.x,p1.y,p2.x,p2.y); _id = id; }
void larcv::ImageMeta::update (size_t row_count, size_t col_count) inline
Change # of vertical/horizontal pixels in meta data.
Definition at line 110 of file ImageMeta.h.
References _col_count, and _row_count.
Referenced by larcv::Image2D::clear(), larcv::Image2D::compress(), ImageMeta(), and larcv::Image2D::resize().
 {_row_count = row_count; _col_count = col_count;}
double larcv::BBox2D::width () const inline inherited
Definition at line 57 of file BBox.h.
References larcv::BBox2D::_p1, larcv::BBox2D::_p2, and larcv::Point2D::x.
Referenced by pixel_width().
 { return _p2.x - _p1.x; }
Friends And Related Function Documentation
friend class Image2D friend
Definition at line 37 of file ImageMeta.h.
Member Data Documentation
size_t larcv::ImageMeta::_col_count protected
of pixels in horizontal axis
Definition at line 124 of file ImageMeta.h.
Referenced by cols(), dump(), index(), operator==(), pixel_width(), size(), and update().
ImageIndex_t larcv::ImageMeta::_image_id protected
Associated image ID (of the same producer name)
Definition at line 123 of file ImageMeta.h.
size_t larcv::ImageMeta::_row_count protected
of pixels in vertical axis
Definition at line 125 of file ImageMeta.h.
Referenced by dump(), index(), operator==(), pixel_height(), rows(), size(), and update().
DistanceUnit_t larcv::ImageMeta::_unit protected
distance unit defined in DataFormatTypes.h
Definition at line 126 of file ImageMeta.h.
Referenced by inclusive(), overlap(), and unit().
The documentation for this class was generated from the following files:
ImageMeta.h
ImageMeta.cxx