LArCV: larcv::Voxel Class Reference
larcv::Voxel Class Reference
3D voxel definition element class consisting of ID and stored value
#include <Voxel.h>
Public Member Functions
Voxel (VoxelID_t id=kINVALID_VOXELID, float value=kINVALID_FLOAT)
Default constructor.
~Voxel ()
Default destructor.
VoxelID_t id () const
ID getter.
float value () const
Value getter.
void set (VoxelID_t id, float value)
Value setter.
Voxel & operator+= (float value)
Voxel & operator-= (float value)
Voxel & operator*= (float factor)
Voxel & operator/= (float factor)
bool operator== (const Voxel &rhs) const
bool operator< (const Voxel &rhs) const
bool operator<= (const Voxel &rhs) const
bool operator> (const Voxel &rhs) const
bool operator>= (const Voxel &rhs) const
bool operator== (const float &rhs) const
bool operator< (const float &rhs) const
bool operator<= (const float &rhs) const
bool operator> (const float &rhs) const
bool operator>= (const float &rhs) const
Private Attributes
VoxelID_t _id
voxel id
float _value
Pixel Value.
Detailed Description
3D voxel definition element class consisting of ID and stored value
Definition at line 24 of file Voxel.h.
Constructor & Destructor Documentation
larcv::Voxel::Voxel (VoxelID_t id = kINVALID_VOXELID, float value = kINVALID_FLOAT)
Default constructor.
Definition at line 9 of file Voxel.cxx.
References _id, _value, id(), and value().
   { _id = id; _value = value; }
larcv::Voxel::~Voxel () inline
Default destructor.
Definition at line 31 of file Voxel.h.
 {}
Member Function Documentation
VoxelID_t larcv::Voxel::id () const inline
ID getter.
Definition at line 34 of file Voxel.h.
References _id.
Referenced by set(), and Voxel().
 { return _id; }
Voxel& larcv::Voxel::operator*= (float factor) inline
Definition at line 48 of file Voxel.h.
References _value.
     { _value *= factor; return (*this); }
Voxel& larcv::Voxel::operator+= (float value) inline
Definition at line 44 of file Voxel.h.
References _value, and value().
     { _value += value; return (*this); }
Voxel& larcv::Voxel::operator-= (float value) inline
Definition at line 46 of file Voxel.h.
References _value, and value().
     { _value -= value; return (*this); }
Voxel& larcv::Voxel::operator/= (float factor) inline
Definition at line 50 of file Voxel.h.
References _value.
     { _value /= factor; return (*this); }
bool larcv::Voxel::operator< (const Voxel & rhs) const inline
Definition at line 58 of file Voxel.h.
References _id.
     {
       if ( _id < rhs._id) return true;
       if ( _id > rhs._id) return false;
       return false;
     }
bool larcv::Voxel::operator< (const float & rhs) const inline
Definition at line 73 of file Voxel.h.
References _value.
     { return _value <  rhs; }
bool larcv::Voxel::operator<= (const Voxel & rhs) const inline
Definition at line 64 of file Voxel.h.
     { return  ((*this) == rhs || (*this) < rhs); }
bool larcv::Voxel::operator<= (const float & rhs) const inline
Definition at line 75 of file Voxel.h.
References _value.
     { return _value <= rhs; }
bool larcv::Voxel::operator== (const Voxel & rhs) const inline
Definition at line 56 of file Voxel.h.
References _id.
     { return (_id == rhs._id); }
bool larcv::Voxel::operator== (const float & rhs) const inline
Definition at line 71 of file Voxel.h.
References _value.
     { return _value == rhs; }
bool larcv::Voxel::operator> (const Voxel & rhs) const inline
Definition at line 66 of file Voxel.h.
     { return !((*this) <= rhs); }
bool larcv::Voxel::operator> (const float & rhs) const inline
Definition at line 77 of file Voxel.h.
References _value.
     { return _value >  rhs; }
bool larcv::Voxel::operator>= (const Voxel & rhs) const inline
Definition at line 68 of file Voxel.h.
     { return !((*this) <  rhs); }
bool larcv::Voxel::operator>= (const float & rhs) const inline
Definition at line 79 of file Voxel.h.
References _value.
     { return _value >= rhs; }
void larcv::Voxel::set (VoxelID_t id, float value) inline
Value setter.
Definition at line 39 of file Voxel.h.
References _id, _value, id(), and value().
 { _id = id; _value = value; }
float larcv::Voxel::value () const inline
Value getter.
Definition at line 36 of file Voxel.h.
References _value.
Referenced by operator+=(), operator-=(), set(), and Voxel().
 { return _value; }
Member Data Documentation
VoxelID_t larcv::Voxel::_id private
voxel id
Definition at line 83 of file Voxel.h.
Referenced by id(), operator<(), operator==(), set(), and Voxel().
float larcv::Voxel::_value private
Pixel Value.
Definition at line 84 of file Voxel.h.
Referenced by operator*=(), operator+=(), operator-=(), operator/=(), operator<(), operator<=(), operator==(), operator>(), operator>=(), set(), value(), and Voxel().
The documentation for this class was generated from the following files:
Voxel.h
Voxel.cxx