LArCV: larcv::DataProductFactory Class Reference
larcv::DataProductFactory Class Reference
Factory class for instantiating event product instance by larcv::IOManager This factory class can instantiate a specified product instance w/ provided producer name.
#include <DataProductFactory.h>
Public Member Functions
DataProductFactory ()
Default ctor, shouldn't be used.
~DataProductFactory ()
Default dtor.
void add_factory (std::string type, larcv::DataProductFactoryBase *factory)
Factory registration method (should be called by global factory instance in algorithm header)
EventBase * create (const std::string &type, const std::string &producer)
Factory creation method (should be called by clients, possibly you!)
EventBase * create (const ProducerName_t &id)
Factory creation method (should be called by clients, possibly you!)
void list () const
List registered products.
size_t unique_product_count () const
const std::vector< std::string > & product_names () const
const larcv::logger & logger () const
Logger getter.
void set_verbosity (::larcv::msg::Level_t level)
Verbosity level.
const std::string & name () const
Name getter, defined in a logger instance attribute.
Static Public Member Functions
static DataProductFactory & get ()
Static sharable instance getter.
Private Attributes
std::map< std::string,
larcv::DataProductFactoryBase * > _factory_map
Factory container.
std::vector< std::string > _id_to_type
Unique product type ID.
Static Private Attributes
static DataProductFactory * _me = nullptr
Static self.
Detailed Description
Factory class for instantiating event product instance by larcv::IOManager This factory class can instantiate a specified product instance w/ provided producer name.
The actual factory core (to which each product class must register creation factory instance) is
a static std::map. Use static method to get a static instance (larcv::DataProductFactory::get)
to access a factory.
Definition at line 49 of file DataProductFactory.h.
Constructor & Destructor Documentation
larcv::DataProductFactory::DataProductFactory () inline
Default ctor, shouldn't be used.
Definition at line 53 of file DataProductFactory.h.
Referenced by get().
                          : larcv_base("DataProductFactory")
     {}
larcv::DataProductFactory::~DataProductFactory () inline
Default dtor.
Definition at line 56 of file DataProductFactory.h.
References _factory_map.
 {_factory_map.clear();}
Member Function Documentation
void larcv::DataProductFactory::add_factory (std::string type, larcv::DataProductFactoryBase * factory)
Factory registration method (should be called by global factory instance in algorithm header)
Definition at line 10 of file DataProductFactory.cxx.
References _factory_map, _id_to_type, LARCV_CRITICAL, and LARCV_INFO.
Referenced by larcv::EventBBox2DFactory::EventBBox2DFactory(), larcv::EventBBox3DFactory::EventBBox3DFactory(), larcv::EventChStatusFactory::EventChStatusFactory(), larcv::EventClusterPixel2DFactory::EventClusterPixel2DFactory(), larcv::EventClusterVoxel3DFactory::EventClusterVoxel3DFactory(), larcv::EventImage2DFactory::EventImage2DFactory(), larcv::EventMetaFactory::EventMetaFactory(), larcv::EventParticleFactory::EventParticleFactory(), larcv::EventSparseTensor2DFactory::EventSparseTensor2DFactory(), and larcv::EventSparseTensor3DFactory::EventSparseTensor3DFactory().
   {
     if(type.empty()) {
       LARCV_CRITICAL() << "Attempted to register a data product type with empty name!" << std::endl
                << "Maybe a new data product source code was made by gen_class_product script?" << std::endl
                << "This error happens when that + forgotten implementation of product_unique_name<T> function (see the header!)" << std::endl
                << std::endl;
       throw larbys();
     }
     LARCV_INFO() << "Registering a factory " << factory << " of type " << type << std::endl;
     auto iter = _factory_map.find(type);
     if(iter != _factory_map.end()) {
       LARCV_CRITICAL() << "Attempted a duplicate registration of Data product "
                << type << " to a factory!" << std::endl;
       throw larbys();
     }
     _factory_map[type] = factory;
     _id_to_type.push_back(type);
   }
EventBase* larcv::DataProductFactory::create (const std::string & type, const std::string & producer) inline
Factory creation method (should be called by clients, possibly you!)
Definition at line 65 of file DataProductFactory.h.
Referenced by larcv::IOManager::register_producer().
{
       return create(ProducerName_t(type,producer));
     }
EventBase * larcv::DataProductFactory::create (const ProducerName_t & id)
Factory creation method (should be called by clients, possibly you!)
Definition at line 34 of file DataProductFactory.cxx.
References _factory_map, and LARCV_ERROR.
{
     auto iter = _factory_map.find(id.first);
     if(iter == _factory_map.end() || !((*iter).second)) {
       LARCV_ERROR() << "Found no registered class " << id.first << std::endl;
       return nullptr;
     }
     auto ptr = (*iter).second->create();
     ptr->_producer = id.second;
     return ptr;
   }
static DataProductFactory& larcv::DataProductFactory::get () inline static
Static sharable instance getter.
Definition at line 58 of file DataProductFactory.h.
References _me, and DataProductFactory().
Referenced by larcv::EventBBox2DFactory::EventBBox2DFactory(), larcv::EventBBox3DFactory::EventBBox3DFactory(), larcv::EventChStatusFactory::EventChStatusFactory(), larcv::EventClusterPixel2DFactory::EventClusterPixel2DFactory(), larcv::EventClusterVoxel3DFactory::EventClusterVoxel3DFactory(), larcv::EventImage2DFactory::EventImage2DFactory(), larcv::EventMetaFactory::EventMetaFactory(), larcv::EventParticleFactory::EventParticleFactory(), larcv::EventSparseTensor2DFactory::EventSparseTensor2DFactory(), larcv::EventSparseTensor3DFactory::EventSparseTensor3DFactory(), and larcv::IOManager::register_producer().
     { if(!_me) _me = new DataProductFactory; return *_me; }
void larcv::DataProductFactory::list () const
List registered products.
Definition at line 45 of file DataProductFactory.cxx.
References _factory_map, _id_to_type, and LARCV_NORMAL.
{
     std::stringstream ss;
     ss << "    Listing registered products:" << std::endl;
     for(size_t id=0; id<_id_to_type.size(); ++id) {
       ss << "    Name: " << _id_to_type[id]
      << " ... ID=" << id
      << " ... Factory @ " << _factory_map.find(_id_to_type[id])->second
      << std::endl;
     }
     ss << std::endl;
     LARCV_NORMAL() << ss.str() << std::endl;
   }
const larcv::logger& larcv::larcv_base::logger () const inline inherited
Logger getter.
Definition at line 43 of file larcv_base.h.
References larcv::larcv_base::_logger.
Referenced by larcv::ProcessDriver::configure(), and larcv::larcv_base::name().
     { return *_logger; }
const std::string& larcv::larcv_base::name () const inline inherited
Name getter, defined in a logger instance attribute.
Definition at line 51 of file larcv_base.h.
References larcv::larcv_base::logger(), and larcv::logger::name().
Referenced by larcv::ProcessFactory::add_factory(), larcv::ProcessDriver::configure(), larcv::ProcessFactory::create(), larcv::ProcessDriver::finalize(), larcv::IOManager::initialize(), larcv::IOManager::IOManager(), larcv::IOManager::set_out_file(), and larcv::PyImageStitcher::set_producer_name().
     { return logger().name(); }
const std::vector<std::string>& larcv::DataProductFactory::product_names () const inline
Definition at line 78 of file DataProductFactory.h.
References _id_to_type.
     { return _id_to_type; }
void larcv::larcv_base::set_verbosity (::larcv::msg::Level_t level) inline inherited
Verbosity level.
Definition at line 47 of file larcv_base.h.
References larcv::larcv_base::_logger, and larcv::logger::set().
Referenced by larcv::ProcessBase::_configure_(), larcv::ProcessDriver::configure(), and larcv::IOManager::configure().
     { _logger->set(level); }
size_t larcv::DataProductFactory::unique_product_count () const inline
Definition at line 75 of file DataProductFactory.h.
References _id_to_type.
     { return _id_to_type.size(); }
Member Data Documentation
std::map<std::string,larcv::DataProductFactoryBase*> larcv::DataProductFactory::_factory_map private
Factory container.
Definition at line 83 of file DataProductFactory.h.
Referenced by add_factory(), create(), list(), and ~DataProductFactory().
std::vector<std::string> larcv::DataProductFactory::_id_to_type private
Unique product type ID.
Definition at line 85 of file DataProductFactory.h.
Referenced by add_factory(), list(), product_names(), and unique_product_count().
larcv::DataProductFactory * larcv::DataProductFactory::_me = nullptr static private
Static self.
Definition at line 87 of file DataProductFactory.h.
Referenced by get().
The documentation for this class was generated from the following files:
DataProductFactory.h
DataProductFactory.cxx