LArCV: larcv Namespace Reference
larcv Namespace Reference
Core_Base | Core_DataFormat | Core_Processor | Core_PyUtil
C++ namespace for developping LArTPC software interface to computer vision software (LArCV)
Namespaces
chstatus
Channel status constants.
msg
Namespace for larcv message related types.
parser
Classes
class ConfigManager
Utility class to register a set of configurations Provides also a shared instance through which registered configurations can be shared beyond a single owner.
class larbys
Throw insignificant larbys when you find nonesense.
class larcv_base
Framework base class equipped with a logger class.
class logger
Utility class used to show formatted message on the screen.
class PSet
A nested configuration parameter set holder for larcv framework.
class Watch
a very simple stopwatch class for simple time measurement
class BBox2D
Bounding box in 2D.
class BBox3D
Bounding box in 3D.
class ChStatus
Data rep.
class DataProductFactoryBase
Abstract base class for factory (to be implemented per data product)
class DataProductFactory
Factory class for instantiating event product instance by larcv::IOManager This factory class can instantiate a specified product instance w/ provided producer name.
class EventBase
Base class for an event data product (what is stored in output file), holding run/subrun/event ID + producer name.
class EventBBox2D
Event-wise class to store a collection of larcv::BBox.
class EventBBox3D
Event-wise class to store a collection of larcv::BBox.
class EventBBox2DFactory
class EventBBox3DFactory
class EventChStatus
Event-wise class to store a collection of larcv::ChStatus (one per plane)
class EventChStatusFactory
class EventImage2D
Event-wise class to store a collection of larcv::Image2D.
class EventImage2DFactory
class EventMeta
User-defined data product class (please comment!)
class EventMetaFactory
class EventParticle
User-defined data product class (please comment!)
class EventParticleFactory
class EventClusterPixel2D
Event-wise class to store a collection of VoxelSet (cluster) per projection id.
class EventSparseTensor2D
Event-wise class to store a collection of VoxelSet (cluster) per projection id.
class EventClusterPixel2DFactory
class EventSparseTensor2DFactory
class EventClusterVoxel3D
Event-wise class to store a collection of VoxelSet (cluster) collection.
class EventSparseTensor3D
Event-wise class to store a collection of VoxelSet.
class EventClusterVoxel3DFactory
class EventSparseTensor3DFactory
class Image2D
Meant to be a storage class for an image into a ROOT file.
class ImageMeta
A simple class to store image's meta data including
0) origin (left-top corner of the picture) absolute coordinate
1) horizontal and vertical size (width and height) in double precision
2) number of horizontal and vertical pixels
It is meant to be associated with a specific cv::Mat or larcv::Image2D object
(where the latter class contains ImageMeta as an attribute).
class IOManager
LArCV file IO hanlder class: it can read/write LArCV file.
class Meta
A class to hold meta data that can be generated on the fly.
class Particle
Particle/Interaction-wise truth information data.
class ParticleSet
Particle/Interaction collection.
class Point2D
Simple 2D point struct (unit of "x" and "y" are not defined here and app specific)
class Point3D
Simple 3D point struct (unit of "x", "y" and "z" are not defined here and app specific)
class Vertex
class Voxel
3D voxel definition element class consisting of ID and stored value
class VoxelSet
Container of multiple voxels consisting of ordered sparse vector and meta data.
class VoxelSetArray
Container of multiple VoxelSet (i.e.
class SparseTensor2D
Container of multiple (2D-projected) voxel set array.
class ClusterPixel2D
Container of multiple (2D-projected) voxel set array.
class SparseTensor3D
Container of multiple (3D-projected) voxel set array.
class ClusterVoxel3D
Container of multiple (3D-projected) voxel set array.
class Voxel3DMeta
Meta data for defining voxels (ID, size, position) and voxelized volume (coordinate, size)
class ProcessBase
A base class for "process module" to be run by larcv::ProcessDriver Inherited class must implment 4 pure virtual functions that are called by larcv::ProcessDriver instance.
class ProcessDriver
Analysis event-loop driver that executes larcv::ProcessBase inherit "process modules".
class ProcessFactoryBase
Abstract base class for factory (to be implemented per process)
class ProcessFactory
Factory class for instantiating process instance This factory class can instantiate a specified process instance w/ provided instance name.
class load_pyutil
User defined class load_pyutil ...
class PyCluster3DMaker
class PyCluster3DMakerProcessFactory
class PyImageMaker
class PyImageMakerProcessFactory
class PyImageStitcher
class PyImageStitcherProcessFactory
class PyTensor3DMaker
class PyTensor3DMakerProcessFactory
class PyCluster3DMakerFactory
A concrete factory class for larcv::PyCluster3DMaker.
class PyImageMakerFactory
A concrete factory class for larcv::PyImageMaker.
class PyImageStitcherFactory
A concrete factory class for larcv::PyImageStitcher.
class PyTensor3DMakerFactory
A concrete factory class for larcv::PyTensor3DMaker.
Typedefs
typedef unsigned short ImageIndex_t
Image index type for Image2D within EventImage2D.
typedef unsigned short ParticleIndex_t
ROI index type for Particle within EventROI.
typedef unsigned short ProjectionID_t
Projection ID to distinguish different 2D projections.
typedef unsigned short MCSTIndex_t
"ID" of MCShower/MCTrack in terms of its index number in the collection std::vector
typedef unsigned short MCTIndex_t
"ID" of MCTruth in terms of its index number in the collection std::vector
typedef unsigned short InstanceID_t
"ID" for a set of elements
typedef unsigned long long VoxelID_t
"ID" for Voxel3D
typedef size_t MCTrackID_t
"ID" of MCParticles in terms of its G4 track ID (unless mixing multiple MC samples)
typedef std::set
< larcv::MCTrackID_t > MCTrackIDSet_t
A collection of MCTrackID_t for multiple MCParticles.
typedef size_t ProducerID_t
ProducerID_t to identify a unique data product within a process (for larcv::IOManager)
typedef std::pair< std::string,
std::string > ProducerName_t
ProductName_t to identify a unique data product within a process (for larcv::IOManager)
typedef size_t ProcessID_t
A unique identifier for an instantiated processes.
Enumerations
enum DistanceUnit_t { kUnitUnknown, kUnitCM, kUnitWireTime }
Coordinate unit type.
enum PoolType_t { kPoolSum, kPoolAverage, kPoolMax }
Pooling type.
enum ShapeType_t { kShapeShower, kShapeTrack, kShapeUnknown }
Object appearance type in LArTPC.
Functions
std::string ConfigFile2String (std::string fname)
Given a configuration string, format to create larcv::PSet.
PSet CreatePSetFromFile (std::string fname, std::string cfg_name="cfg")
Given a configuration file (full path), create and return larcv::PSet.
template<>
PSet PSet::get< larcv::PSet > (const std::string &key) const
larcv::Image2D as_image2d (const SparseTensor2D &tensor)
Algorithm to convert SparseTensor2D into Image2d.
larcv::Image2D as_image2d (const VoxelSet &tensor, const ImageMeta &meta)
Algorithm to convert VoxelSet and ImagMeta into Image2d.
larcv::SparseTensor2D as_sparse_tensor2d (const ClusterPixel2D &clusters)
Algorithm to convert ClusterPixel2D into SparseTensor2D.
larcv::Image2D as_image2d (const ClusterPixel2D &clusters)
Algorithm to convert ClusterPixel2D into Image2D.
larcv::SparseTensor3D as_sparse_tensor3d (const ClusterVoxel3D &clusters)
Algorithm to convert ClusterVoxel3D into SparseTensor3D.
template<class T >
std::string product_unique_name ()
template<>
std::string product_unique_name< larcv::EventBBox2D > ()
template EventBBox2D & IOManager::get_data< larcv::EventBBox2D > (const std::string &)
template EventBBox2D & IOManager::get_data< larcv::EventBBox2D > (const ProducerID_t)
template<>
std::string product_unique_name< larcv::EventBBox3D > ()
template EventBBox3D & IOManager::get_data< larcv::EventBBox3D > (const std::string &)
template EventBBox3D & IOManager::get_data< larcv::EventBBox3D > (const ProducerID_t)
template<>
std::string product_unique_name< larcv::EventChStatus > ()
template EventChStatus & IOManager::get_data< larcv::EventChStatus > (const std::string &)
template EventChStatus & IOManager::get_data< larcv::EventChStatus > (const ProducerID_t)
template<>
std::string product_unique_name< larcv::EventImage2D > ()
template EventImage2D & IOManager::get_data< larcv::EventImage2D > (const std::string &)
template EventImage2D & IOManager::get_data< larcv::EventImage2D > (const ProducerID_t)
template<>
std::string product_unique_name< larcv::EventMeta > ()
template EventMeta & IOManager::get_data< larcv::EventMeta > (const std::string &)
template EventMeta & IOManager::get_data< larcv::EventMeta > (const ProducerID_t)
template<>
std::string product_unique_name< larcv::EventParticle > ()
template EventParticle & IOManager::get_data< larcv::EventParticle > (const std::string &)
template EventParticle & IOManager::get_data< larcv::EventParticle > (const ProducerID_t)
template<>
std::string product_unique_name< larcv::EventClusterPixel2D > ()
template EventClusterPixel2D & IOManager::get_data< larcv::EventClusterPixel2D > (const std::string &)
template EventClusterPixel2D & IOManager::get_data< larcv::EventClusterPixel2D > (const ProducerID_t)
template<>
std::string product_unique_name< larcv::EventSparseTensor2D > ()
template EventSparseTensor2D & IOManager::get_data< larcv::EventSparseTensor2D > (const std::string &)
template EventSparseTensor2D & IOManager::get_data< larcv::EventSparseTensor2D > (const ProducerID_t)
template<>
std::string product_unique_name< larcv::EventClusterVoxel3D > ()
template EventClusterVoxel3D & IOManager::get_data< larcv::EventClusterVoxel3D > (const std::string &)
template EventClusterVoxel3D & IOManager::get_data< larcv::EventClusterVoxel3D > (const ProducerID_t)
template<>
std::string product_unique_name< larcv::EventSparseTensor3D > ()
template EventSparseTensor3D & IOManager::get_data< larcv::EventSparseTensor3D > (const std::string &)
template EventSparseTensor3D & IOManager::get_data< larcv::EventSparseTensor3D > (const ProducerID_t)
double ParticleMass (const int pdgcode)
Utility to get a particle mass.
static const larcv::Voxel kINVALID_VOXEL (kINVALID_VOXELID, 0.)
void SetPyUtil ()
A utility function: call one-time-only numpy module initialization (you don't have to call)
PyObject * as_ndarray (const std::vector< float > &data)
std::vector<float> to numpy array converter
PyObject * as_ndarray (const Image2D &img)
larcv::Image2D to numpy array converter
void copy_array (PyObject *arrayin, const std::vector< float > &cvec)
copy 1D array (std::vector<float> to 1D numpy array float32 type)
PyObject * as_caffe_ndarray (const Image2D &img)
larcv::Image2D to numpy array converter
larcv::Image2D as_image2d_meta (PyObject *, ImageMeta meta)
Generate Image2D object with provided 2D numpy array and ImageMeta.
larcv::Image2D as_image2d (PyObject *)
Generate Image2D object with provided 2D numpy array (ImageMeta made with height=rows and width=cols)
VoxelSet as_tensor3d (PyObject *, float min_threshold=0)
Generate VoxelSet from 3D numpy array. Entries with value < min_threshold is ignored.
void fill_img_col (Image2D &img, std::vector< short > &adcs, const int col, const float pedestal=0.0)
allows one to avoid some loops in python
Variables
const long long kINVALID_LONGLONG = std::numeric_limits< long long >::max()
Used as an invalid value identifier for long long.
const unsigned long long kINVALID_ULONGLONG = std::numeric_limits< unsigned long long >::max()
Used as an invalid value identifier for unsigned long long.
const size_t kINVALID_SIZE = std::numeric_limits< size_t >::max()
Used as an invalid value identifier for size_t.
const int kINVALID_INT = std::numeric_limits< int >::max()
Used as an invalid value identifier for int.
const unsigned int kINVALID_UINT = std::numeric_limits< unsigned int >::max()
Used as an invalid value identifier for unsigned int.
const short kINVALID_SHORT = std::numeric_limits< short >::max()
Used as an invalid value identifier for unsigned short.
const unsigned short kINVALID_USHORT = std::numeric_limits< unsigned short >::max()
Used as an invalid value identifier for unsigned unsigned short.
const float kINVALID_FLOAT = std::numeric_limits< float >::max()
Used as an invalid value idnetifier for single-point precision.
const double kINVALID_DOUBLE = std::numeric_limits< double >::max()
Used as an invalid value idnetifier for double-point precision.
static const unsigned short kINVALID_INDEX = kINVALID_USHORT
Invalid rep for vector index.
static const unsigned short kINVALID_INSTANCEID = kINVALID_USHORT
Invalid rep for InstanceID_t.
static const ProjectionID_t kINVALID_PROJECTIONID = kINVALID_USHORT
Invalid projection id.
static const VoxelID_t kINVALID_VOXELID = kINVALID_ULONGLONG
Invalid Voxel3DID_t definition.
static const ProducerID_t kINVALID_PRODUCER =kINVALID_SIZE
Invalid ProducerID_t.
static EventBBox2DFactory __global_EventBBox2DFactory__
static EventBBox3DFactory __global_EventBBox3DFactory__
static EventChStatusFactory __global_EventChStatusFactory__
Global larcv::SBClusterFactory to register ClusterAlgoFactory.
static EventImage2DFactory __global_EventImage2DFactory__
Global larcv::SBClusterFactory to register ClusterAlgoFactory.
static EventMetaFactory __global_EventMetaFactory__
Global larcv::SBClusterFactory to register ClusterAlgoFactory.
static EventParticleFactory __global_EventParticleFactory__
Global larcv::SBClusterFactory to register ClusterAlgoFactory.
static EventClusterPixel2DFactory __global_EventClusterPixel2DFactory__
Global larcv::EventClusterPixel2DFactory to register EventClusterPixel2D.
static EventSparseTensor2DFactory __global_EventSparseTensor2DFactory__
Global larcv::EventSparseTensor2DFactory to register EventSparseTensor2D.
static EventClusterVoxel3DFactory __global_EventClusterVoxel3DFactory__
Global larcv::EventClusterPixel3DFactory to register EventClusterPixel3D.
static EventSparseTensor3DFactory __global_EventSparseTensor3DFactory__
Global larcv::EventSparseTensor3DFactory to register EventSparseTensor3D.
static
PyCluster3DMakerProcessFactory __global_PyCluster3DMakerProcessFactory__
static PyImageMakerProcessFactory __global_PyImageMakerProcessFactory__
static
PyImageStitcherProcessFactory __global_PyImageStitcherProcessFactory__
static
PyTensor3DMakerProcessFactory __global_PyTensor3DMakerProcessFactory__
Detailed Description
C++ namespace for developping LArTPC software interface to computer vision software (LArCV)
Typedef Documentation
typedef unsigned short larcv::ImageIndex_t
Image index type for Image2D within EventImage2D.
Definition at line 12 of file DataFormatTypes.h.
typedef unsigned short larcv::InstanceID_t
"ID" for a set of elements
Definition at line 22 of file DataFormatTypes.h.
typedef unsigned short larcv::MCSTIndex_t
"ID" of MCShower/MCTrack in terms of its index number in the collection std::vector
Definition at line 18 of file DataFormatTypes.h.
typedef unsigned short larcv::MCTIndex_t
"ID" of MCTruth in terms of its index number in the collection std::vector
Definition at line 20 of file DataFormatTypes.h.
typedef size_t larcv::MCTrackID_t
"ID" of MCParticles in terms of its G4 track ID (unless mixing multiple MC samples)
Definition at line 70 of file DataFormatTypes.h.
typedef std::set<larcv::MCTrackID_t> larcv::MCTrackIDSet_t
A collection of MCTrackID_t for multiple MCParticles.
Definition at line 72 of file DataFormatTypes.h.
typedef unsigned short larcv::ParticleIndex_t
ROI index type for Particle within EventROI.
Definition at line 14 of file DataFormatTypes.h.
typedef size_t larcv::ProcessID_t
A unique identifier for an instantiated processes.
Definition at line 6 of file ProcessorTypes.h.
typedef size_t larcv::ProducerID_t
ProducerID_t to identify a unique data product within a process (for larcv::IOManager)
Definition at line 75 of file DataFormatTypes.h.
typedef std::pair<std::string,std::string> larcv::ProducerName_t
ProductName_t to identify a unique data product within a process (for larcv::IOManager)
Definition at line 77 of file DataFormatTypes.h.
typedef unsigned short larcv::ProjectionID_t
Projection ID to distinguish different 2D projections.
Definition at line 16 of file DataFormatTypes.h.
typedef unsigned long long larcv::VoxelID_t
"ID" for Voxel3D
Definition at line 29 of file DataFormatTypes.h.
Enumeration Type Documentation
enum larcv::DistanceUnit_t
Coordinate unit type.
Enumerator
kUnitUnknown
undefined scale (bad!)
kUnitCM
cm scale
kUnitWireTime
wire/time in 2D image
Definition at line 49 of file DataFormatTypes.h.
                       {
     kUnitUnknown,
     kUnitCM,
     kUnitWireTime
   };
enum larcv::PoolType_t
Pooling type.
Enumerator
kPoolSum
sum channels
kPoolAverage
average over channels
kPoolMax
max channel
Definition at line 56 of file DataFormatTypes.h.
                   {
     kPoolSum,
     kPoolAverage,
     kPoolMax
   };
enum larcv::ShapeType_t
Object appearance type in LArTPC.
Enumerator
kShapeShower
Shower.
kShapeTrack
Track.
kShapeUnknown
LArbys.
Definition at line 63 of file DataFormatTypes.h.
                    {
     kShapeShower,
     kShapeTrack,
     kShapeUnknown
   };
Function Documentation
PyObject * larcv::as_caffe_ndarray (const Image2D & img)
larcv::Image2D to numpy array converter
Definition at line 72 of file PyUtils.cxx.
References larcv::Image2D::as_vector(), larcv::ImageMeta::cols(), larcv::Image2D::meta(), larcv::ImageMeta::rows(), and SetPyUtil().
{
   SetPyUtil();
   npy_intp dim_data[2];
   dim_data[0] = img.meta().rows();
   dim_data[1] = img.meta().cols();
   auto const &vec = img.as_vector();
   return PyArray_SimpleNewFromData(2, dim_data, NPY_FLOAT, (char *)&(vec[0]));
 }
larcv::Image2D larcv::as_image2d (const SparseTensor2D & tensor)
Algorithm to convert SparseTensor2D into Image2d.
Definition at line 8 of file ClusterTensorUtils.cxx.
Referenced by larcv::PyImageMaker::append_ndarray(), and larcv::PyImageStitcher::append_ndarray().
   { return as_image2d((VoxelSet)tensor,tensor.meta()); }
larcv::Image2D larcv::as_image2d (const VoxelSet & tensor, const ImageMeta & meta)
Algorithm to convert VoxelSet and ImagMeta into Image2d.
Definition at line 11 of file ClusterTensorUtils.cxx.
References larcv::VoxelSet::as_vector(), and larcv::ImageMeta::size().
   {
     std::vector<float> data(meta.size(),0.);
     for(auto const& voxel : tensor.as_vector())
       data[voxel.id()] = voxel.value();
     return Image2D(std::move(ImageMeta(meta)),std::move(data));
   }
larcv::Image2D larcv::as_image2d (const ClusterPixel2D & clusters)
Algorithm to convert ClusterPixel2D into Image2D.
Definition at line 30 of file ClusterTensorUtils.cxx.
References larcv::VoxelSetArray::as_vector(), larcv::ClusterPixel2D::meta(), and larcv::ImageMeta::size().
   {
     std::vector<float> data(clusters.meta().size(),0.);
     for(auto const& cluster : clusters.as_vector()) {
       for(auto const& voxel : cluster.as_vector())
     { data[voxel.id()] = voxel.value(); }
     }
     return Image2D(std::move(ImageMeta(clusters.meta())),std::move(data));
   }
Image2D larcv::as_image2d (PyObject * pyarray)
Generate Image2D object with provided 2D numpy array (ImageMeta made with height=rows and width=cols)
Definition at line 106 of file PyUtils.cxx.
References larcv::logger::get(), larcv::msg::kCRITICAL, kINVALID_PROJECTIONID, larcv::logger::send(), and SetPyUtil().
{
   SetPyUtil();
   float **carray;
   // Create C arrays from numpy objects:
   const int dtype = NPY_FLOAT;
   PyArray_Descr *descr = PyArray_DescrFromType(dtype);
   npy_intp dims[2];
   if (PyArray_AsCArray(&pyarray, (void **)&carray, dims, 2, descr) < 0) {
     logger::get("PyUtil").send(larcv::msg::kCRITICAL, __FUNCTION__, __LINE__,
                                "ERROR: cannot convert to 2D C-array\n");
     throw larbys();
   }
   std::vector<float> res_data(dims[0] * dims[1], 0.);
   for (int i = 0; i < dims[0]; ++i) {
     for (int j = 0; j < dims[1]; ++j) {
       res_data[i + j * dims[0]] = (float)(carray[i][j]);
     }
   }
   PyArray_Free(pyarray, (void *)carray);
   ImageMeta meta(0., 0., (double)(dims[0]), (double)(dims[1]),
                  (size_t)(dims[0]),
                  (size_t)(dims[1]),
                  larcv::kINVALID_PROJECTIONID);
   Image2D res(std::move(meta), std::move(res_data));
   return res;
 }
Image2D larcv::as_image2d_meta (PyObject * pyarray, ImageMeta meta)
Generate Image2D object with provided 2D numpy array and ImageMeta.
Definition at line 81 of file PyUtils.cxx.
References larcv::logger::get(), larcv::msg::kCRITICAL, larcv::logger::send(), and SetPyUtil().
Referenced by larcv::PyImageMaker::append_ndarray_meta(), and larcv::PyImageStitcher::append_ndarray_meta().
{
   SetPyUtil();
   float **carray;
   // Create C arrays from numpy objects:
   const int dtype = NPY_FLOAT;
   PyArray_Descr *descr = PyArray_DescrFromType(dtype);
   npy_intp dims[2];
   if (PyArray_AsCArray(&pyarray, (void **)&carray, dims, 2, descr) < 0) {
     logger::get("PyUtil").send(larcv::msg::kCRITICAL, __FUNCTION__, __LINE__,
                                "ERROR: cannot convert to 2D C-array");
     throw larbys();
   }
   std::vector<float> res_data(dims[0] * dims[1], 0.);
   for (int i = 0; i < dims[0]; ++i) {
     for (int j = 0; j < dims[1]; ++j) {
       res_data[i + j * dims[0]] = (float)(carray[i][j]);
     }
   }
   PyArray_Free(pyarray, (void *)carray);
   Image2D res(std::move(meta), std::move(res_data));
   return res;
 }
PyObject * larcv::as_ndarray (const std::vector< float > & vec)
std::vector<float> to numpy array converter
Definition at line 20 of file PyUtils.cxx.
References LARCV_CRITICAL, and SetPyUtil().
{
   SetPyUtil();
   if (vec.size() >= INT_MAX) {
     LARCV_CRITICAL() << "Length of data vector too long to specify ndarray. "
                         "Use by batch call."
                      << std::endl;
     throw larbys();
   }
   int nd = 1;
   npy_intp dims[1];
   dims[0] = (int)vec.size();
   PyArrayObject *array = (PyArrayObject *)PyArray_SimpleNewFromData(
       nd, dims, NPY_FLOAT, (char *)&(vec[0]));
   return PyArray_Return(array);
 }
PyObject * larcv::as_ndarray (const Image2D & img)
larcv::Image2D to numpy array converter
Definition at line 37 of file PyUtils.cxx.
References larcv::Image2D::as_vector(), larcv::ImageMeta::cols(), larcv::Image2D::meta(), larcv::ImageMeta::rows(), and SetPyUtil().
{
   SetPyUtil();
   npy_intp dim_data[2];
   dim_data[0] = img.meta().cols();
   dim_data[1] = img.meta().rows();
   auto const &vec = img.as_vector();
   return PyArray_Transpose(((PyArrayObject*)(PyArray_SimpleNewFromData(2, dim_data, NPY_FLOAT, (char *)&(vec[0])))),NULL);
   //return PyArray_FromDimsAndData(2, dim_data, NPY_FLOAT, (char *)&(vec[0]));
 }
larcv::SparseTensor2D larcv::as_sparse_tensor2d (const ClusterPixel2D & clusters)
Algorithm to convert ClusterPixel2D into SparseTensor2D.
Definition at line 20 of file ClusterTensorUtils.cxx.
References larcv::VoxelSet::add(), larcv::VoxelSetArray::as_vector(), and larcv::ClusterPixel2D::meta().
   {
     VoxelSet vs;
     for(auto const& cluster : clusters.as_vector()) {
       for(auto const& voxel : cluster.as_vector())
     { vs.add(voxel); }
     }
     return SparseTensor2D(std::move(vs),std::move(ImageMeta(clusters.meta())));
   }
larcv::SparseTensor3D larcv::as_sparse_tensor3d (const ClusterVoxel3D & clusters)
Algorithm to convert ClusterVoxel3D into SparseTensor3D.
Definition at line 41 of file ClusterTensorUtils.cxx.
References larcv::VoxelSet::add(), larcv::VoxelSetArray::as_vector(), and larcv::ClusterVoxel3D::meta().
   {
     VoxelSet vs;
     for(auto const& cluster : clusters.as_vector()) {
       for(auto const& voxel : cluster.as_vector())
     { vs.add(voxel); }
     }
     return SparseTensor3D(std::move(vs),std::move(Voxel3DMeta(clusters.meta())));
   }
VoxelSet larcv::as_tensor3d (PyObject * pyarray, float min_threshold)
Generate VoxelSet from 3D numpy array. Entries with value < min_threshold is ignored.
Definition at line 136 of file PyUtils.cxx.
References larcv::VoxelSet::emplace(), LARCV_CRITICAL, and SetPyUtil().
Referenced by larcv::PyCluster3DMaker::append_ndarray(), and larcv::PyTensor3DMaker::append_ndarray().
{
   SetPyUtil();
   float ***carray;
   // Create C arrays from numpy objects:
   const int dtype = NPY_FLOAT;
   PyArray_Descr *descr = PyArray_DescrFromType(dtype);
   npy_intp dims[3];
   int ret = PyArray_AsCArray(&pyarray, (void***)&carray, dims, 3, descr);
   if ( ret < 0) {
     LARCV_CRITICAL() << "Cannot convert to 3D C-array (return code " << ret << ")" << std::endl;
     throw larbys();
   }
   VoxelSet res;
   float val=0.;
   size_t id = 0;
   for (int i = 0; i < dims[0]; ++i) {
     for (int j = 0; j < dims[1]; ++j) {
       for (int k = 0; k < dims[2]; ++k) {
         val = (float)(carray[i][j][k]);
         if(val <= min_threshold) continue;
         id = i * dims[1] * dims[2] + j * dims[2] + k;
         res.emplace(id,val,true);
       }
     }
   }
   PyArray_Free(pyarray, (void *)carray);
   return res;
 }
std::string larcv::ConfigFile2String (std::string fname)
Given a configuration string, format to create larcv::PSet.
Given a configuration file (full path), read & parse contents to create larcv::PSet
Definition at line 9 of file LArCVBaseUtilFunc.cxx.
Referenced by CreatePSetFromFile().
   {
     std::ifstream filestrm(fname.c_str());
     std::string   contents;
     std::string   line;
     while(std::getline(filestrm, line)) {
       if(line.empty()) continue;
       std::stringstream linestrm(line);
       std::string       valid_line;
       std::getline(linestrm, valid_line, '#');
       if(valid_line.empty()) continue;
       contents += " " + valid_line;
     }
     filestrm.close();
     return contents;
   }
void larcv::copy_array (PyObject * arrayin, const std::vector< float > & cvec)
copy 1D array (std::vector<float> to 1D numpy array float32 type)
Definition at line 47 of file PyUtils.cxx.
References SetPyUtil().
{
   SetPyUtil();
   PyArrayObject *ptr = (PyArrayObject *)(arrayin);
   /*
   std::cout<< PyArray_NDIM(ptr) << std::endl
            << PyArray_DIM(ptr,0)<<std::endl
            << PyArray_SIZE(ptr) << std::endl;
   */
   // Check dimension size is 1:
   if (PyArray_NDIM(ptr) != 1){
     throw std::exception();
   }
   if ((long)(cvec.size()) != PyArray_SIZE(ptr))
     throw std::exception();
   npy_intp loc[1];
   loc[0] = 0;
   auto fptr = (float *)(PyArray_GetPtr(ptr, loc));
   for (size_t i = 0; i < size_t(PyArray_SIZE(ptr)); ++i) {
     // std::cout << fptr[i] << std::endl;
     fptr[i] = cvec[i];
   };
 }
PSet larcv::CreatePSetFromFile (std::string fname, std::string cfg_name)
Given a configuration file (full path), create and return larcv::PSet.
Definition at line 32 of file LArCVBaseUtilFunc.cxx.
References ConfigFile2String().
Referenced by larcv::ConfigManager::AddConfigFile(), larcv::ProcessDriver::configure(), and larcv::IOManager::IOManager().
   {
     PSet res(cfg_name,ConfigFile2String(fname));
     return res;
   }
void larcv::fill_img_col (Image2D & img, std::vector< short > & adcs, const int col, const float pedestal)
allows one to avoid some loops in python
Definition at line 166 of file PyUtils.cxx.
References larcv::ImageMeta::cols(), larcv::BBox2D::max_y(), larcv::Image2D::meta(), larcv::BBox2D::min_y(), larcv::Image2D::pixel(), larcv::ImageMeta::row(), and larcv::Image2D::set_pixel().
 {
   if (col < 0 || col >= (long)(img.meta().cols()))
     return;
   for (int iadc = 0; iadc < (int)adcs.size(); iadc++) {
     if (iadc <= img.meta().min_y() || iadc >= img.meta().max_y())
       continue;
     int irow = img.meta().row(iadc);
     float val = img.pixel(irow, col);
     img.set_pixel(irow, col, val + ((float)adcs.at(iadc) - pedestal));
   }
 }
template EventBBox2D& larcv::IOManager::get_data< larcv::EventBBox2D > (const std::string &)
template EventBBox2D& larcv::IOManager::get_data< larcv::EventBBox2D > (const ProducerID_t)
template EventBBox3D& larcv::IOManager::get_data< larcv::EventBBox3D > (const std::string &)
template EventBBox3D& larcv::IOManager::get_data< larcv::EventBBox3D > (const ProducerID_t)
template EventChStatus& larcv::IOManager::get_data< larcv::EventChStatus > (const std::string &)
template EventChStatus& larcv::IOManager::get_data< larcv::EventChStatus > (const ProducerID_t)
template EventClusterPixel2D& larcv::IOManager::get_data< larcv::EventClusterPixel2D > (const std::string &)
template EventClusterPixel2D& larcv::IOManager::get_data< larcv::EventClusterPixel2D > (const ProducerID_t)
template EventClusterVoxel3D& larcv::IOManager::get_data< larcv::EventClusterVoxel3D > (const std::string &)
template EventClusterVoxel3D& larcv::IOManager::get_data< larcv::EventClusterVoxel3D > (const ProducerID_t)
template EventImage2D& larcv::IOManager::get_data< larcv::EventImage2D > (const std::string &)
template EventImage2D& larcv::IOManager::get_data< larcv::EventImage2D > (const ProducerID_t)
template EventMeta& larcv::IOManager::get_data< larcv::EventMeta > (const std::string &)
template EventMeta& larcv::IOManager::get_data< larcv::EventMeta > (const ProducerID_t)
template EventParticle& larcv::IOManager::get_data< larcv::EventParticle > (const std::string &)
template EventParticle& larcv::IOManager::get_data< larcv::EventParticle > (const ProducerID_t)
template EventSparseTensor2D& larcv::IOManager::get_data< larcv::EventSparseTensor2D > (const std::string &)
template EventSparseTensor2D& larcv::IOManager::get_data< larcv::EventSparseTensor2D > (const ProducerID_t)
template EventSparseTensor3D& larcv::IOManager::get_data< larcv::EventSparseTensor3D > (const std::string &)
template EventSparseTensor3D& larcv::IOManager::get_data< larcv::EventSparseTensor3D > (const ProducerID_t)
static const larcv::Voxel larcv::kINVALID_VOXEL (kINVALID_VOXELID , 0.) static
Referenced by larcv::VoxelSet::find().
double larcv::ParticleMass (const int pdgcode)
Utility to get a particle mass.
Definition at line 10 of file ParticleMass.cxx.
   {
     switch(pdgcode) {
       // electron
     case  11:
     case -11:
       return 0.510998910;
       // muon
     case  13:
     case -13:
       return 105.65838934;
       // gamma
     case 22:
       return 0.0;
       // neutrinos
     case 12:
     case 14:
       return 0.0;
       // proton
     case  2212:
     case -2212:
       return 938.272046;
       // neutron
     case  2112:
     case -2112:
       return 939.565378;
       // pi0
     case  111:
       return 134.9766;
       // pi +/-
     case  211:
     case -211:
       return 139.57018;
       // K0/K0L/K0S
     case  311:
     case  130:
     case  310:
       return 497.648;
       // K +/-
     case  321:
     case -321:
       return 493.667;
       // Delta
     case  2114:
     case  2214:
     case  2224:
     case  1114:
       return 1232.0;
       // Lambda
     case  3122:
     case -3122:
       return 1115.683;
       // Sigma+
     case  3222:
     case -3222:
       return 1189.37;
       // Sigma0
     case  3212:
     case -3212:
       return 1192.642;
       // Sigma-
     case  3112:
     case -3112:
       return 1197.449;
       // Xi0
     case  3322:
       return 1314.86;
       // Xi-/Xi+
     case  3312:
     case -3312:
       return 1321.71;
       // rho-0
     case  113:
       return 775.49;
       // rho-+
     case  123:
       return 775.4;
       // phi
     case  333:
       return 1019.445;
       // eta
     case  221:
       return 547.862;
       // eta'
     case  331:
       return 957.78;
       // deuteron
     case  1000010020:
       return 1875.6;
       // tritium
     case  1000010030:
       return 2829.87;
       // Helium 3
     case  1000020030:
       return 2829.85;
       // Helium 4
     case  1000020040:
       return 3755.53;
       // Berylium 8
     case  1000040080:
       return 7511.15;
     default:
       std::stringstream msg;
       msg << "PDG Code " << pdgcode << " is not handled yet! Please implement :) ";
       throw larbys(msg.str());
     }
     return -1;
   }
template<class T > std::string larcv::product_unique_name ()
template<> std::string larcv::product_unique_name< larcv::EventBBox2D > () inline
Definition at line 81 of file EventBBox.h.
 { return "bbox2d"; }
template<> std::string larcv::product_unique_name< larcv::EventBBox3D > () inline
Definition at line 101 of file EventBBox.h.
 { return "bbox3d"; }
template<> std::string larcv::product_unique_name< larcv::EventChStatus > () inline
Definition at line 70 of file EventChStatus.h.
 { return "chstatus"; }
template<> std::string larcv::product_unique_name< larcv::EventClusterPixel2D > () inline
Definition at line 116 of file EventVoxel2D.h.
 { return "cluster2d"; }
template<> std::string larcv::product_unique_name< larcv::EventClusterVoxel3D > () inline
Definition at line 69 of file EventVoxel3D.h.
 { return "cluster3d"; }
template<> std::string larcv::product_unique_name< larcv::EventImage2D > () inline
Definition at line 73 of file EventImage2D.h.
 { return "image2d"; }
template<> std::string larcv::product_unique_name< larcv::EventMeta > () inline
Definition at line 47 of file EventMeta.h.
 { return "meta"; }
template<> std::string larcv::product_unique_name< larcv::EventParticle > () inline
Definition at line 48 of file EventParticle.h.
 { return "particle"; }
template<> std::string larcv::product_unique_name< larcv::EventSparseTensor2D > () inline
Definition at line 136 of file EventVoxel2D.h.
 { return "sparse2d"; }
template<> std::string larcv::product_unique_name< larcv::EventSparseTensor3D > () inline
Definition at line 89 of file EventVoxel3D.h.
 { return "sparse3d"; }
template<> PSet larcv::PSet::get< larcv::PSet > (const std::string & key) const
Definition at line 369 of file PSet.cxx.
   { return this->get_pset(key); }
void larcv::SetPyUtil ()
A utility function: call one-time-only numpy module initialization (you don't have to call)
Definition at line 12 of file PyUtils.cxx.
Referenced by as_caffe_ndarray(), as_image2d(), as_image2d_meta(), as_ndarray(), as_tensor3d(), and copy_array().
                  {
   static bool once = false;
   if (!once) {
     import_array();
     once = true;
   }
 }
Variable Documentation
EventBBox2DFactory larcv::__global_EventBBox2DFactory__ static
Definition at line 8 of file EventBBox.cxx.
EventBBox3DFactory larcv::__global_EventBBox3DFactory__ static
Definition at line 10 of file EventBBox.cxx.
EventChStatusFactory larcv::__global_EventChStatusFactory__ static
Global larcv::SBClusterFactory to register ClusterAlgoFactory.
Definition at line 10 of file EventChStatus.cxx.
EventClusterPixel2DFactory larcv::__global_EventClusterPixel2DFactory__ static
Global larcv::EventClusterPixel2DFactory to register EventClusterPixel2D.
Definition at line 9 of file EventVoxel2D.cxx.
EventClusterVoxel3DFactory larcv::__global_EventClusterVoxel3DFactory__ static
Global larcv::EventClusterPixel3DFactory to register EventClusterPixel3D.
Definition at line 9 of file EventVoxel3D.cxx.
EventImage2DFactory larcv::__global_EventImage2DFactory__ static
Global larcv::SBClusterFactory to register ClusterAlgoFactory.
Definition at line 10 of file EventImage2D.cxx.
EventMetaFactory larcv::__global_EventMetaFactory__ static
Global larcv::SBClusterFactory to register ClusterAlgoFactory.
Definition at line 8 of file EventMeta.cxx.
EventParticleFactory larcv::__global_EventParticleFactory__ static
Global larcv::SBClusterFactory to register ClusterAlgoFactory.
Definition at line 8 of file EventParticle.cxx.
EventSparseTensor2DFactory larcv::__global_EventSparseTensor2DFactory__ static
Global larcv::EventSparseTensor2DFactory to register EventSparseTensor2D.
Definition at line 12 of file EventVoxel2D.cxx.
EventSparseTensor3DFactory larcv::__global_EventSparseTensor3DFactory__ static
Global larcv::EventSparseTensor3DFactory to register EventSparseTensor3D.
Definition at line 12 of file EventVoxel3D.cxx.
PyCluster3DMakerProcessFactory larcv::__global_PyCluster3DMakerProcessFactory__ static
Definition at line 9 of file PyCluster3DMaker.cxx.
PyImageMakerProcessFactory larcv::__global_PyImageMakerProcessFactory__ static
Definition at line 9 of file PyImageMaker.cxx.
PyImageStitcherProcessFactory larcv::__global_PyImageStitcherProcessFactory__ static
Definition at line 9 of file PyImageStitcher.cxx.
PyTensor3DMakerProcessFactory larcv::__global_PyTensor3DMakerProcessFactory__ static
Definition at line 9 of file PyTensor3DMaker.cxx.
const double larcv::kINVALID_DOUBLE = std::numeric_limits< double >::max()
Used as an invalid value idnetifier for double-point precision.
Definition at line 52 of file LArCVTypes.h.
const float larcv::kINVALID_FLOAT = std::numeric_limits< float >::max()
Used as an invalid value idnetifier for single-point precision.
Definition at line 50 of file LArCVTypes.h.
const unsigned short larcv::kINVALID_INDEX = kINVALID_USHORT static
Invalid rep for vector index.
Definition at line 10 of file DataFormatTypes.h.
const unsigned short larcv::kINVALID_INSTANCEID = kINVALID_USHORT static
Invalid rep for InstanceID_t.
Definition at line 24 of file DataFormatTypes.h.
const int larcv::kINVALID_INT = std::numeric_limits< int >::max()
Used as an invalid value identifier for int.
Definition at line 42 of file LArCVTypes.h.
const long long larcv::kINVALID_LONGLONG = std::numeric_limits< long long >::max()
Used as an invalid value identifier for long long.
Definition at line 36 of file LArCVTypes.h.
const ProducerID_t larcv::kINVALID_PRODUCER =kINVALID_SIZE static
Invalid ProducerID_t.
Definition at line 79 of file DataFormatTypes.h.
Referenced by larcv::IOManager::producer_id().
const ProjectionID_t larcv::kINVALID_PROJECTIONID = kINVALID_USHORT static
Invalid projection id.
Definition at line 26 of file DataFormatTypes.h.
Referenced by as_image2d().
const short larcv::kINVALID_SHORT = std::numeric_limits< short >::max()
Used as an invalid value identifier for unsigned short.
Definition at line 46 of file LArCVTypes.h.
const size_t larcv::kINVALID_SIZE = std::numeric_limits< size_t >::max()
Used as an invalid value identifier for size_t.
Definition at line 40 of file LArCVTypes.h.
Referenced by larcv::EventBase::clear(), larcv::IOManager::get_data(), larcv::PyImageMaker::initialize(), larcv::PyImageStitcher::initialize(), larcv::PyTensor3DMaker::initialize(), larcv::PyCluster3DMaker::initialize(), larcv::IOManager::prepare_input(), larcv::PyImageMaker::process(), larcv::PyImageStitcher::process(), larcv::IOManager::read_entry(), larcv::IOManager::register_producer(), larcv::Voxel3DMeta::update(), and larcv::EventBase::valid().
const unsigned int larcv::kINVALID_UINT = std::numeric_limits< unsigned int >::max()
Used as an invalid value identifier for unsigned int.
Definition at line 44 of file LArCVTypes.h.
const unsigned long long larcv::kINVALID_ULONGLONG = std::numeric_limits< unsigned long long >::max()
Used as an invalid value identifier for unsigned long long.
Definition at line 38 of file LArCVTypes.h.
const unsigned short larcv::kINVALID_USHORT = std::numeric_limits< unsigned short >::max()
Used as an invalid value identifier for unsigned unsigned short.
Definition at line 48 of file LArCVTypes.h.
const VoxelID_t larcv::kINVALID_VOXELID = kINVALID_ULONGLONG static
Invalid Voxel3DID_t definition.
Definition at line 31 of file DataFormatTypes.h.
Referenced by larcv::SparseTensor3D::emplace(), larcv::Voxel3DMeta::id(), larcv::Voxel3DMeta::invalid_voxel_id(), and larcv::Voxel3DMeta::shift().